Normation/rudder-plugins

Makefile, blank-template/src/main/scala-templates/limited/com/normation/plugins/BLANK/EnablePluginImpl.scala, datasources/src/main/scala-templates/limited/com/normation/plugins/datasources/EnablePluginImpl.scala, helloworld/Makefile, makefiles/make-plugins-common.mk, node-external-reports/Makefile, node-external-reports/src/main/scala-templates/limited/com/normation/plugins/nodeexternalreports/EnablePluginImpl.scala, plugins-common-private/Makefile, plugins-common-private/build.conf, plugins-common-private/pom.xml, plugins-common-private/src/main/scala/com/normation/plugins/ParsePluginLicense.scala, plugins-common/Makefile, plugins-common/build.conf, plugins-common/pom.xml
https://www.rudder-project.org/redmine/issues/12240
=> Fixes #12240: Add top-level make file target to generate licensed plugins

datasources/src/main/scala/com/normation/plugins/datasources/api/DataSourceApi.scala, datasources/src/main/scala/com/normation/plugins/datasources/api/DataSourceApiImpl.scala
https://www.rudder-project.org/redmine/issues/12255
=> Fixes #12255: Datasource compilation error with API provider trait

.gitignore, Makefile, makefiles/common-scala-plugin.mk, makefiles/find_m2_repo.sh, makefiles/global-vars.mk, makefiles/make-plugins-common.mk
https://www.rudder-project.org/redmine/issues/12391
=> Fixes #12391: Make maven faster and correct MAVEN_OPS

centreon/README.md
https://www.rudder-project.org/redmine/issues/12734
=> Fixes #12734: Add documentation for the Centreon plugin

api-authorizations/src/main/elm/sources/api-authorizations.elm, api-authorizations/src/main/elm/toserve/media.css, api-authorizations/src/main/scala/com/normation/plugins/apiauthorizations/ApiAccountsExtension.scala
https://www.rudder-project.org/redmine/issues/12843
=> Fixes #12843: UI enhancement for API ACL selection

api-authorizations/src/main/elm/sources/api-authorizations.elm, api-authorizations/src/main/scala/com/normation/plugins/apiauthorizations/ApiAccountsExtension.scala
https://www.rudder-project.org/redmine/issues/12936
=> Fixes #12936: Missing select all/none by categories

changes-validation/LICENSE, changes-validation/LICENSE_EXCEPTION, changes-validation/Makefile, changes-validation/README.asciidoc, changes-validation/build.conf, changes-validation/packaging/metadata, changes-validation/packaging/postinst, changes-validation/pom-template.xml, changes-validation/src/main/resources/template/ChangesValidationManagement.html, changes-validation/src/main/resources/toserve/changesvalidation/changes-validation.css, changes-validation/src/main/resources/toserve/changesvalidation/changes-validation.js, changes-validation/src/main/scala-templates/default/com/normation/plugins/changesvalidation/EnablePluginImpl.scala, changes-validation/src/main/scala-templates/limited/com/normation/plugins/changesvalidation/EnablePluginImpl.scala, changes-validation/src/main/scala/bootstrap/rudder/plugin/ChangesValidationConf.scala, changes-validation/src/main/scala/com/normation/plugins/changesvalidation/ChangesValidationPluginDef.scala, changes-validation/src/main/scala/com/normation/plugins/changesvalidation/DataTypes.scala, changes-validation/src/main/scala/com/normation/plugins/changesvalidation/WorkflowService.scala, changes-validation/src/main/scala/com/normation/plugins/changesvalidation/comet/WorkflowInformation.scala, changes-validation/src/main/scala/com/normation/plugins/changesvalidation/snippet/ChangesValidationSettings.scala, changes-validation/src/test/resources/logback-test.xml, main-build.conf
https://www.rudder-project.org/redmine/issues/12905
=> Fixes #12905: Create validation workflows plugins

node-external-reports/build.conf
https://www.rudder-project.org/redmine/issues/13071
=> Fixes #13071: Bad build.conf format breaks node-external-reports info displaying

vault/LICENSE, vault/Makefile, vault/README.md, vault/build.conf, vault/packaging/metadata, vault/packaging/postinst, vault/share/plugins/vault/20_cfe_basics/vault_lib.cf, vault/share/plugins/vault/30_generic_methods/variable_from_vault.cf, vault/share/plugins/vault/sample_vault.json
https://www.rudder-project.org/redmine/issues/12865
=> Fixes #12865: Vault plugin : Add a variable_from_vault generic method.

vault/share/plugins/vault/20_cfe_basics/vault_lib.cf, vault/share/plugins/vault/30_generic_methods/variable_from_vault.cf
https://www.rudder-project.org/redmine/issues/12959
=> Fixes #12959: Add direct token auth to the auth_modes for the Vault plugin

centreon/bin/centreon-plugin.py
https://www.rudder-project.org/redmine/issues/13496
=> Fixes #13496: Centreon plugin doesn't work with python 2.7

centreon/bin/centreon-plugin.py
https://www.rudder-project.org/redmine/issues/13571
=> Fixes #13571: Applying hosttemplate from generic method fails

change-validation/src/main/resources/template/ChangeValidationManagement.html, change-validation/src/main/scala/bootstrap/rudder/plugin/ChangeValidationConf.scala, change-validation/src/main/scala/com/normation/plugins/changevalidation/DataTypes.scala, change-validation/src/main/scala/com/normation/plugins/changevalidation/ValidationNeeded.scala, change-validation/src/main/scala/com/normation/plugins/changevalidation/WorkflowService.scala
https://www.rudder-project.org/redmine/issues/13559
=> Fixes #13559: Check node, not group, for need of change request

datasources/src/test/scala/com/normation/plugins/datasources/UpdateHttpDatasetTest.scala
https://www.rudder-project.org/redmine/issues/13733
=> Fixes #13733: On small hardware, datasource test timeout

Makefile, makefiles/common-plugin.mk
https://www.rudder-project.org/redmine/issues/13749
=> Fixes #13749: Allow to build no license plugin with licensed target

notify/README.adoc, notify/packaging/metadata
https://issues.rudder.io/issues/13924
=> Fixes #13924: Make python dependency a warning instead of check in notify packaging

change-validation/Makefile, change-validation/packaging/postinst
https://issues.rudder.io/issues/15185
=> Fixes #15185: validated user sql script is not packaged

README.adoc, api-authorizations/README.adoc, auth-backends/README.adoc, branding/README.asciidoc, centreon/README.adoc, change-validation/README.adoc, create-node-api/README.asciidoc, datasources/README.adoc, glpi/README.adoc, helloworld/README.asciidoc, node-external-reports/README.adoc, notify/README.adoc, scale-out-relay/README.asciidoc, src/main/g8/README.asciidoc, src/main/g8/src/main/scala-templates/default/com/normation/plugins/$plugin_pkg$/EnablePluginImpl.scala, src/main/g8/src/main/scala-templates/limited/com/normation/plugins/$plugin_pkg$/EnablePluginImpl.scala, src/main/g8/src/main/scala/bootstrap/rudder/plugin/$plugin_class$Conf.scala, user-management/README.asciidoc, vault/README.adoc, zabbix/README.adoc
https://issues.rudder.io/issues/15306
=> Fixes #15306:  Update link in readme to rudder.io and missing smarttag for create-node-api

openscap-report/LICENSE, openscap-report/LICENSE_EXCEPTION, openscap-report/Makefile, openscap-report/README.adoc, openscap-report/build.conf, openscap-report/configuration-repository/ncf/50_techniques/plugin_openscap_report/plugin_openscap_report.cf, openscap-report/configuration-repository/techniques/plugin_openscap_report/category.xml, openscap-report/packaging/metadata, openscap-report/packaging/postinst, openscap-report/packaging/prerm, openscap-report/src/node-external-reports.properties
https://issues.rudder.io/issues/16048
=> Fixes #16024: Make a plugin from the current OpenSCAP technique

qa-test
https://issues.rudder.io/issues/15249
=> Fixes #15249: Add set -e to qa-test in order to force its failure when a test is not passed

change-validation/src/main/scala/com/normation/plugins/changevalidation/ChangeRequestJdbcRepository.scala, change-validation/src/main/scala/com/normation/plugins/changevalidation/DataTypes.scala, change-validation/src/main/scala/com/normation/plugins/changevalidation/SupervisedTargetsReposiory.scala, change-validation/src/main/scala/com/normation/plugins/changevalidation/WorkflowJdbcRepository.scala, change-validation/src/main/scala/com/normation/plugins/changevalidation/WorkflowService.scala, change-validation/src/main/scala/com/normation/plugins/changevalidation/api/SupervisedTargetsApi.scala
https://issues.rudder.io/issues/15113
=> Fixes #15113: Missing logs in change validation plugin

user-management/src/main/elm/sources/ApiCalls.elm, user-management/src/main/elm/sources/DataTypes.elm, user-management/src/main/elm/sources/Init.elm, user-management/src/main/elm/sources/JsonDecoder.elm, user-management/src/main/elm/sources/JsonEncoder.elm, user-management/src/main/elm/sources/UserManagement.elm, user-management/src/main/elm/sources/View.elm, user-management/src/main/scala/com/normation/plugins/usermanagement/UserManagementService.scala, user-management/src/main/scala/com/normation/plugins/usermanagement/api/UserManagementApi.scala
https://issues.rudder.io/issues/16567
=> Fixes #16567: Be able to add a hashed password 

datasources/pom-template.xml, datasources/src/main/scala/com/normation/plugins/datasources/DataSourcesPluginDef.scala, datasources/src/main/scala/com/normation/plugins/datasources/Repository.scala, datasources/src/main/scala/com/normation/plugins/datasources/Scheduler.scala, datasources/src/main/scala/com/normation/plugins/datasources/UpdateHttpDataset.scala, datasources/src/test/scala/com/normation/plugins/datasources/UpdateHttpDatasetTest.scala, pom-template.xml
https://issues.rudder.io/issues/16926
=> Fixes #16926: Port datasources to zio RC18-2

qa-test
https://issues.rudder.io/issues/17032
=> Fixes #17032: Fix qa-test

scale-out-relay/src/main/scala/com/normation/plugins/scaleoutrelay/ScaleOutRelayPluginDef.scala
https://issues.rudder.io/issues/17160
=> Fixes #17160: On high load after a reboot, generation fails because scale-out-relay not OK

cis/README.adoc
https://issues.rudder.io/issues/17419
=> Fixes #17419: cleanup the documentation

scale-out-relay/src/main/scala/bootstrap/rudder/plugin/ScaleOutRelayConf.scala, scale-out-relay/src/main/scala/com/normation/plugins/scaleoutrelay/ScaleOutRelayService.scala
https://issues.rudder.io/issues/17570
=> Fixes #17570: Trigger promises generation when promoting a node to relay

openscap-policies/configuration/techniques/plugin_openscap_report.json
https://issues.rudder.io/issues/17347
=> Fixes #17347: update openscap technique to improve technique documentation

glpi/bin/glpi-plugin
https://issues.rudder.io/issues/18233
=> Fixes #18233: Plugin always tries to sent old inventories

cis/packaging/metadata
https://issues.rudder.io/issues/18248
=> Fixes #18248: rudder-api-client should be a dependency of CIS

change-validation/src/main/scala/com/normation/plugins/changevalidation/snippet/ChangeRequestChangesForm.scala, main-build.conf
https://issues.rudder.io/issues/19182
=> Fixes #19182: Change validation details page is not accessible anymore when a Node group query has been modified

change-validation/pom-template.xml, change-validation/src/main/scala/bootstrap/rudder/plugin/ChangeValidationConf.scala, change-validation/src/main/scala/com/normation/plugins/changevalidation/NotificationService.scala, change-validation/src/test/resources/emails/change-validation-email.conf, change-validation/src/test/scala/com/normation/plugins/changevalidation/TestEmailService.scala
https://issues.rudder.io/issues/19352
=> Fixes #19352: Illegal address when no replyTo configured

plugins-common/pom-template.xml
https://issues.rudder.io/issues/19884
=> Fixes #19884: Update dependencies in parents-plugin to last rudder version

auth-backends/README.adoc, auth-backends/pom-template.xml, auth-backends/src/main/resources/applicationContext-security-auth-oauth2.xml, auth-backends/src/main/resources/applicationContext-security-auth-oidc.xml, auth-backends/src/main/scala/bootstrap/rudder/plugin/AuthBackendsConf.scala, auth-backends/src/main/scala/com/normation/plugins/authbackends/DataTypes.scala, auth-backends/src/main/scala/com/normation/plugins/authbackends/Oauth2Authentication.scala, auth-backends/src/main/scala/com/normation/plugins/authbackends/snippet/Oauth2LoginBanner.scala
https://issues.rudder.io/issues/20778
Add the possibility to have an Oauthv2/OIDC (openid connect) SSO authentication in Rudder. 
Under the hood, it uses spring-security module for Oauthv2 (https://docs.spring.io/spring-security/reference/5.7/reactive/oauth2/index.html). 
The main difficulties is that contrary to other existing backend, Oauthv2 is a change in the list of security filter chain, not a new authentication "data base" for the web authentication filter. 
So we need to hack existing chain (configured in main rudder) and hand-build missing filters for oauth/oidc and but them back at the correct place. This is complicated. It's done in `AuthBackendsConf.scala` in `AuthBackendsSpringConfiguration`.
In that class: 
- we read and update existing filter chain in …
=> Fixes #20778: Add Oauth2/openid connect backend

datasources/pom-template.xml, datasources/src/test/resources/logback-test.xml, datasources/src/test/scala/com/normation/plugins/datasources/UpdateHttpDatasetTest.scala, helloworld/src/main/scala/bootstrap/rudder/plugin/HelloWorldConf.scala, main-build.conf, plugins-common/pom-template.xml
https://issues.rudder.io/issues/21115
Main changes here are:
- update the list of `provided` dependencies. The command needed a little update, perhaps due to changes in mvn plugins. Sorting was impacted.
- remove `http4s`, add `zio-http`. Their API are very, very near, so it was okayish to migrate. 
Notice that `zio-http` seems to be even faster than http4s and much simpler, so we could certainly use that in other tests.
=> Fixes #21115: Update dependencies from #21102

auth-backends/README.adoc
https://issues.rudder.io/issues/21897
=> Fixes #21897: OIDC doc contains a merge diff resolution comment

auth-backends/src/main/scala/bootstrap/rudder/plugin/AuthBackendsConf.scala, auth-backends/src/main/scala/com/normation/plugins/authbackends/Oauth2Authentication.scala, branding/src/main/scala/com/normation/plugins/branding/BrandingConfService.scala, branding/src/main/scala/com/normation/plugins/branding/BrandingPluginDef.scala, change-validation/src/main/scala/com/normation/plugins/changevalidation/ChangeValidationPluginDef.scala, change-validation/src/main/scala/com/normation/plugins/changevalidation/NotificationService.scala, change-validation/src/main/scala/com/normation/plugins/changevalidation/WorkflowService.scala, datasources/pom-template.xml, datasources/src/main/scala/bootstrap/rudder/plugin/DataSourcesConf.scala, datasources/src/main/scala/com/normation/plugins/datasources/DataSourcesPluginDef.scala, datasources/src/main/scala/com/normation/plugins/datasources/DataTypes.scala, datasources/src/main/scala/com/normation/plugins/datasources/QueryService.scala, datasources/src/main/scala/com/normation/plugins/datasources/Repository.scala, datasources/src/main/scala/com/normation/plugins/datasources/Scheduler.scala, datasources/src/main/scala/com/normation/plugins/datasources/Serialization.scala, datasources/src/main/scala/com/normation/plugins/datasources/UpdateHttpDataset.scala, datasources/src/main/scala/com/normation/plugins/datasources/api/DataSourceApiImpl.scala, datasources/src/test/scala/com/normation/plugins/datasources/UpdateHttpDatasetTest.scala, datasources/src/test/scala/com/normation/plugins/datasources/api/RestDataSourceTest.scala, main-build.conf, node-external-reports/src/main/scala/com/normation/plugins/nodeexternalreports/NodeExternalReportPluginDef.scala, openscap/src/main/scala/com/normation/plugins/openscappolicies/services/ReportSanitizer.scala, plugins-common/pom-template.xml, scale-out-relay/src/main/scala/com/normation/plugins/scaleoutrelay/ScaleOutRelayService.scala, user-management/src/main/scala/com/normation/plugins/usermanagement/UserManagementPluginDef.scala
https://issues.rudder.io/issues/21826
Same general changes than https://github.com/Normation/rudder/pull/4507 but in addition, some more related to Datasources. We use since rudder 7.2 `zhttp` for the tests which simplifies a lot the cats dependencies spagghetti ball. The bad point is that for `ZIO 2`, we need to use `2.0.0.x` version, which happens to have a breaking change in the semantic of URL pattern matching. It caused some troubles to be identified. Most of the other changes in [UpdateHttpDatasetTest.scala](https://github.com/Normation/rudder-plugins/pull/501/files#diff-44d43b7b8b22fabae4537dae04dcf91ea30fe5594278681a49ffe9e43951e4e8) 
Are related to either reodering of code, some cleaning (partly thanks to better ZIO features and partly because the dev are better with it). 
The …
=> Fixes #21826: Port plugins to ZIO2

centreon/packaging/metadata
https://issues.rudder.io/issues/21889
=> Fixes #21889: package dependency is named python3-requests and not python-requests

user-management/src/main/elm/sources/UserManagement.elm, user-management/src/main/scala/com/normation/plugins/usermanagement/DataTypes.scala, user-management/src/main/scala/com/normation/plugins/usermanagement/UserManagementService.scala, user-management/src/main/scala/com/normation/plugins/usermanagement/api/UserManagementApi.scala, user-management/src/test/scala/com/normation/plugins/usermanagement/RoleComputationTest.scala
https://issues.rudder.io/issues/22349
There is a lot of things to change in the way that plugin works, but in that PR I limited to what is the minimum to make it compatible with Rudder 7.3 changes + an auto-backup of `rudder-user.xml` file in case of problem - because we didn't have anything for that, and it would make rudder broken. 
So, the changes related to API changes in core are: 
- reflect name changes from rudder (`RudderRoles`)
- update function from `Box` to `ZIO` (reflecting changes in backend + general direction of where we are going)
Other changes that were needed:
- add a backup/rollback logic if something goes badly when writting the new `rudder-users.xml` file. At least, let the user know that he is not hopeless. 
- remove useless duplicate call to reload after each …
=> Fixes #22349: Update user plugin to manage update custom roles

scale-out-relay/packaging/postinst
https://issues.rudder.io/issues/22492
Revert back line that were incorrectly upmerged in https://github.com/Normation/rudder-plugins/commit/13d42153faf61aa8a9513dbf6deea3985d719703#diff-7507dfd2e40a78a835e6d6b9f355a48fdc9005811548262f7a918490bc02954d
=> Fixes #22492: Scale-out-relay: missing command node-to-relay due to upmerge

user-management/README.adoc, user-management/src/main/elm/sources/DataTypes.elm, user-management/src/main/elm/sources/Init.elm, user-management/src/main/elm/sources/JsonDecoder.elm, user-management/src/main/elm/sources/JsonEncoder.elm, user-management/src/main/elm/sources/UserManagement.elm, user-management/src/main/elm/sources/View.elm, user-management/src/main/scala/com/normation/plugins/usermanagement/DataTypes.scala, user-management/src/main/scala/com/normation/plugins/usermanagement/Serialization.scala, user-management/src/main/scala/com/normation/plugins/usermanagement/UserManagementService.scala, user-management/src/main/scala/com/normation/plugins/usermanagement/api/UserManagementApi.scala
https://issues.rudder.io/issues/22580
A pr that mostly change `role` into `permissions`. The main point of attention is to remain able to read the old `role` tag from rudder 7.2-
=> Fixes #22580: Plugin writes "roles" in place of "permissions"

auth-backends/README.adoc
https://issues.rudder.io/issues/22513
This is a modification to advertise the use of `rudder-web.propertise.d` - no impact on code, it's just doc.
=> Fixes #22513: LDAP config example advocate for editing rudder-web.properties in place of using a dedicated file

change-validation/src/main/scala/bootstrap/rudder/plugin/ChangeValidationConf.scala, change-validation/src/main/scala/bootstrap/rudder/plugin/MigrateSupervisedGroups.scala, change-validation/src/main/scala/com/normation/plugins/changevalidation/ChangeValidationPluginDef.scala, change-validation/src/main/scala/com/normation/plugins/changevalidation/DataTypes.scala, change-validation/src/main/scala/com/normation/plugins/changevalidation/UnsupervisedTargetsReposiory.scala, change-validation/src/main/scala/com/normation/plugins/changevalidation/ValidationNeeded.scala, change-validation/src/main/scala/com/normation/plugins/changevalidation/api/SupervisedTargetsApi.scala
https://issues.rudder.io/issues/14330
Make the all groups being supervised by default, and new groups automatically supervised. 
To achieve that without complexity and a need to look to group creation, we just invert what we save in base: we save unsupervised target, and invert the list to get the supervised ones (we were already retrieving all the groups where performance matters, and the invert is trivial, so it should not change much regarding perf). 
To make migration transparent, on first use we read all supervised targets, invert set based on current group lib, and save the new set of unsupervised targets.
We change the name of the file were supervised groups were persisted to `unsupervised-groups.json`, which give us a way to know if the migration already happened.
We still need to …
=> Fixes #14330: By default, no group are supervised and new group are not supervised 

auth-backends/README.adoc, auth-backends/src/main/scala/bootstrap/rudder/plugin/AuthBackendsConf.scala, auth-backends/src/main/scala/com/normation/plugins/authbackends/Oauth2Authentication.scala
https://issues.rudder.io/issues/22738
We already have a class in charge of creating a "rudder user" from a "oidc token" (`RudderOidcUserService`). So that PR only customize the "load roles" part so that in addition to the rudder roles, we look at the added configuration parameters of the OIDC providers to see if and what we have to do with OIDC list of role name provided in the token. 
The role resolution from name use the existing logic for the role names in `rudder-users.xml`, nothing new here. 
The most complicated part was the configuration properties part (bring the 3 new property values to the RudderOidcUserService). It needed changes in the spring beans declaration, and it's always a mess. 
Most of the other changes are doc and logging things so that it is very clear that an OIDC …
=> Fixes #22738: OIDC provided custom role list

datasources/src/main/scala/com/normation/plugins/datasources/Scheduler.scala, datasources/src/test/scala/com/normation/plugins/datasources/UpdateHttpDatasetTest.scala
https://issues.rudder.io/issues/22971
So the problem seems to be that depending of the timing, when we observe f1 status, it is either still running because init if not done (typically on a slow machine where the foreign datasource answer takes time to be completed) or suspended.
Now, the test check for both status (they are both ok at that point).
I also added a new check that the reloaded datasource fiber is actually live.
=> Fixes #22971: Spurious test error on the killing of old fiber on datasource save/delete

user-management/README.adoc
https://issues.rudder.io/issues/23079
=> Fixes #23079: <authentications> must not have a "s" in user-management doc

auth-backends/README.adoc, auth-backends/src/main/scala/bootstrap/rudder/plugin/AuthBackendsConf.scala, auth-backends/src/main/scala/com/normation/plugins/authbackends/AuthBackendsRepository.scala
https://issues.rudder.io/issues/23112
The role mapping was only done in a OIDC case, in a ` buildUser` function in the OIDC specialized `loadUser` function.
That PR factorize-out the `buildUser` function to put it into the generic `RudderUserServerMapping` trait. That works well because we retrieve group attribute with a function (`getAttribute[java.util.ArrayList[String]](reg.roles.attributeName)`) that is common to both protocol. 
The remaining bits are just gluing:
- pass the protocol name as a parameter for have correct logs
- add the `RudderClientRegistrationRepository` in the trait because it is now required for both, and change class parameters to match it
- generalize the user details creation to adapt to both `OAuth2` and `OIDC` case in there respective implementation.
Also …
=> Fixes #23112: Add the role-retrieving OIDC feature to OAuth2

change-validation/src/main/scala/com/normation/plugins/changevalidation/WorkflowService.scala
https://issues.rudder.io/issues/22993
The change-request was blocked in state "deployment" but can be deployed (the changes was deployed even if the change-request is still in the "pending deployment" section. The problem only occurs for pending deployment request, the step valaidation to deployed, is working as expected.
The bug was that it was missing the logic for deployment to deployed part
The bug is only present in 7.3 due to https://github.com/Normation/rudder-plugins/commit/3103cf4338d98ed30425e4fbb5e31ba449433141 the logic was removed 
1. install the plugin change-validation
2. create a group and add node in it
3. activate change request in the plugin page
4. modify the name
5. Check that a change request is generated
6. Validate the change request, the change request should be …
=> Fixes #22993: Can't deploy, “Configuration state of the object modified by this change request has changed” looping

api-authorizations/src/main/elm/sources/UserApiToken.elm, api-authorizations/src/main/scala/com/normation/plugins/apiauthorizations/UserTokenApiDefinition.scala, main-build.conf
https://issues.rudder.io/issues/23243
Matching https://github.com/Normation/rudder/pull/4971 changes.
=> Fixes #23243: Hash API tokens - plugin

user-management/README.adoc, user-management/src/main/elm/sources/DataTypes.elm, user-management/src/main/elm/sources/Init.elm, user-management/src/main/elm/sources/JsonDecoder.elm, user-management/src/main/elm/sources/UserManagement.elm, user-management/src/main/elm/sources/View.elm, user-management/src/main/scala/com/normation/plugins/usermanagement/DataTypes.scala
https://issues.rudder.io/issues/23254
A first PR for the problematic of dynamic role. This one is done so that it is compatible with current Rudder 7.3 and so we don't have the real configuration option for OIDC role override. So we just add a generic warning message to avoid surprise. 
This PR also correct the fact that the list of authentication providers is hard coded in user management (to provide human readable version ?) and that authentication provider out of that not-maintained list are IGNORED. 
At some point, we will have a type for providers, with their properties (does it override roles, etc), but we should never ignore unknown providers! I just removed the types, because they would likely be something else. 
This was why OIDC was not listed and so user got false information. …
=> Fixes #23254: User management plugin incorrectly understand OIDC roles

auth-backends/src/main/scala/com/normation/plugins/authbackends/api/AuthBackendsApi.scala, branding/src/main/scala/com/normation/rudder/rest/BrandingApiSchema.scala, change-validation/src/main/scala/bootstrap/rudder/plugin/ChangeValidationConf.scala, change-validation/src/main/scala/com/normation/plugins/changevalidation/WorkflowService.scala, change-validation/src/main/scala/com/normation/plugins/changevalidation/api/ChangeRequestApi.scala, change-validation/src/main/scala/com/normation/plugins/changevalidation/api/SupervisedTargetsApi.scala, change-validation/src/main/scala/com/normation/plugins/changevalidation/api/ValidatedUserApi.scala, datasources/src/main/scala/com/normation/plugins/datasources/api/DataSourceApi.scala, user-management/src/main/scala/com/normation/plugins/usermanagement/api/UserManagementApi.scala, user-management/src/test/scala/com/normation/plugins/usermanagement/RoleComputationTest.scala
https://issues.rudder.io/issues/23348
Use the new facility provided by https://github.com/Normation/rudder/pull/5004 to declare rights along with the API schema. Correct a bunch of API rights which were using the default one (`Administrator.Write`) in place of something less powerful (often `Administration.Read`)
For change validation: 
- the dedicated api right mapper is not useful anymore, 
- it was missing `ValidatedUser` in the list of aggregated endpoints, which was causing specific additional problems.
=> Fixes #23348: not allowed to access errors because rudder plugins are missing AuthorizationApiMapping 

auth-backends/README.adoc
https://issues.rudder.io/issues/23419
=> Fixes #23419: Bad doc for known authentication backends

change-validation/src/main/elm/sources/Init.elm
https://issues.rudder.io/issues/17809
Documentation says the value is in milliseconds
=> Fixes #17809: If tables are missing, the error notification toast disappears almost instantly

datasources/README.adoc, datasources/src/main/scala/com/normation/plugins/datasources/QueryService.scala, datasources/src/main/scala/com/normation/plugins/datasources/Repository.scala, datasources/src/main/scala/com/normation/plugins/datasources/api/DataSourceApi.scala, datasources/src/main/scala/com/normation/plugins/datasources/api/DataSourceApiImpl.scala, datasources/src/test/scala/com/normation/plugins/datasources/UpdateHttpDatasetTest.scala
https://issues.rudder.io/issues/23563
Delete property related to datasource when the datasource is deleted. 
Main changes: 
- factor out the logic to update the node property for the datasource so that it can be used in both update and delete method, 
- add a `cause` to delete. Likely other methods from the repo should have it too. 
- add a `deleteAll` method in `HttpQueryDataSourceService` because it's really it that has the logic to things on node, not the repository (the repo is just the warrant for datasource backend/liveness consistency)
- add a unit test that checks that the properties are really gone when the datasource is deleted.
Note: deletion of a datasource will only remove properties with the `datasource` provider. 
It allows the following use case: 
- configure datasources …
=> Fixes #23563: When a datasource is deleted, its properties should be deleted

api-authorizations/src/main/elm/sources/ApiAuthorizations.elm, api-authorizations/src/main/resources/toserve/apiauthorizations/media.css
https://issues.rudder.io/issues/21724
Instead of the 'category' title having a padding of 40px, the icon has a width of 40px.
The icon is also in a label now, so it allows to do the fold :partying_face:
=> Fixes #21724: Categories can't be folded in ACL API with authorization plugin

branding/pom-template.xml, branding/src/main/scala/bootstrap/rudder/plugin/BrandingPluginConf.scala, branding/src/main/scala/com/normation/plugins/branding/BrandingConf.scala, branding/src/main/scala/com/normation/plugins/branding/BrandingConfService.scala, branding/src/main/scala/com/normation/plugins/branding/api/BrandingApi.scala, branding/src/main/scala/com/normation/plugins/branding/snippet/CommonBranding.scala, branding/src/main/scala/com/normation/plugins/branding/snippet/LoginBranding.scala, branding/src/main/scala/com/normation/rudder/rest/BrandingApiSchema.scala, branding/src/test/resources/branding_api/api_branding.yml, branding/src/test/scala/com/normation/plugins/branding/BrandingConfServiceTest.scala, branding/src/test/scala/com/normation/plugins/branding/api/BrandingApiTest.scala, openscap/pom-template.xml, openscap/src/main/scala/bootstrap/rudder/plugin/OpenscapPoliciesConf.scala, openscap/src/main/scala/com/normation/plugins/openscappolicies/api/OpenScapApi.scala, openscap/src/main/scala/com/normation/plugins/openscappolicies/services/OpenScapReportReader.scala, openscap/src/test/resources/openscap_api/api_openscap.yml, openscap/src/test/scala/com/normation/plugins/openscappolicies/api/OpenScapApiTest.scala, scale-out-relay/pom-template.xml, scale-out-relay/src/main/scala/bootstrap/rudder/plugin/ScaleOutRelayConf.scala, scale-out-relay/src/main/scala/com/normation/plugins/scaleoutrelay/api/ScaleOutRelayApi.scala, scale-out-relay/src/test/resources/scaleoutrelay_api/api_scaleoutrelay.yml, scale-out-relay/src/test/scala/com/normation/plugins/scaleoutrelay/MockServices.scala, scale-out-relay/src/test/scala/com/normation/plugins/scaleoutrelay/api/ScaleOutRelayApiTest.scala
https://issues.rudder.io/issues/23760
Removing any occurrence of lift-json in the three plugins : branding, openscap, scale-out-relay.
In the branding plugin there is an outdated serial format (from the v5.0 of rudder), which should be removed later. The openscap plugin has only unused imports from lift-json, I took the opportunity to add yaml tests for the API
=> Fixes #23760: Migrate branding, openscap, scale-out-relay to zio-json

api-authorizations/src/main/scala/bootstrap/rudder/plugin/ApiAuthorizationsConf.scala, api-authorizations/src/main/scala/com/normation/plugins/apiauthorizations/ApiAccountsExtension.scala, api-authorizations/src/main/scala/com/normation/plugins/apiauthorizations/UserJsonCodec.scala, api-authorizations/src/main/scala/com/normation/plugins/apiauthorizations/UserTokenApiDefinition.scala, api-authorizations/src/test/resources/authorizations_api/api_users.yml, api-authorizations/src/test/scala/com/normation/plugins/apiauthorizations/MockServices.scala, api-authorizations/src/test/scala/com/normation/plugins/apiauthorizations/api/UserApiTest.scala, auth-backends/src/main/scala/bootstrap/rudder/plugin/AuthBackendsConf.scala, auth-backends/src/main/scala/com/normation/plugins/authbackends/AuthBackendsRepository.scala, auth-backends/src/main/scala/com/normation/plugins/authbackends/DataTypes.scala, auth-backends/src/main/scala/com/normation/plugins/authbackends/api/AuthBackendsApi.scala, auth-backends/src/test/resources/authbackends_api/api_authbackends.yml, auth-backends/src/test/scala/com/normation/plugins/authbackends/api/AuthBackendsApiTest.scala
https://issues.rudder.io/issues/23775
Migrating api-authorizations, there needed to be a rewrite of [the lift-json serializer](https://github.com/Normation/rudder/blob/master/webapp/sources/rudder/rudder-core/src/main/scala/com/normation/rudder/apidata/RestDataSerializer.scala#L669) into a data transfer case class and the added tests ensures that the display/hiding of the token value is the same after migrating to zio-json...
=> Fixes #23775: Migrate api-authorizations, auth-backends to zio-json

datasources/src/main/scala/bootstrap/rudder/plugin/DataSourcesConf.scala, datasources/src/main/scala/com/normation/plugins/datasources/DataTypes.scala, datasources/src/main/scala/com/normation/plugins/datasources/Repository.scala, datasources/src/main/scala/com/normation/plugins/datasources/Serialization.scala, datasources/src/main/scala/com/normation/plugins/datasources/api/DataSourceApi.scala, datasources/src/main/scala/com/normation/plugins/datasources/api/DataSourceApiImpl.scala, datasources/src/test/resources/datasources_api/api_datasources.yml, datasources/src/test/scala/com/normation/plugins/datasources/RepositoryTest.scala, datasources/src/test/scala/com/normation/plugins/datasources/UpdateHttpDatasetTest.scala, datasources/src/test/scala/com/normation/plugins/datasources/api/RestDataSourceTest.scala
https://issues.rudder.io/issues/23805
There are two different use cases of deserialization in the plugin, that were in the `OptionalJson` and `CompleteJson`  extractors : 
* the _complete_ one for representing a whole datasource properties object with **all fields mandatory**
* the _optional_ one for representing a subset of them, so with **all fields optional** 
We needed to add case classes with **full** representation of a datasource, and derive json codecs accordingly so that the migration keeps the json format and validation constraints.
The previously named "wrappers" classes, with optional fields has been renamed to **patch** classes, as they are used to update a datasource (patch is the operation name as defined by _chimney_ for that use case). These "patch" classes have the same …
=> Fixes #23805: Migrate datasource plugin to zio-json

auth-backends/README.adoc
https://issues.rudder.io/issues/23919
=> Fixes #23919: One note section is not rendered in auth-backend plugin

change-validation/src/main/scala/bootstrap/rudder/plugin/MigrateSupervisedGroups.scala, change-validation/src/main/scala/com/normation/plugins/changevalidation/ChangeRequestJdbcRepository.scala, change-validation/src/main/scala/com/normation/plugins/changevalidation/ChangeRequestRepository.scala, change-validation/src/main/scala/com/normation/plugins/changevalidation/DataTypes.scala, change-validation/src/main/scala/com/normation/plugins/changevalidation/UnsupervisedTargetsReposiory.scala, change-validation/src/main/scala/com/normation/plugins/changevalidation/WorkflowJdbcRepository.scala, change-validation/src/main/scala/com/normation/plugins/changevalidation/api/ChangeRequestApi.scala, change-validation/src/main/scala/com/normation/plugins/changevalidation/api/SupervisedTargetsApi.scala
https://issues.rudder.io/issues/23907
Adding the `ruleId`, `directiveId` and `nodeGroupId` query params filter support for listing change requests.
I fixed compilations issues along the way (missing type declaration for implicits).
There exists repository methods to `getByRule` etc. but the state is queried with a pattern : `LIKE 'Pending%'` in SQL. In the end the result is the same as when passing explicit state values : `IN ('Pending deployment', 'Pending validation')`, I preferred the latter to also avoid conflicts when refactoring from `Box` to `IOResult`
=> Fixes #23907: List change requests with additional filters

auth-backends/README.adoc, auth-backends/src/main/scala/bootstrap/rudder/plugin/AuthBackendsConf.scala, auth-backends/src/main/scala/com/normation/plugins/authbackends/DataTypes.scala, auth-backends/src/main/scala/com/normation/plugins/authbackends/Oauth2Authentication.scala, user-management/src/main/scala/bootstrap/rudder/plugin/UserManagementConf.scala, user-management/src/main/scala/com/normation/plugins/usermanagement/UserManagementService.scala, user-management/src/main/scala/com/normation/plugins/usermanagement/api/UserManagementApi.scala
https://issues.rudder.io/issues/23444
That change needs https://github.com/Normation/rudder/pull/5121.
The changes in `user-management` are just the minimum to make things compile. A big change is still needed: we must use information from database in that plugin, which is not done here. 
The changes in `authentication-backend` add the possibility for `oidc/oauth2` backend to auto-provision users in Rudder if their authentication was successful. 
That possibility is governed by a new IdP propery: `rudder.auth.oauth2.provider.${idp}.enableProvisionning=true`
The logic change is then rather small and mainly in [AuthBackendsConf.scala](https://github.com/Normation/rudder-plugins/pull/603/files#diff-8fe302fecad34e77c8d7fa30f3efdf0110c77048e1f14006e4855dc1c60e73d9): on authentication success, …
=> Fixes #23444: Impact of adding UserInfo base on public plugins

openscap/pom-template.xml
https://issues.rudder.io/issues/24004
=> Fixes #24004: Add neko-htmlUnit as dependency due to security checks

_typos.toml, change-validation/pom-template.xml, change-validation/src/main/scala/bootstrap/rudder/plugin/ChangeValidationConf.scala, change-validation/src/main/scala/com/normation/plugins/changevalidation/ChangeRequestJdbcRepository.scala, change-validation/src/main/scala/com/normation/plugins/changevalidation/ChangeRequestJson.scala, change-validation/src/main/scala/com/normation/plugins/changevalidation/NotificationService.scala, change-validation/src/main/scala/com/normation/plugins/changevalidation/WorkflowJdbcRepository.scala, change-validation/src/main/scala/com/normation/plugins/changevalidation/WorkflowService.scala, change-validation/src/main/scala/com/normation/plugins/changevalidation/api/ChangeRequestApi.scala, change-validation/src/main/scala/com/normation/plugins/changevalidation/snippet/ChangeRequestChangesForm.scala, change-validation/src/test/resources/changevalidation_api/api_changerequest.yml, change-validation/src/test/scala/com/normation/plugins/changevalidation/ChangeRequestJdbcRepositoryTest.scala, change-validation/src/test/scala/com/normation/plugins/changevalidation/MockServices.scala, change-validation/src/test/scala/com/normation/plugins/changevalidation/TestEmailService.scala, change-validation/src/test/scala/com/normation/plugins/changevalidation/WorkflowJdbcRepositoryTest.scala, change-validation/src/test/scala/com/normation/plugins/changevalidation/api/ChangeRequestApiTest.scala
https://issues.rudder.io/issues/23831
This PR migrates only the zio-json parts of the change request APIs. It consists in : 
* adding tests to the API and the database which is left untouched
* removing usage of `RestExtractorService` from Rudder which is the only part using lift-json indirectly
A whole new ADT tree needed to be created to be in par with the domain model of `ChangeRequest`, and we heavily use _chimney_ to do the mapping, see the [ChangeRequestJson.scala](https://github.com/Normation/rudder-plugins/blob/eebed5083c2ba840ef6919314938d7e5b8178c4b/change-validation/src/main/scala/com/normation/plugins/changevalidation/ChangeRequestJson.scala) file. This time, we use the `PartialTransformer` from _chimney_ because serialization could result in errors anywhere in the …
=> Fixes #23831: Migrate change request API in change-validation to zio-json

auth-backends/src/main/scala/bootstrap/rudder/plugin/AuthBackendsConf.scala, auth-backends/src/main/scala/com/normation/plugins/authbackends/api/AuthBackendsApi.scala
https://issues.rudder.io/issues/24042
Test for the attribute existence in the map to provide a better warning log if it's missing:
=> Fixes #24042: When the Oauth2 role provisioning attribute is incorrect, the error is misleading

makefiles/common.mk
https://issues.rudder.io/issues/24127
Solution: split apport the declaration of files from the declaration of targets
=> Fixes #24127: Let the plugins Makefile build target without including them in the resulting rpkg

change-validation/src/test/scala/com/normation/plugins/changevalidation/MockServices.scala
https://issues.rudder.io/issues/24185
Needed to compile tests since https://github.com/Normation/rudder/pull/5298/files#diff-2d8cf21151c3dfe2e8774dfec8128c71392431cc0256299979b9843ba24dba4fR241
=> Fixes #24185: Group repository in tests should get by ids

auth-backends/src/main/scala/bootstrap/rudder/plugin/AuthBackendsConf.scala, auth-backends/src/main/scala/com/normation/plugins/authbackends/Oauth2Authentication.scala, auth-backends/src/test/scala/com/normation/plugins/authbackends/TestReadOidcConfig.scala
https://issues.rudder.io/issues/24182
This PR provides two main things: 
- a way to map IdP provided roles to rudder internal roles, and optionnally to restrict IdP addressable roles to only the mapped one
- configuration option to use IdP Single Log Out by configuring a logout url (and post logout redirect url)
The code is not very interesting and mostly deals with adding option, reading them, logs and spring workaround. 
For role, we just have a new layer of mapping that uses the `Alias` role. 
For redirect, we just have a new `PostLogoutAction` that build the correct URL (the main changes are in rudder).
=> Fixes #24182: Add a role mapping and filtering for OIDC provided roles

user-management/src/main/elm/sources/ApiCalls.elm, user-management/src/main/elm/sources/DataTypes.elm, user-management/src/main/elm/sources/Init.elm, user-management/src/main/elm/sources/JsonDecoder.elm, user-management/src/main/elm/sources/JsonEncoder.elm, user-management/src/main/elm/sources/UserManagement.elm, user-management/src/main/elm/sources/View.elm, user-management/src/main/resources/toserve/usermanagement/user-management.css, user-management/src/main/scala/com/normation/plugins/usermanagement/DataTypes.scala, user-management/src/main/scala/com/normation/plugins/usermanagement/api/UserManagementApi.scala, user-management/src/main/scala/com/normation/plugins/usermanagement/snippet/UserPlugin.scala, user-management/src/test/resources/usermanagement_api/api_usermanagement.yml, user-management/src/test/scala/com/normation/plugins/usermanagement/RoleComputationTest.scala
https://issues.rudder.io/issues/24184
Basically we change the API format to separate _roles_ and _authorizations_, and also to add some fields, now the meaning of the fields are :
* `permissions` : roles only, without any authorizations
* `authz` : all authorizations (or "rights" if you prefer) associated with the `permissions`
* `rolesCoverage` : all inferred roles from all user authorizations, a superset of `permissions`
* `customRights` : set of custom authorizations that were manually added (not related to any `permissions`)
In the UI we add a "readonly section" (below the "Delete" and "Save" buttons to edit the user), in which we display the authorizations and the inferred roles (the roles can still be edited in the same field as before) :
Now the UI is more consistent, we can remove …
=> Fixes #24184: User management roles and permissions are intermingled in the UI

main-build.conf, makefiles/global-vars.mk
https://issues.rudder.io/issues/24191
Add a variable for the version to use in rpdk metadata so that rudder package is happy. It's not a solid way to do it, we should avoid to port it to 7.3 branch when merging - but at least, it will be easy to find/correct if merged in main branches by error.
=> Fixes #24191: Make version of backport branch ok for rudder-package

user-management/src/main/elm/sources/View.elm, user-management/src/main/resources/toserve/usermanagement/user-management.css
https://issues.rudder.io/issues/24187
This fix uses the grid system of Bootstrap 3 which has changed in Bootstrap 5 so we will do another fix for the 8.1 branch
=> Fixes #24187: Users cards are not evenly aligned and leave some blank space 

glpi/bin/glpi-plugin
https://issues.rudder.io/issues/24119
=> Fixes #24119: GLPI plugin fails to send inventory

change-validation/src/main/resources/template/ChangeValidationManagement.html, change-validation/src/main/scala/bootstrap/rudder/plugin/ChangeValidationConf.scala, change-validation/src/main/scala/com/normation/plugins/changevalidation/snippet/ChangeValidationSettings.scala
https://issues.rudder.io/issues/24206
We use the configuration from https://github.com/Normation/rudder/pull/5404.
The checkbox behaves the same as the ones for enabling/disabling change requests :
=> Fixes #24206: We need an option to force validation of change requests

auth-backends/src/main/scala/bootstrap/rudder/plugin/AuthBackendsConf.scala
https://issues.rudder.io/issues/24296
This depends on the `debugString` method introduced in https://github.com/Normation/rudder/pull/5414
=> Fixes #24296: Log on user api authorizations should use a debug string for ACL

user-management/src/main/elm/sources/ApiCalls.elm, user-management/src/main/elm/sources/DataTypes.elm, user-management/src/main/elm/sources/Init.elm, user-management/src/main/elm/sources/JsonDecoder.elm, user-management/src/main/elm/sources/JsonEncoder.elm, user-management/src/main/elm/sources/UserManagement.elm, user-management/src/main/elm/sources/View.elm, user-management/src/main/resources/toserve/usermanagement/user-management.css, user-management/src/main/scala/com/normation/plugins/usermanagement/DataTypes.scala, user-management/src/main/scala/com/normation/plugins/usermanagement/UserManagementService.scala, user-management/src/main/scala/com/normation/plugins/usermanagement/api/UserManagementApi.scala, user-management/src/test/resources/usermanagement_api/api_usermanagement.yml, user-management/src/test/scala/com/normation/plugins/usermanagement/MockServices.scala
https://issues.rudder.io/issues/24298
* Splitting the endpoints in 2 : the existing one should only be used for the "roles" and "password" update, the new one to update user info : "name", "email" and "otherInfo"
* Updating the display to keep consistency and have clearer messages when roles are defined both in the users.xml file and from the provider. For that we have migrated the "role extension" ADT from the plugin to Rudder [in this PR](https://github.com/Normation/rudder/pull/5428), and pattern matching on it now makes the logic of handling both file and external provider more fluent.
=> Fixes #24298: Display current session permission and split appart form to update user details

auth-backends/README.adoc
https://issues.rudder.io/issues/24384
=> Fixes #24384: Documentation for OIDC properties is not up to date

auth-backends/src/main/scala/bootstrap/rudder/plugin/AuthBackendsConf.scala
https://issues.rudder.io/issues/24394
=> Fixes #24394: Autoprovisioned users don't have access to any nodes

api-authorizations/src/main/scala/com/normation/plugins/apiauthorizations/ApiAccountsExtension.scala, api-authorizations/src/main/scala/com/normation/plugins/apiauthorizations/UserTokenApiDefinition.scala, api-authorizations/src/test/scala/com/normation/plugins/apiauthorizations/api/UserApiTest.scala
https://issues.rudder.io/issues/24450
=> Fixes #24450: Update API ACL plugin

auth-backends/src/main/scala/com/normation/plugins/authbackends/snippet/Oauth2LoginBanner.scala, user-management/src/main/elm/sources/View.elm, user-management/src/main/style/user-management.css
https://issues.rudder.io/issues/24434
Mainly the user management cards in the dashboard are impacted by bootstrap 5 upgrade : the `row` class is no longer needed.
Along with that the login page also uses classes which were renamed / render differently in bootstrap 5, now we have :
=> Fixes #24434: Fix UI issues caused by bootstrap update in user-management and auth-backends plugin

api-authorizations/src/main/scala/com/normation/plugins/apiauthorizations/UserInformationExtension.scala
https://issues.rudder.io/issues/24585
=> Fixes #24585: API authorization menu has two different icons to open it

change-validation/src/main/scala/com/normation/plugins/changevalidation/UnsupervisedTargetsReposiory.scala
https://issues.rudder.io/issues/24714
createDirectories create also parents contrary to createDirectory
=> Fixes #24714: /var/rudder/plugin-resources/change-validation is not created anymore on plugin startup

node-external-reports/src/main/scala/com/normation/plugins/nodeexternalreports/extension/CreateNodeDetailsExtension.scala
https://issues.rudder.io/issues/24630
=> Fixes #24630: External reports tab is not aligned in nodes page and content is always displayed

change-validation/src/main/elm/sources/SupervisedTargets.elm, change-validation/src/main/style/change-validation.css
https://issues.rudder.io/issues/24685
The "Panel" concept no longer exist in bootstrap 5, now it has been replaced with [Card](https://getbootstrap.com/docs/5.0/components/card/).
Also, elements are not collapsed by default so we need to add a `show` class on all elements at initialization.  
There are still some flaws, the border-top/border-bottom combinations are messy and we need to rethink it later, but for now we have something which looks okay :
=> Fixes #24685: Change validation group settings has broken UI

change-validation/src/main/scala/com/normation/plugins/changevalidation/WorkflowService.scala, change-validation/src/main/scala/com/normation/plugins/changevalidation/api/ChangeRequestApi.scala, change-validation/src/main/scala/com/normation/plugins/changevalidation/snippet/ChangeRequestChangesForm.scala, change-validation/src/main/scala/com/normation/plugins/changevalidation/snippet/ChangeRequestDetails.scala, change-validation/src/test/scala/com/normation/plugins/changevalidation/MockServices.scala, scale-out-relay/src/test/scala/com/normation/plugins/scaleoutrelay/MockServices.scala
https://issues.rudder.io/issues/24727
Fix compilation of the change-validation and scale-out-relay plugin since changes in https://github.com/Normation/rudder/pull/5608
=> Fixes #24727: Groups node ids list in API should be filtered by tenant in plugins

api-authorizations/pom-template.xml, auth-backends/pom-template.xml, change-validation/pom-template.xml, openscap/pom-template.xml
https://issues.rudder.io/issues/24771
Minor bumps for some plugins : 
* `auth-backends` : :man_dancing: jackson-databind 
* `change-validation` : :incoming_envelope: new version uses the jakarta mail 2 API now 
* `openscap` : :wastebasket: neko-html-unit can be deleted as stated in the comment
=> Fixes #24771: Update scala plugin dependencies

api-authorizations/pom-template.xml
https://issues.rudder.io/issues/24849
It was updated from 2.5.0 but the [previous artifact](https://mvnrepository.com/artifact/javax.servlet/servlet-api) has been moved since version 3
=> Fixes #24849: Fix servlet api dependency in api-authorizations

plugins-common-private/pom-template.xml, plugins-common-private/src/main/scala/com/normation/plugins/ParsePluginLicense.scala
https://issues.rudder.io/issues/24825
=> Fixes #24825: User version 2.2.1 of license lib

datasources/src/main/scala/com/normation/plugins/datasources/UpdateHttpDataset.scala
https://issues.rudder.io/issues/24996
So, there was two problems: 
- 1/ `try` in `attempt` leads to stalling tests
We had that: 
```
IOResult.attemptZIO(try {
json.read[JSONAware](path).succeed
} catch {
case _: ClassCastException =>
try { ...
```
And in case of exception, it was not doing what was expected but failing with the exception. It might be due to a change in the way `ZIO.attempt` works (since we switched to 2.x around here), but how the hell didn't we caught it before ? Or is it a more recent change in 2.X branch ? (but then, the last upgrade is in 08/2023 on 8.0 branch).
* 2/ Second problem: we had a `.toString` in the fallback case, so all values, even when they were map (ie json objects), were changed into string, so quote espacted, then parsed back AS STRING. Which …
=> Fixes #24996: UpdateHttpDatasetTest datasource test get blocked forever

api-authorizations/src/test/scala/com/normation/plugins/apiauthorizations/api/UserApiTest.scala, auth-backends/src/test/scala/com/normation/plugins/authbackends/api/AuthBackendsApiTest.scala, branding/src/test/scala/com/normation/plugins/branding/api/BrandingApiTest.scala, change-validation/src/main/scala/com/normation/plugins/changevalidation/ChangeRequestJson.scala, change-validation/src/main/scala/com/normation/plugins/changevalidation/WorkflowService.scala, change-validation/src/test/resources/changevalidation_api/api_changerequest.yml, change-validation/src/test/scala/com/normation/plugins/changevalidation/ValidatedUserJdbcRepositoryTest.scala, change-validation/src/test/scala/com/normation/plugins/changevalidation/api/ChangeRequestApiTest.scala, change-validation/src/test/scala/com/normation/plugins/changevalidation/api/SupervisedTargetsApiTest.scala, change-validation/src/test/scala/com/normation/plugins/changevalidation/api/ValidatedUserApiTest.scala, datasources/src/main/scala/bootstrap/rudder/plugin/DataSourcesConf.scala, datasources/src/main/scala/com/normation/plugins/datasources/QueryService.scala, datasources/src/main/scala/com/normation/plugins/datasources/Repository.scala, datasources/src/main/scala/com/normation/plugins/datasources/Serialization.scala, datasources/src/main/scala/com/normation/plugins/datasources/UpdateHttpDataset.scala, datasources/src/test/scala/com/normation/plugins/datasources/UpdateHttpDatasetTest.scala, datasources/src/test/scala/com/normation/plugins/datasources/api/RestDataSourceFilesTest.scala, datasources/src/test/scala/com/normation/plugins/datasources/api/RestDataSourceTest.scala, openscap/src/main/scala/com/normation/plugins/openscappolicies/api/OpenScapApi.scala, openscap/src/main/scala/com/normation/plugins/openscappolicies/services/GetActiveTechniqueIds.scala, openscap/src/test/scala/com/normation/plugins/openscappolicies/api/OpenScapApiTest.scala, scale-out-relay/src/main/scala/com/normation/plugins/scaleoutrelay/DataTypes.scala, scale-out-relay/src/test/scala/com/normation/plugins/scaleoutrelay/api/ScaleOutRelayApiTest.scala
https://issues.rudder.io/issues/25015
Lots of changes going on here : 
- for all plugins, changing the use of `TraitTestApiFromYamlFiles` ; similar, purely mechanic changes appart in datasources because the test was mixing both that and standard specs2 tests, I splitted it in two files (`RestDataSourceTest.scala` for specs2 and `RestDataSourceFilesTest.scala` for rest YAML)
- some YAML test file have some changes in json property orders. This is due to the fact that the normalisation with the new `TraitTestApiFromYamlFiles` is not exactly the same than before
- some `.apply` are added to comply to more recent scala rules
- `ScaleOutRelay` is adapted to `policyTag`: it seems that it's limited to only removing parameters in  `getBundleVariables` 
- because of changes in node API and …
=> Fixes #25015: Plugins need to be ported, too

datasources/src/test/scala/com/normation/plugins/datasources/UpdateHttpDatasetTest.scala
https://issues.rudder.io/issues/25085
Tests are still unstable, I was not sure of how to reproduce test failures : once I did the change and it passed once, I double-checked the behavior by reverting to the old version but then the tests always passed :weary: 
Before that, I changed the `nThreads` value to 1, and the test passed (but other tests on parallelism failed).
And yet I didn't find any "shared" state within the failing tests on 404 error, so I assumed this is a "client" behavior, and therefore the client IO may not finish before specs2 checks the second branche of the `... and ...`
=> Fixes #25085: Datasources tests fail on 404

user-management/src/main/elm/sources/View.elm
https://issues.rudder.io/issues/25464
Just do not display the button when editing current user
=> Fixes #25464: A user should not be able to delete themselves in user management

change-validation/src/main/scala/com/normation/plugins/changevalidation/comet/WorkflowInformation.scala
https://issues.rudder.io/issues/25741
Adding the `pe-auto` class to make links clickable, and restoring the same UI as before : 
The CSS structure was adapted to be the same as in the api-authorization plugin because (S)CSS from Rudder apply to generic items in the menu i.e. a `li` with an `id` and another `ul` within that contains each item :
The resulting structure is :
=> Fixes #25741: Change requests bar is no longer clickable

branding/src/main/scala/com/normation/plugins/branding/snippet/LoginBranding.scala
https://issues.rudder.io/issues/25737
The branding plugin was brutally replacing the previous content from the auth-backends plugin with empty XML.
It just needed to add the bar if it wanted to do it, really...
=> Fixes #25737: Login form for OIDC can disappear depending on branding configuration

openscap/Makefile, openscap/src/main/scala/bootstrap/rudder/plugin/OpenscapPoliciesConf.scala, openscap/src/main/scala/com/normation/plugins/openscappolicies/api/OpenScapApi.scala, openscap/src/main/scala/com/normation/plugins/openscappolicies/extension/OpenScapNodeDetailsExtension.scala, openscap/src/main/scala/com/normation/plugins/openscappolicies/services/OpenScapReportReader.scala, openscap/src/test/resources/openscap_api/api_openscap.yml, openscap/src/test/scala/com/normation/plugins/openscappolicies/api/OpenScapApiTest.scala
https://issues.rudder.io/issues/26066
* openscap.properties has been deleted in https://github.com/Normation/rudder-plugins/pull/777, the make target should also be removed
* use the NodeFactRepository, that requires `qc: QueryContext`
=> Fixes #26066: OpenSCAP needs queryContext and has build issues from stale properties file

openscap/src/main/scala/com/normation/plugins/openscappolicies/extension/OpenScapNodeDetailsExtension.scala
https://issues.rudder.io/issues/26065
We have to read the report file (as the API does) in the snippet, as pass the information down, to create buttons with a download action (similar to https://github.com/Normation/rudder/pull/5941).
The iframe can be used to render the original report by putting the sanitized content as string in [the srcdoc attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#srcdoc)
Result :
=> Fixes #26065: OpenSCAP report needs to be rendered without iframe with sanitized html

api-authorizations/src/main/elm/sources/UserApiToken.elm, api-authorizations/src/main/scala/bootstrap/rudder/plugin/ApiAuthorizationsConf.scala, api-authorizations/src/main/scala/com/normation/plugins/apiauthorizations/UserInformationExtension.scala, api-authorizations/src/main/scala/com/normation/plugins/apiauthorizations/UserTokenApiDefinition.scala, api-authorizations/src/test/scala/com/normation/plugins/apiauthorizations/api/UserApiTest.scala, user-management/src/main/scala/com/normation/plugins/usermanagement/DataTypes.scala, user-management/src/test/resources/usermanagement_api/api_usermanagement.yml
https://issues.rudder.io/issues/25999
UI for the feature switch in https://github.com/Normation/rudder/pull/6050 : essentially we don't display the user API token menu in the api-authorizations plugin snippet.
We still have an API endpoint to pass the configuration value, also there is some refactoring and formatting applied to the Elm code which knows about the status by calling the endpoint.
In the related PR, the user management roles and default providers are also changed, so there is some changes in the user-management plugin
=> Fixes #25999: Disabling user rest API token feature from api-authorizations plugin UI 

auth-backends/README.adoc
https://issues.rudder.io/issues/26063
Add a procedure to help people debug LDAP authentication.
=> Fixes #26063: When we use LDAP authentication backend, the error is confusing if the user doesn't exist in Rudder

datasources/src/test/scala/com/normation/plugins/datasources/api/RestDataSourceFilesTest.scala
https://issues.rudder.io/issues/26182
It is weird that we did not get an upmerge conflict from https://github.com/Normation/rudder-plugins/pull/784/files#diff-989df757ea97a81756f5beb30e2373c1467346fa13c2847917f2db0e54a284dcL68
=> Fixes #26182: Datasources tests fail in 8.2 since restextractorservice deletion

plugins-common/pom-template.xml
https://issues.rudder.io/issues/26195
The webapp was not able to load the plugin. See https://stackoverflow.com/a/64263739, some dependencies in 8.3 come with signatures, we just want to ignore them in all plugins
=> Fixes #26195: Maven shade plugin update and ignore signatures

plugins-common/pom-template.xml
https://issues.rudder.io/issues/26199
Following  https://github.com/Normation/rudder-plugins/pull/786 : 
in fact `janino` has been the only dependency with a signed jar that was added in 8.3, and not provided to plugins, so it was causing the error.
=> Fixes #26199: Janino dependency was not provided to plugins causing plugin load issue

datasources/src/test/scala/com/normation/plugins/datasources/UpdateHttpDatasetTest.scala
https://issues.rudder.io/issues/26309
Just skipping them as are they are now rarely modified, at some point we will want to rewrite the whole testing framework, or change the setup to ignore some tests depending on the environment (like postgresql running only on CI)
=> Fixes #26309: Datasources HTTP tests are failing in 8.2

auth-backends/src/main/scala/com/normation/plugins/authbackends/snippet/Oauth2LoginBanner.scala, branding/src/main/scala/com/normation/plugins/branding/snippet/LoginBranding.scala, branding/src/main/scala/com/normation/rudder/rest/BrandingApiSchema.scala, change-validation/src/main/scala/com/normation/plugins/changevalidation/api/SupervisedTargetsApi.scala, change-validation/src/main/scala/com/normation/plugins/changevalidation/api/ValidatedUserApi.scala, change-validation/src/test/scala/com/normation/plugins/changevalidation/ValidatedUserJdbcRepositoryTest.scala, datasources/src/main/scala/com/normation/plugins/datasources/api/DataSourceApi.scala, scale-out-relay/src/main/scala/com/normation/plugins/scaleoutrelay/api/ScaleOutRelayApi.scala
https://issues.rudder.io/issues/26397
Impact of https://github.com/Normation/rudder/pull/5669 (plus some missing renaming of `RudderPluginVersion`) : we need to explicitely declare `Administration.Write` now.
=> Fixes #26397: Impact of 24872 (API rights) on public plugins

api-authorizations/src/main/scala/com/normation/plugins/apiauthorizations/UserTokenApiDefinition.scala, api-authorizations/src/test/scala/com/normation/plugins/apiauthorizations/MockServices.scala, api-authorizations/src/test/scala/com/normation/plugins/apiauthorizations/api/UserApiTest.scala, auth-backends/src/main/scala/bootstrap/rudder/plugin/AuthBackendsConf.scala, auth-backends/src/main/scala/com/normation/plugins/authbackends/snippet/Oauth2LoginBanner.scala, branding/src/main/scala/bootstrap/rudder/plugin/BrandingPluginConf.scala, branding/src/main/scala/com/normation/plugins/branding/snippet/LoginBranding.scala
https://issues.rudder.io/issues/26457
- remove unused call to `PluginVersion` (changed to `RudderPluginVersion`)
- impact of https://github.com/Normation/rudder/pull/6173 and related PR weren't fully repercuted
=> Fixes #26457: Impact of #26335 to ApiAuthorization - again

change-validation/src/main/scala/com/normation/plugins/changevalidation/snippet/ChangeRequestDetails.scala, node-external-reports/src/main/scala/com/normation/plugins/nodeexternalreports/extension/CreateNodeDetailsExtension.scala, openscap/src/main/scala/com/normation/plugins/openscappolicies/extension/OpenScapNodeDetailsExtension.scala
https://issues.rudder.io/issues/26608
See https://github.com/Normation/rudder/pull/6280 for context
=> Fixes #26608: CurrentUser.queryContext is null when used in a ZIO for (public plugins)

api-authorizations/src/main/scala/com/normation/plugins/apiauthorizations/UserTokenApiDefinition.scala
https://issues.rudder.io/issues/26594
See: https://github.com/Normation/rudder/pull/6260
Json object for ACL now is `{"path", ["actions"]}` in place of `{"path", "verb"}
=> Fixes #26594: Impact of #26538 on api-authorization

change-validation/src/test/scala/com/normation/plugins/changevalidation/UnsupervisedTargetsRepositoryTest.scala
https://issues.rudder.io/issues/26756
When `skipped` is put at the end, some assertions may still fail and throw before the `Skipped` exception is thrown
=> Fixes #26756: Skipped tests are not skipped

change-validation/src/main/elm/elm.json, change-validation/src/main/elm/sources/ErrorMessages.elm, change-validation/src/main/elm/sources/Init.elm, change-validation/src/main/elm/sources/Notifications.elm, change-validation/src/main/elm/sources/SupervisedTargets.elm, change-validation/src/main/elm/sources/WorkflowInformation.elm, change-validation/src/main/elm/sources/WorkflowInformationTest.elm, change-validation/src/main/elm/sources/WorkflowUsers.elm, change-validation/src/main/scala/com/normation/plugins/changevalidation/comet/WorkflowInformation.scala
https://issues.rudder.io/issues/26788
This is part of the plan to remove the dependency to the lift library.
- The `WorkflowInformation` app (the dropdown menu in the navigation bar which displays the number of pending change requests) was mostly migrated to Elm   (see `WorkflowInformation.elm`)
- The `WorkflowInformation.scala` comet actor was not removed since it allows for rerendering the app without refreshing the entire page. The check of the user's authorization type(s) and the check of the value of the `enable_change_request` setting are handled in this comet actor.
- The actor has a mutable state, which allows for the Elm app to be loaded if and only if the app needs to be displayed i.e. if change requests are enabled, *and* if the current user has either or both of the needed …
=> Fixes #26788: Rewrite WorkflowInformation navigation bar in Elm

Jenkinsfile-release
https://issues.rudder.io/issues/26890
=> Fixes #26890: Make node-external-reports not licensed in release build

change-validation/src/test/resources/changevalidation_api/api_changerequest.yml
https://issues.rudder.io/issues/26949
API error detail no longer includes the Rudder error type `Unexpected` / `Inconsistency` since https://github.com/Normation/rudder/pull/6388
=> Fixes #26949: Impact of 26936 on plugins

change-validation/src/main/elm/sources/ApiCalls.elm, change-validation/src/main/elm/sources/DataTypes.elm, change-validation/src/main/elm/sources/Init.elm, change-validation/src/main/elm/sources/JsonDecoders.elm, change-validation/src/main/elm/sources/JsonEncoders.elm, change-validation/src/main/elm/sources/SupervisedTargets.elm, change-validation/src/main/elm/sources/View.elm, change-validation/src/main/elm/sources/WorkflowUsers.elm, change-validation/src/main/resources/template/ChangeValidationManagement.html
https://issues.rudder.io/issues/26946
This is part of the plan to "merge" both existing Elm apps in the change-validation settings page, as well as migrate the `ChangeValidationSettings` snippet to Elm, so that the change-validation settings page contains a single Elm app that renders the whole page.
The first step is to merge the 'Validate all' checkbox and save button with the `WorkflowUsers` Elm app, as the former is currently being rendered by the `ChangeValidationSettings` snippet.
Commit history :
1. Changed the html structure of the settings page so that the `WorkflowUsers` app can contain the 'Validate all' checkbox and save button
2. Applied `elm-format` to all the elm source files that will be modified, no implementation changes (this should probably have been done first, oops) …
=> Fixes #26946: Add the 'Validate All' check box to the WorkflowUsers Elm app

change-validation/src/main/elm/sources/WorkflowInformation.elm, change-validation/src/main/scala/com/normation/plugins/changevalidation/TopBarExtension.scala, change-validation/src/main/scala/com/normation/plugins/changevalidation/comet/WorkflowInformation.scala
https://issues.rudder.io/issues/27029
There is some refactoring that justify that we need to add a loader :
* we need to change the initialization of the Elm app to be in an AJAX, instead of in a `<script/>` using the actor's `partialUpdate` (as in https://github.com/Normation/rudder/pull/5966), because script tags are annoying within actors and when we add CSP headers (see https://github.com/Normation/rudder-plugins/pull/837)
* the AJAX is a bit slower which makes it noticeable, so we need to add placeholders for display, [using bootstrap classes](https://getbootstrap.com/docs/5.1/components/placeholders/)
* the access checks, when moved to the snippet of the plugin extension `TopBarExtension`, simplifies the code in the actor a lot
=> Fixes #27029: Change request count Elm WorkflowInformation app needs a loader  

datasources/src/main/elm/sources/View.elm, datasources/src/main/resources/template/dataSourceManagement.html
https://issues.rudder.io/issues/27000
* Action buttons were missing the `hasWriteRights` check
* `administration_write` permission allows to edit datasources, not `rule_write`
=> Fixes #27000: Datasources edition has action buttons even for read-only user

change-validation/src/main/resources/template/ChangeValidationManagement.html
https://issues.rudder.io/issues/27064
The `Configure change request triggers` section of the` change-validation` settings page has two sections that contradict each other. This PR is a backport of the fix in the 9.0 version, see https://github.com/Normation/rudder-plugins/pull/832/commits/31ed45f4680680ca119c7db5dfe5f3bcf7890b13
=> Fixes #27064: Change validation settings page has contradictory documentation

Jenkinsfile
https://issues.rudder.io/issues/27091
`deploy` implies `package` and `install`, but not `clean`
=> Fixes #27091: Missing clean in build command

change-validation/src/main/elm/sources/ChangeRequestDetails.elm, change-validation/src/main/elm/sources/ChangeRequestEditForm.elm
https://issues.rudder.io/issues/27289
Previously, the banner and changes table of a given change request were not updated directly after the user had used the edit form in order to modify the title or description of the change request.
The banner and changes table are now updated without needing to refresh the page.
Note : After editing the title or description of a change request, no new log will appear in the logs table - the issue is on the API side (modifying a change request's info by using the public API does not create a new log). Hence, the update of the changes table is not visible in this case.
=> Fixes #27289: Change request page is not updated directly after using the form to edit the title/description 
