- node-external-reports/pom.xml
https://www.rudder-project.org/redmine/issues/11661
> Fixes #11661: Bad repo declaration in node-external-reports pom.xml

- common-scala-plugin.mk
- datasources/pom.xml
- datasources/src/main/scala-templates/default/com/normation/plugins/datasources/EnablePluginImpl.scala
- datasources/src/main/scala-templates/limited/com/normation/plugins/datasources/EnablePluginImpl.scala
https://www.rudder-project.org/redmine/issues/11666
> Fixes #11666: Update datasource to license framework 1.1.0

- README.md
https://www.rudder-project.org/redmine/issues/11700
> Fixes #11700: Missing build documentation for plugins

- node-external-reports/build.conf
- node-external-reports/pom.xml
- node-external-reports/src/main/scala/com/normation/plugins/nodeexternalreport/NodeExternalReportPluginDef.scala
https://www.rudder-project.org/redmine/issues/11709
> Fixes #11709: Broken build for node-external-info / 4.2-x

- node-external-reports/Makefile
- node-external-reports/README.asciidoc
- node-external-reports/pom.xml
https://www.rudder-project.org/redmine/issues/11708
> Fixes #11708: Add a build option to embed a preconfigured config file in node-external-info

- node-external-reports/build.conf
https://www.rudder-project.org/redmine/issues/11710
> Fixes #11710: Release version 4.x-1.3 of node-external-reports

- README.md
https://www.rudder-project.org/redmine/issues/11711
> Fixes #11711: Make plugins tool requirement more explicit

- Makefile
https://www.rudder-project.org/redmine/issues/11951
> Fixes #11951: Add a makefile to the repositoryto build plugins from the root

- makefiles/common.mk
https://www.rudder-project.org/redmine/issues/11953
> Fixes #11953: Plugin datasource cannot build

- datasources/Makefile
- helloworld/Makefile
- makefiles/common-scala-plugin.mk
- makefiles/common.mk
- node-external-reports/Makefile
https://www.rudder-project.org/redmine/issues/11954
> Fixes #11954: Datasource misses the sql script

- datasources/Makefile
- helloworld/Makefile
- node-external-reports/Makefile
https://www.rudder-project.org/redmine/issues/11960
> Fixes #11960: Datasource misses the sql script

- datasources/build.conf
- helloworld/build.conf
- node-external-reports/build.conf
https://www.rudder-project.org/redmine/issues/12075
> Fixes #12075: Change plugins version to 4.3

- .gitignore
- datasources/LICENSE
- datasources/LICENSE_EXCEPTION
https://www.rudder-project.org/redmine/issues/12170
> Fixes #12170: datasources plugin is missing LICENSE file

- api-authorizations/.gitignore
- api-authorizations/LICENSE
- api-authorizations/LICENSE_EXCEPTION
- api-authorizations/Makefile
- api-authorizations/README.asciidoc
- api-authorizations/build.conf
- api-authorizations/packaging/metadata
- api-authorizations/packaging/postinst
- api-authorizations/pom.xml
- api-authorizations/src/main/assembly/plugin-with-own-dependencies.xml
- api-authorizations/src/main/scala-templates/limited/com/normation/plugins/apiauthorizations/EnablePluginImpl.scala
- api-authorizations/src/main/scala/bootstrap/rudder/plugin/ApiAuthorizationsConf.scala
- api-authorizations/src/main/scala/bootstrap/rudder/plugin/EnablePlugin.scala
- api-authorizations/src/main/scala/com/normation/plugins/apiauthorizations/ApiAuhorizationsPluginDef.scala
- api-authorizations/src/main/scala/com/normation/plugins/apiauthorizations/EnablePluginImpl.scala
- api-authorizations/src/test/resources/logback-test.xml
https://www.rudder-project.org/redmine/issues/12112
> Fixes #12112: Plugin for API authorization ACL

- node-external-reports/pom.xml
https://www.rudder-project.org/redmine/issues/12201
> Fixes #12201: Missing part of POM for node external report

- Makefile
- blank-template/pom.xml
- datasources/pom.xml
- how-to-run-mvn-here.txt
- main-build.conf
- makefiles/common-scala-plugin.mk
- makefiles/common.mk
- makefiles/global-vars.mk
- makefiles/make-plugins-common.mk
- node-external-reports/pom.xml
- plugins-common-private/Makefile
- plugins-common-private/pom.xml
- plugins-common/Makefile
- plugins-common/pom.xml
- pom.xml
https://www.rudder-project.org/redmine/issues/12251
> Fixes #12251: lib version is not parametrized in submodules

- .gitignore
- Makefile
- blank-template/build.conf
- blank-template/pom-template.xml
- datasources/pom-template.xml
- helloworld/pom-template.xml
- makefiles/common.mk
- makefiles/global-vars.mk
- makefiles/make-plugins-common.mk
- node-external-reports/pom-template.xml
- plugins-common-private/pom-template.xml
- plugins-common/pom-template.xml
- pom-template.xml
https://www.rudder-project.org/redmine/issues/12257
> Fixes #12257: maven furious. maven requires more life sacrifices to be happy

- blank-template/build.conf
- datasources/build.conf
- makefiles/global-vars.mk
- plugins-common/src/main/scala/com/normation/plugins/PluginData.scala
- pom-template.xml
https://www.rudder-project.org/redmine/issues/12275
> Fixes #12275: "\" in build.conf description leads to unreacoverable exception during boot

- datasources/src/main/resources/toserve/datasources/rudder-datasources.js
- datasources/src/main/scala/com/normation/plugins/datasources/DataSourcesPluginDef.scala
- pom-template.xml
https://www.rudder-project.org/redmine/issues/12416
> Fixes #12416: Bad internal API URL in datasources for Rudder 4.3

- pom-template.xml
https://www.rudder-project.org/redmine/issues/12417
> Fixes #12417: build.conf properties are not filtered (replaced) in plugin

- blank-template/pom-template.xml
- datasources/pom-template.xml
- helloworld/pom-template.xml
- pom-template.xml
https://www.rudder-project.org/redmine/issues/12412
> Fixes #12412: Exception and stacktrace with datasources plugin on 4.3

- branding/src/main/elm/build-app.sh
https://www.rudder-project.org/redmine/issues/12738
> Fixes #12738: Use elm-install to install elm dependencies instead of just using elm-make

- branding/pom-template.xml
- branding/src/main/elm/brandingManagement.html
https://www.rudder-project.org/redmine/issues/12800
> Fixes #12800: Correct branding html so we can use it 

- centreon/bin/centreon-plugin.py
- centreon/share/python/centreonapi/webservice/configuration/host.py
- centreon/share/python/centreonapi/webservice/configuration/service.py
- qa-test
https://www.rudder-project.org/redmine/issues/12656
> Fixes #12656:  Use pylint to verify python code in rudder-plugins

- centreon/bin/centreon-plugin.py
https://www.rudder-project.org/redmine/issues/12809
> Fixes #12809: Centreon plugin uses an undefined variable

- pom-template.xml
https://www.rudder-project.org/redmine/issues/12834
> Fixes #12834: We need to explicit version of scala-library in plugin-parent else one is pick at random from transitive dependencies

- branding/.gitignore
- branding/src/main/elm/brandingManagement.html
- branding/src/main/elm/sources/ApiCall.elm
- branding/src/main/elm/sources/Branding.elm
- branding/src/main/elm/sources/DataTypes.elm
- branding/src/main/elm/sources/JsonDecoder.elm
- branding/src/main/elm/sources/JsonEncoder.elm
- branding/src/main/elm/sources/View.elm
- branding/src/main/scala/bootstrap/rudder/plugin/BrandingConf.scala
- branding/src/main/scala/com/normation/plugins/branding/BrandingConf.scala
- branding/src/main/scala/com/normation/plugins/branding/BrandingConfService.scala
- branding/src/main/scala/com/normation/plugins/branding/api/BrandingApi.scala
- branding/src/main/scala/com/normation/plugins/branding/snippet/CommonBranding.scala
- branding/src/main/scala/com/normation/plugins/branding/snippet/LoginBranding.scala
https://www.rudder-project.org/redmine/issues/6661
> Fixes #6661: Customize Login frontend and Rudder color them to differentiate environments

- README.md
- pom-template.xml
https://www.rudder-project.org/redmine/issues/12848
> Fixes #12848: Duplicate definition of scala-version in parent ticket

- datasources/build.conf
- datasources/src/main/scala/com/normation/plugins/datasources/DataSourcesPluginDef.scala
- datasources/src/test/scala/com/normation/plugins/datasources/UpdateHttpDatasetTest.scala
- main-build.conf
- node-external-reports/build.conf
- node-external-reports/src/main/resources/nodeExternalReports.html
- node-external-reports/src/main/scala/com/normation/plugins/nodeexternalreports/NodeExternalReportPluginDef.scala
- node-external-reports/src/main/scala/com/normation/plugins/nodeexternalreports/service/NodeExternalReportApi.scala
- pom-template.xml
https://www.rudder-project.org/redmine/issues/12860
> Fixes #12860: Plugins need a release before 4.3.3 API change

- branding/packaging/postinst
https://www.rudder-project.org/redmine/issues/12850
> Fixes #12850: Correct packaging for branding plugin

- branding/src/main/elm/brandingManagement.html
https://www.rudder-project.org/redmine/issues/12890
> Fixes #12890: Add missing class to make Branding page UI pretty

- plugins-common/src/main/scala/com/normation/plugins/PluginData.scala
https://www.rudder-project.org/redmine/issues/12894
> Fixes #12894: plugin-common-compilation-error when building on 4.3.0

- datasources/packaging/postinst
https://www.rudder-project.org/redmine/issues/12792
> Fixes #12792: Datasources postinst SQL does not use Rudder connection parameters

- api-authorizations/src/main/elm/sources/user-api-token.elm
- api-authorizations/src/main/elm/toserve/media.css
- api-authorizations/src/main/scala/com/normation/plugins/apiauthorizations/UserInformationExtension.scala
https://www.rudder-project.org/redmine/issues/12909
> Fixes #12909: UI enhancement for API ACL dropdown form

- datasources/src/main/scala/com/normation/plugins/datasources/DataSourcesPluginDef.scala
https://www.rudder-project.org/redmine/issues/12918
> Fixes #12918: Datasource plugin does not declare its APIs

- branding/src/main/elm/sources/View.elm
- branding/src/main/scala/com/normation/plugins/branding/snippet/LoginBranding.scala
https://www.rudder-project.org/redmine/issues/12971
> Fixes #12971: A part of the login form disappears if the custom bar is not activated

- branding/src/main/elm/toserve/media.css
https://www.rudder-project.org/redmine/issues/12948
> Fixes #12948: Color picker is hiddin by header bar

- src/main/g8/src/main/scala/com/normation/plugins/$plugin_pkg$/$plugin_class$PluginDef.scala
https://www.rudder-project.org/redmine/issues/13025
> Fixes #13025: Remaning "datasources" in g8 template

- Makefile
- datasources/src/main/scala/bootstrap/rudder/plugin/DataSourcesConf.scala
- datasources/src/test/scala/com/normation/plugins/datasources/UpdateHttpDatasetTest.scala
- main-build.conf
- scale-out-relay/LICENSE
- scale-out-relay/LICENSE_EXCEPTION
- scale-out-relay/Makefile
- scale-out-relay/README.asciidoc
- scale-out-relay/build.conf
- scale-out-relay/packaging/metadata
- scale-out-relay/packaging/postinst
- scale-out-relay/pom-template.xml
- scale-out-relay/src/main/resources/template/ScaleOutRelayManagement.html
- scale-out-relay/src/main/resources/toserve/scaleoutrelay/scale-out-relay.css
- scale-out-relay/src/main/resources/toserve/scaleoutrelay/scale-out-relay.js
- scale-out-relay/src/main/scala-templates/default/com/normation/plugins/scaleoutrelay/EnablePluginImpl.scala
- scale-out-relay/src/main/scala-templates/limited/com/normation/plugins/scaleoutrelay/EnablePluginImpl.scala
- scale-out-relay/src/main/scala/bootstrap/rudder/plugin/ScaleOutRelayConf.scala
- scale-out-relay/src/main/scala/com/normation/plugins/scaleoutrelay/DataTypes.scala
- scale-out-relay/src/main/scala/com/normation/plugins/scaleoutrelay/ScaleOutRelayPluginDef.scala
- scale-out-relay/src/test/resources/logback-test.xml
https://www.rudder-project.org/redmine/issues/12888
> Fixes #12888: Create a plugin for relay servers

- Makefile
- api-authorizations/src/main/scala/bootstrap/rudder/plugin/ApiAuthorizationsConf.scala
- api-authorizations/src/main/scala/com/normation/plugins/apiauthorizations/ApiAccountsExtension.scala
- api-authorizations/src/main/scala/com/normation/plugins/apiauthorizations/UserInformationExtension.scala
- branding/src/main/scala/bootstrap/rudder/plugin/BrandingConf.scala
- branding/src/main/scala/com/normation/plugins/branding/snippet/CommonBranding.scala
- branding/src/main/scala/com/normation/plugins/branding/snippet/LoginBranding.scala
- datasources/src/main/scala/bootstrap/rudder/plugin/DataSourcesConf.scala
- helloworld/src/main/scala/bootstrap/rudder/plugin/HelloWorldConf.scala
- helloworld/src/main/scala/com/normation/plugins/helloworld/extension/CreateRuleExtension.scala
- helloworld/src/main/scala/com/normation/plugins/helloworld/snippet/HelloWorld.scala
- main-build.conf
- node-external-reports/src/main/scala/bootstrap/rudder/plugin/NodeExternalReportsConf.scala
- node-external-reports/src/main/scala/com/normation/plugins/nodeexternalreports/extension/CreateNodeDetailsExtension.scala
- node-external-reports/src/main/scala/com/normation/plugins/nodeexternalreports/snippet/PluginInfo.scala
- src/main/g8/src/main/scala/bootstrap/rudder/plugin/$plugin_class$Conf.scala
https://www.rudder-project.org/redmine/issues/13037
> Fixes #13037: Remove spring in plugins

- src/main/g8/src/main/scala/com/normation/plugins/$plugin_pkg$/$plugin_class$PluginDef.scala
https://www.rudder-project.org/redmine/issues/13045
> Fixes #13045: Oups, I totally broke g8 when removing 'datasources'

- auth-backends/LICENSE
- auth-backends/LICENSE_EXCEPTION
- auth-backends/Makefile
- auth-backends/README.asciidoc
- auth-backends/build.conf
- auth-backends/packaging/metadata
- auth-backends/packaging/postinst
- auth-backends/pom-template.xml
- auth-backends/src/main/resources/applicationContext-security-auth-ldap.xml
- auth-backends/src/main/resources/applicationContext-security-auth-radius.xml
- auth-backends/src/main/resources/auth-backends.properties
- auth-backends/src/main/resources/template/AuthBackendsManagement.html
- auth-backends/src/main/resources/toserve/authbackends/auth-backends.css
- auth-backends/src/main/resources/toserve/authbackends/auth-backends.js
- auth-backends/src/main/scala-templates/default/com/normation/plugins/authbackends/EnablePluginImpl.scala
- auth-backends/src/main/scala-templates/limited/com/normation/plugins/authbackends/EnablePluginImpl.scala
- auth-backends/src/main/scala/bootstrap/rudder/plugin/AuthBackendsConf.scala
- auth-backends/src/main/scala/com/normation/plugins/authbackends/AuthBackendsPluginDef.scala
- auth-backends/src/main/scala/com/normation/plugins/authbackends/DataTypes.scala
- auth-backends/src/main/scala/com/normation/plugins/authbackends/RadiusAuthentication.scala
- auth-backends/src/test/resources/logback-test.xml
https://www.rudder-project.org/redmine/issues/13024
> Fixes #13024: Create alternative backend authentication plugin

- changes-validation/src/main/scala/bootstrap/rudder/plugin/ChangesValidationConf.scala
- changes-validation/src/main/scala/com/normation/plugins/changesvalidation/ChangesValidationPluginDef.scala
- changes-validation/src/main/scala/com/normation/plugins/changesvalidation/TopBarExtension.scala
https://www.rudder-project.org/redmine/issues/13027
> Fixes #13027: Add in change validation plugin the comet actor register

- api-authorizations/src/main/scala/bootstrap/rudder/plugin/ApiAuthorizationsConf.scala
https://www.rudder-project.org/redmine/issues/13079
> Fixes #13079: Incorrect verification of plugin status for API authz

- api-authorizations/src/main/scala/com/normation/plugins/apiauthorizations/ApiAccountsExtension.scala
- api-authorizations/src/main/scala/com/normation/plugins/apiauthorizations/UserInformationExtension.scala
- auth-backends/build.conf
- branding/src/main/scala/bootstrap/rudder/plugin/BrandingConf.scala
- branding/src/main/scala/com/normation/plugins/branding/snippet/CommonBranding.scala
- branding/src/main/scala/com/normation/plugins/branding/snippet/LoginBranding.scala
- changes-validation/build.conf
- changes-validation/src/main/scala/bootstrap/rudder/plugin/ChangesValidationConf.scala
- changes-validation/src/main/scala/com/normation/plugins/changesvalidation/TopBarExtension.scala
- main-build.conf
- node-external-reports/src/main/scala/com/normation/plugins/nodeexternalreports/extension/CreateNodeDetailsExtension.scala
- scale-out-relay/build.conf
- scale-out-relay/src/main/scala/bootstrap/rudder/plugin/ScaleOutRelayConf.scala
- scale-out-relay/src/main/scala/com/normation/plugins/scaleoutrelay/DataTypes.scala
- scale-out-relay/src/main/scala/com/normation/plugins/scaleoutrelay/ScaleOutRelayPluginDef.scala
https://www.rudder-project.org/redmine/issues/13087
> Fixes #13087: Correction on plugins for parent status check 

- glpi/LICENSE
- glpi/Makefile
- glpi/README.md
- glpi/bin/glpi-plugin
- glpi/build.conf
- glpi/etc/glpi.conf
- glpi/etc/hooks.d/node-post-acceptance/glpi-inventory.sh
- glpi/packaging/metadata
- glpi/packaging/postinst
https://www.rudder-project.org/redmine/issues/13098
> Fixes #13098: GLPI plugin

- vault/share/plugins/vault/20_cfe_basics/vault_lib.cf
https://www.rudder-project.org/redmine/issues/12978
> Fixes #12978: Add TLS cert/key auth to the Vault plugin

- centreon/packaging/postinst
https://www.rudder-project.org/redmine/issues/13142
> Fixes #13142: Cronify the execution of the centreon plugin

- vault/README.md
- vault/share/plugins/vault/sample_vault.json
https://www.rudder-project.org/redmine/issues/13150
> Fixes #13150: Add documentation to the Vault plugin

- .gitignore
- Makefile
- datasources/README.adoc
- node-external-reports/README.adoc
https://www.rudder-project.org/redmine/issues/13265
> Fixes #13265: Generate usable docs files from plugins

- auth-backends/src/main/scala/com/normation/plugins/authbackends/AuthBackendsPluginDef.scala
- branding/src/main/scala/com/normation/plugins/branding/BrandingPluginDef.scala
- changes-validation/src/main/scala/com/normation/plugins/changesvalidation/ChangesValidationPluginDef.scala
- datasources/src/main/scala/com/normation/plugins/datasources/DataSourcesPluginDef.scala
- helloworld/src/main/scala/com/normation/plugins/helloworld/HelloWorldPluginDef.scala
- main-build.conf
- node-external-reports/src/main/scala/com/normation/plugins/nodeexternalreports/NodeExternalReportPluginDef.scala
https://www.rudder-project.org/redmine/issues/13379
> Fixes #13379: Update menu registering for plugins

- blank-template/src/main/scala-templates/limited/com/normation/plugins/BLANK/EnablePluginImpl.scala
- datasources/src/main/scala-templates/limited/com/normation/plugins/datasources/EnablePluginImpl.scala
- main-build.conf
- makefiles/common-scala-plugin.mk
- node-external-reports/src/main/scala-templates/limited/com/normation/plugins/nodeexternalreports/EnablePluginImpl.scala
- plugins-common-private/build.conf
- plugins-common-private/pom-template.xml
- plugins-common-private/src/main/scala/com/normation/plugins/ParsePluginLicense.scala
https://www.rudder-project.org/redmine/issues/13283
> Fixes #13283: Update build so that licensed binaries don't embed key/license

- api-authorizations/src/main/scala-templates/limited/com/normation/plugins/apiauthorizations/EnablePluginImpl.scala
- branding/src/main/scala-templates/limited/com/normation/plugins/branding/EnablePluginImpl.scala
- datasources/src/main/scala-templates/limited/com/normation/plugins/datasources/EnablePluginImpl.scala
- node-external-reports/src/main/scala-templates/limited/com/normation/plugins/nodeexternalreports/EnablePluginImpl.scala
https://www.rudder-project.org/redmine/issues/13321
> Fixes #13321:  Update build so that licensed binaries don't embed key/license (branche 4.3)

- auth-backends/src/main/scala-templates/limited/com/normation/plugins/authbackends/EnablePluginImpl.scala
- changes-validation/src/main/scala-templates/limited/com/normation/plugins/changesvalidation/EnablePluginImpl.scala
- datasources/src/test/scala/com/normation/plugins/datasources/api/RestDataSourceTest.scala
- scale-out-relay/src/main/scala-templates/limited/com/normation/plugins/scaleoutrelay/EnablePluginImpl.scala
- src/main/g8/src/main/scala-templates/limited/com/normation/plugins/$plugin_pkg$/EnablePluginImpl.scala
https://www.rudder-project.org/redmine/issues/13322
> Fixes #13322:  Update build so that licensed binaries don't embed key/license (branche 5.0)

- main-build.conf
https://www.rudder-project.org/redmine/issues/13442
> Fixes #13442: Branding plugin doesn't build in branch 5.0

- auth-backends/pom-template.xml
- branding/src/main/scala/com/normation/plugins/branding/BrandingPluginDef.scala
- change-validation/README.adoc
- change-validation/pom-template.xml
- change-validation/src/main/elm/build-app.sh
- change-validation/src/main/elm/elm-package.json
- change-validation/src/main/elm/sources/supervised-targets.elm
- change-validation/src/main/resources/template/ChangeValidationManagement.html
- change-validation/src/main/resources/template/changeRequest.html
- change-validation/src/main/resources/template/changeRequests.html
- change-validation/src/main/resources/toserve/changevalidation/ComponentChangeRequest.html
- change-validation/src/main/resources/toserve/changevalidation/change-validation.css
- change-validation/src/main/resources/toserve/changevalidation/change-validation.js
- change-validation/src/main/resources/toserve/changevalidation/toasty.css
- change-validation/src/main/scala/bootstrap/rudder/plugin/ChangeValidationConf.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/ChangeValidationPluginDef.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/DataTypes.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/SupervisedTargetsReposiory.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/WorkflowService.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/api/SupervisedTargetsApi.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/comet/WorkflowInformation.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/snippet/ChangeRequestChangesForm.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/snippet/ChangeRequestDetails.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/snippet/ChangeRequestEditForm.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/snippet/ChangeRequestManagement.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/snippet/ChangeValidationSettings.scala
https://www.rudder-project.org/redmine/issues/12194
> Fixes #12194: Target groups for the Validation Workflow

- centreon/bin/centreon-plugin.py
https://www.rudder-project.org/redmine/issues/13574
> Fixes #13574: Applying hosttemplate from generic method fails

- helloworld/src/main/scala-templates/default/com/normation/plugins/helloworld/EnablePluginImpl.scala
- helloworld/src/main/scala-templates/limited/com/normation/plugins/helloworld/EnablePluginImpl.scala
- helloworld/src/main/scala/bootstrap/rudder/plugin/HelloWorldConf.scala
- helloworld/src/main/scala/com/normation/plugins/helloworld/HelloWorldPluginDef.scala
https://www.rudder-project.org/redmine/issues/13576
> Fixes #13576: Make helloworld plugin compile on 5.0 branch

- helloworld/pom-template.xml
https://www.rudder-project.org/redmine/issues/13578
> Fixes #13578: pom.xml template on helloworld was not modified

- centreon/bin/centreon-plugin.py
https://www.rudder-project.org/redmine/issues/13570
> Fixes #13570: Add a default hosttemplate when adding a centreon host

- centreon/bin/centreon-plugin.py
- centreon/packaging/postinst
https://www.rudder-project.org/redmine/issues/13579
> Fixes #13579: Run centreon-plugin.py commit when we detect a csv changes instead of each hour

- datasources/src/main/scala/com/normation/plugins/datasources/Repository.scala
https://www.rudder-project.org/redmine/issues/13588
> Fixes #13588: Correct attempt.transact -> transact.attempt in SQL request (see #13517)

- centreon/README.md
- centreon/bin/centreon-plugin
- centreon/etc/hooks.d/node-post-acceptance/centreon-post-acceptance.sh
- centreon/etc/hooks.d/node-pre-deletion/centreon-pre-deletion.sh
- centreon/packaging/postinst
- qa-test
https://www.rudder-project.org/redmine/issues/13580
> Fixes #13580: Use parameter that speak for themselves in centreon plugin

- vault/share/plugins/vault/30_generic_methods/variable_from_vault.cf
- vault/share/plugins/vault/sample_vault.json
https://www.rudder-project.org/redmine/issues/13590
> Fixes #13590: Vault input and output are not what we expect

- change-validation/src/main/scala/com/normation/plugins/changevalidation/ChangeValidationPluginDef.scala
https://www.rudder-project.org/redmine/issues/13628
> Fixes #13628: Bad authorization for Change Validations pages: validator can't validate

- change-validation/src/main/scala/bootstrap/rudder/plugin/ChangeValidationConf.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/ChangeRequestJdbcRepository.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/ChangeRequestRepository.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/ChangeValidationPluginDef.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/ValidationNeeded.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/WorkflowJdbcRepository.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/WorkflowService.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/api/ChangeRequestApi.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/comet/WorkflowInformation.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/snippet/ChangeRequestDetails.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/snippet/ChangeRequestManagement.scala
- main-build.conf
https://www.rudder-project.org/redmine/issues/13630
> Fixes #13630: Change request must not be saved when no validation is needed (plugin)

- auth-backends/src/main/scala/bootstrap/rudder/plugin/AuthBackendsConf.scala
- auth-backends/src/main/scala/com/normation/plugins/authbackends/AuthBackendsRepository.scala
- main-build.conf
https://www.rudder-project.org/redmine/issues/13709
> Fixes #13709: Adapt authentication backend for correct init order

- auth-backends/src/main/elm/sources/auth-backends.elm
- auth-backends/src/main/resources/template/AuthBackendsManagement.html
- auth-backends/src/main/resources/toserve/authbackends/auth-backends.css
https://www.rudder-project.org/redmine/issues/13696
> Fixes #13696: Improve Authentication backends plugin UI

- user-management/src/main/elm/sources/user-management.elm
- user-management/src/main/resources/template/UserManagement.html
- user-management/src/main/resources/toserve/usermanagement/toasty.css
- user-management/src/main/resources/toserve/usermanagement/user-management.css
https://www.rudder-project.org/redmine/issues/13711
> Fixes #13711: Improve User Management plugin UI

- datasources/src/test/scala/com/normation/plugins/datasources/api/RestDataSourceTest.scala
https://www.rudder-project.org/redmine/issues/13731
> Fixes #13731: A test is in error in datasources 4.3

- auth-backends/README.adoc
https://www.rudder-project.org/redmine/issues/13730
> Fixes #13730: Fix auth-backends doc

- change-validation/src/main/elm/sources/supervised-targets.elm
- change-validation/src/main/resources/template/ChangeValidationManagement.html
- change-validation/src/main/resources/toserve/changevalidation/change-validation.css
- change-validation/src/main/resources/toserve/changevalidation/toasty.css
https://www.rudder-project.org/redmine/issues/13729
> Fixes #13729: Improve Change Valdiation plugin UI

- centreon/bin/centreon-plugin
https://www.rudder-project.org/redmine/issues/13723
> Fixes #13723: Broken node deletion in centreon

- change-validation/src/main/scala/com/normation/plugins/changevalidation/ValidationNeeded.scala
https://issues.rudder.io/issues/13895
> Fixes #13895: Directive creation directly linked to a rule are ignored

- notify/packaging/metadata
https://issues.rudder.io/issues/13922
> Fixes #13922: Missing dependecy on python-configparser

- notify/share/python/notify.py
https://issues.rudder.io/issues/13925
> Fixes #13925: When no filters are set, the plugin does not behave like expected

- datasources/README.adoc
- datasources/build.conf
- datasources/src/main/scala/bootstrap/rudder/plugin/DataSourcesConf.scala
- datasources/src/main/scala/com/normation/plugins/datasources/QueryService.scala
- datasources/src/main/scala/com/normation/plugins/datasources/UpdateHttpDataset.scala
- datasources/src/test/scala/com/normation/plugins/datasources/UpdateHttpDatasetTest.scala
- datasources/src/test/scala/com/normation/plugins/datasources/api/RestDataSourceTest.scala
- main-build.conf
https://issues.rudder.io/issues/13933
> Fixes #13933: NoSuchMethodError with datasources 4.3-1.4 + Rudder 4.3.7

- zabbix/LICENSE
- zabbix/Makefile
- zabbix/README.md
- zabbix/bin/zabbix-plugin.py
- zabbix/build.conf
- zabbix/etc/hooks.d/node-post-acceptance/zabbix-post-acceptance.sh
- zabbix/etc/hooks.d/node-pre-deletion/zabbix-pre-deletion.sh
- zabbix/etc/zabbix.conf
- zabbix/packaging/metadata
- zabbix/packaging/postinst
https://www.rudder-project.org/redmine/issues/13107
> Fixes #13107: ZABBIX plugin

- qa-test
- zabbix/Makefile
- zabbix/bin/zabbix-plugin.py
- zabbix/etc/zabbix.conf
- zabbix/packaging/postinst
https://issues.rudder.io/issues/14177
> Fixes #14177: Zabbix packaging problems

- scale-out-relay/packaging/postinst
https://issues.rudder.io/issues/13662
> Fixes #13662: Installing scale-out-relay should trigger a policy generation

- main-build.conf
https://issues.rudder.io/issues/14298
> Fixes #14298: DSC plugin needs Rudder 5.0.4

- auth-backends/README.adoc
https://issues.rudder.io/issues/14329
> Fixes #14329: Add example of mixed ldap,file rudder-users.xml file

- centreon/bin/centreon-plugin
- centreon/packaging/postinst
- centreon/share/python/centreonapi/webservice/__init__.py
https://issues.rudder.io/issues/14364
> Fixes #14364: Add support to multiple centeon pollers

- centreon/bin/centreon-plugin
https://issues.rudder.io/issues/14365
> Fixes #14365: Add support to multiple centeon pollers

- auth-backends/src/main/elm/elm.json
- auth-backends/src/main/resources/template/AuthBackendsManagement.html
https://issues.rudder.io/issues/14604
> Fixes #14604: Missing dependency for auth-backends and html not valid

- change-validation/src/main/elm/sources/supervised-targets.elm
https://issues.rudder.io/issues/14630
> Fixes #14630: Change-validation is not compiling

- centreon/README.adoc
https://issues.rudder.io/issues/14587
> Fixes #14587: improve centreon documentation 

- auth-backends/src/main/scala/com/normation/plugins/authbackends/api/AuthBackendsApi.scala
- branding/src/main/scala/com/normation/plugins/branding/api/BrandingApi.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/api/ChangeRequestApi.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/api/SupervisedTargetsApi.scala
- datasources/src/main/scala/com/normation/plugins/datasources/api/DataSourceApi.scala
- user-management/src/main/scala/com/normation/plugins/usermanagement/api/UserManagementApi.scala
https://issues.rudder.io/issues/14810
> Fixes #14810: Correct API order in plugins  

- Makefile
- create-node-api/LICENSE
- create-node-api/LICENSE_EXCEPTION
- create-node-api/Makefile
- create-node-api/README.asciidoc
- create-node-api/build.conf
- create-node-api/packaging/metadata
- create-node-api/packaging/postinst
- create-node-api/pom-template.xml
- create-node-api/src/main/resources/template/CreateNodeApiManagement.html
- create-node-api/src/main/resources/toserve/createnodeapi/create-node-api.css
- create-node-api/src/main/resources/toserve/createnodeapi/create-node-api.js
- create-node-api/src/main/scala-templates/default/com/normation/plugins/createnodeapi/EnablePluginImpl.scala
- create-node-api/src/main/scala-templates/limited/com/normation/plugins/createnodeapi/EnablePluginImpl.scala
- create-node-api/src/main/scala/bootstrap/rudder/plugin/CreatenodeapiConf.scala
- create-node-api/src/main/scala/com/normation/plugins/createnodeapi/CreateNodeApi.scala
- create-node-api/src/main/scala/com/normation/plugins/createnodeapi/CreateNodeApiPluginDef.scala
- create-node-api/src/main/scala/com/normation/plugins/createnodeapi/DataTypes.scala
- create-node-api/src/test/resources/logback-test.xml
https://issues.rudder.io/issues/7876
> Fixes #7876: [API] Create function to "pre-create" a node

- change-validation/README.adoc
- change-validation/src/main/elm/build-app.sh
- change-validation/src/main/elm/build-dev.sh
- change-validation/src/main/elm/sources/ApiCalls.elm
- change-validation/src/main/elm/sources/DataTypes.elm
- change-validation/src/main/elm/sources/Init.elm
- change-validation/src/main/elm/sources/JsonDecoders.elm
- change-validation/src/main/elm/sources/JsonEncoders.elm
- change-validation/src/main/elm/sources/View.elm
- change-validation/src/main/elm/sources/WorkflowUsers.elm
- change-validation/src/main/resources/change-validation-schema.sql
- change-validation/src/main/resources/template/ChangeValidationManagement.html
- change-validation/src/main/resources/toserve/changevalidation/change-validation.css
- change-validation/src/main/scala/bootstrap/rudder/plugin/ChangeValidationConf.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/ValidatedUserJdbcRepository.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/ValidatedUserRepository.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/ValidationNeeded.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/api/ValidatedUserApi.scala
https://issues.rudder.io/issues/14826
> Fixes #14826: Select a group of user concerned by the workflow

- Makefile
https://issues.rudder.io/issues/15114
> Fixes #15114: Improve doc build to include all plugins

- change-validation/src/main/elm/sources/supervised-targets.elm
https://issues.rudder.io/issues/14756
> Fixes #14756: Success notification on save goes behind  input group

- create-node-api/packaging/postinst
- create-node-api/src/main/resources/template/CreateNodeApiManagement.html
- create-node-api/src/main/scala/bootstrap/rudder/plugin/CreatenodeapiConf.scala
- create-node-api/src/main/scala/com/normation/plugins/createnodeapi/CreateNodeApi.scala
- create-node-api/src/main/scala/com/normation/plugins/createnodeapi/CreateNodeApiPluginDef.scala
- create-node-api/src/main/scala/com/normation/plugins/createnodeapi/DataTypes.scala
https://issues.rudder.io/issues/15296
> Fixes #15296: Release first version of create-node-api plugin

- create-node-api/README.asciidoc
- create-node-api/build.conf
- create-node-api/src/main/resources/template/CreateNodeApiManagement.html
- create-node-api/src/main/scala/com/normation/plugins/createnodeapi/DataTypes.scala
https://issues.rudder.io/issues/15346
> Fixes #15346: API must be consistant with node agent key management

- create-node-api/src/main/scala/com/normation/plugins/createnodeapi/DataTypes.scala
https://issues.rudder.io/issues/15395
> Fixes #15395: Invalid name for certificate value in JSON

- datasources/src/test/scala/com/normation/plugins/datasources/UpdateHttpDatasetTest.scala
- user-management/src/test/scala/com/normation/plugins/usermanagement/RoleComputationTest.scala
https://issues.rudder.io/issues/15468
> Fixes #15468: Fix tests in plugins for branch 5.1

- user-management/src/test/scala/com/normation/plugins/usermanagement/RoleComputationTest.scala
https://issues.rudder.io/issues/15593
> Fixes #15593: Wrong import in RoleComputationTest

- user-management/pom-template.xml
https://issues.rudder.io/issues/15594
> Fixes #15594: Missing better-files depenency in pom-template

- Makefile
- main-build.conf
- makefiles/global-vars.mk
https://issues.rudder.io/issues/15728
> Fixes #15728: Make plugins nightlies great again

- version-compat.adoc
https://issues.rudder.io/issues/15761
> Fixes #15761: Update compatibility of plugins in documentation

- cis/Makefile
- cis/configuration/directives/0146f6f9-040f-4c3d-9001-0f2bc165b6c1.json
- cis/configuration/directives/0b8e988c-fa02-42a0-813c-e07ff6eafb9a.json
- cis/configuration/directives/1002c78b-b3f6-458e-99d7-a7c63ffbabf7.json
- cis/configuration/directives/1115f714-4571-498b-81c8-bd3b6c4b0eb9.json
- cis/configuration/directives/161c3b44-e8c9-456a-99ca-18ca6721d87d.json
- cis/configuration/directives/1affb4e0-606a-4255-bbac-75b6f68118e1.json
- cis/configuration/directives/2b03c63d-e213-4433-b12d-5a3ab0c707f4.json
- cis/configuration/directives/3025b555-2f96-4cb0-babc-9153f089e585.json
- cis/configuration/directives/330783bc-2471-45c8-bc88-702385177e78.json
- cis/configuration/directives/416c5a77-3f2a-4822-94f1-a4e8c8d0f561.json
- cis/configuration/directives/420826fd-bac2-4409-b311-93d88f3123d2.json
- cis/configuration/directives/57bd91e5-c12d-4797-953c-347ffd798018.json
- cis/configuration/directives/5e475cb1-b68d-4b6d-a292-7bc04f0f229a.json
- cis/configuration/directives/660d0644-9efd-406d-8c5d-a4796c61d90e.json
- cis/configuration/directives/7309c1bf-49ca-48aa-84e6-0db3dd7c6b14.json
- cis/configuration/directives/758545d1-136d-49d9-b221-392909e07ff3.json
- cis/configuration/directives/76dd67df-f8f8-437b-bfae-f39220abed4c.json
- cis/configuration/directives/7ade9894-cc47-4257-8b7a-1a4ac59150e8.json
- cis/configuration/directives/9a0c3a1c-60f4-45a1-8f3e-8952273fb92d.json
- cis/configuration/directives/a258d038-fb8d-4a70-b5fb-67e5d309fd02.json
- cis/configuration/directives/a42ba100-62e6-48f2-8040-df7029545ec7.json
- cis/configuration/directives/c077b0af-e225-4bf0-9274-7c6948e15949.json
- cis/configuration/directives/d731f8d5-487e-43c2-98b7-225b1d470c58.json
- cis/configuration/directives/e00cd58e-8554-4259-9ced-9c4a463ce637.json
- cis/configuration/directives/e9baea03-0e70-4526-9e10-5a3d6da950dd.json
- cis/configuration/directives/ef56283e-6503-4628-be96-a763dce29dfb.json
- cis/configuration/directives/fe120766-526c-456b-bc54-e69d9acba92e.json
- cis/configuration/techniques/Ensure sysctl key IPV4.json
- cis/tools/cis-tag
https://issues.rudder.io/issues/15807
> Fixes #15807: Add sysctl IPV4 cis items

- scale-out-relay/packaging/postinst
https://issues.rudder.io/issues/15831
> Fixes #15831: When installing scale out plugin, it doesn't trigger the policy regeneration at the right time

- cis/packaging/rudder-synchronize
https://issues.rudder.io/issues/15837
> Fixes #15837: Add technique export to rudder-synchronize

- cis/packaging/rudder-synchronize
https://issues.rudder.io/issues/15848
> Fixes #15848: Limit the usage of global variables in rudder-synchronize

- change-validation/src/main/scala/bootstrap/rudder/plugin/ChangeValidationConf.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/api/ChangeRequestApi.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/api/ValidatedUserApi.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/snippet/ChangeRequestChangesForm.scala
https://issues.rudder.io/issues/16014
> Fixes #16014: Change validation does not compile with latest version

- ansible-report/LICENSE
- ansible-report/LICENSE_EXCEPTION
- ansible-report/Makefile
- ansible-report/README.adoc
- ansible-report/build.conf
- ansible-report/configuration-repository/ncf/50_techniques/ansible_report/ansible_report.cf
- ansible-report/configuration-repository/techniques/ansible_report/category.xml
- ansible-report/packaging/metadata
- ansible-report/packaging/postinst
- ansible-report/packaging/prerm
https://issues.rudder.io/issues/16048
> Fixes #16048: Make a plugin from the current ansible report script

- cis/README.adoc
https://issues.rudder.io/issues/15942
> Fixes #15942: Improve CIS documentation

- change-validation/src/main/scala/com/normation/plugins/changevalidation/snippet/ChangeRequestChangesForm.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/snippet/ChangeRequestDetails.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/snippet/ChangeRequestManagement.scala
- helloworld/src/main/scala/com/normation/plugins/helloworld/extension/CreateRuleExtension.scala
- main-build.conf
- user-management/src/main/scala/com/normation/plugins/usermanagement/UserManagementService.scala
- user-management/src/main/scala/com/normation/plugins/usermanagement/api/UserManagementApi.scala
- user-management/src/test/scala/com/normation/plugins/usermanagement/RoleComputationTest.scala
https://issues.rudder.io/issues/16132
> Fixes #16132: Update change validation and hello world to Rudder 6.0

- auth-backends/src/main/elm/sources/auth-backends.elm
https://issues.rudder.io/issues/16153
> Fixes #16153: Authentication Backends plugin has typo

- create-node-api/README.adoc
- create-node-api/src/main/resources/template/CreateNodeApiManagement.html
https://issues.rudder.io/issues/16165
> Fixes #16165: Documentation bug for node-create-api

- centreon/packaging/metadata
https://issues.rudder.io/issues/16090
> Fixes #16090: Plugin depends on python libs that are not listed in the packaging nor in the doc

- user-management/README.adoc
https://issues.rudder.io/issues/16190
> Fixes #16190: move historical doc to the dedicated plugin documentation

- change-validation/src/main/scala/com/normation/plugins/changevalidation/snippet/ChangeRequestChangesForm.scala
https://issues.rudder.io/issues/9788
> Fixes #9788: Changing a Directive from "Inherit Standard" to "Audit only" does not show a Diff in CR-Mode enabled

- auth-backends/src/main/resources/applicationContext-security-auth-radius.xml
- auth-backends/src/main/scala/com/normation/plugins/authbackends/RadiusAuthentication.scala
https://issues.rudder.io/issues/16270
> Fixes #16270: Radius authentication throw exception at boot

- change-validation/src/main/scala/com/normation/plugins/changevalidation/ChangeRequestJdbcRepository.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/ValidatedUserJdbcRepository.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/WorkflowJdbcRepository.scala
- datasources/pom-template.xml
- datasources/src/main/scala/com/normation/plugins/datasources/Repository.scala
- datasources/src/main/scala/com/normation/plugins/datasources/Scheduler.scala
- datasources/src/test/scala/com/normation/plugins/datasources/UpdateHttpDatasetTest.scala
https://issues.rudder.io/issues/16351
> Fixes #16351: Plugins don't compile anymore

- auth-backends/build.conf
- branding/build.conf
- datasources/build.conf
- main-build.conf
- node-external-reports/build.conf
- scale-out-relay/build.conf
https://issues.rudder.io/issues/16370
> Fixes #16370: Release plugin for 6.0

- cis/Makefile
- cis/README.adoc
- cis/tools/cis-tag
https://issues.rudder.io/issues/16381
> Fixes #16381: Modify makefile to use pdfs from our private repos

- cis/Makefile
- cis/packaging/metadata
- cis/packaging/postinst
https://issues.rudder.io/issues/16365?issue_count=11&issue_position=1&next_issue_id=16103
> Fixes #16365: backport category creation to 5.0

- Makefile
https://issues.rudder.io/issues/16420
> Fixes #16420: Global Makefile should detect itself the plugins in the repo

- cis/README.adoc
https://issues.rudder.io/issues/16423
> Fixes #16423: Readme does not follow the correct syntax policy

- user-management/src/main/scala/com/normation/plugins/usermanagement/UserManagementService.scala
https://issues.rudder.io/issues/15822
> Fixes #15822: IllegalArgumentException: Missing scheme when deleting user

- centreon/share/python/ipaddress.py
https://issues.rudder.io/issues/16531
> Fixes #16531: Unwanted debbug print in ipaddress.py

- user-management/src/main/scala/com/normation/plugins/usermanagement/UserManagementService.scala
https://issues.rudder.io/issues/16535
> Fixes #16535: Missing scheme error when adding an user from the UI

- user-management/src/main/elm/sources/View.elm
https://issues.rudder.io/issues/16296
> Fixes #16296: Updating informations by submitting empty fields invalidates user's loggin 

- README.adoc
- branding/pom-template.xml
- branding/src/main/scala/com/normation/plugins/branding/snippet/LoginBranding.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/snippet/ChangeRequestChangesForm.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/snippet/ChangeRequestDetails.scala
- create-node-api/pom-template.xml
- datasources/pom-template.xml
- datasources/src/main/scala/com/normation/plugins/datasources/QueryService.scala
- datasources/src/main/scala/com/normation/plugins/datasources/Serialization.scala
- datasources/src/main/scala/com/normation/plugins/datasources/UpdateHttpDataset.scala
- datasources/src/test/scala/com/normation/plugins/datasources/UpdateHttpDatasetTest.scala
- helloworld/build.conf
- helloworld/pom-template.xml
- helloworld/src/main/scala/com/normation/plugins/helloworld/extension/CreateRuleExtension.scala
- helloworld/src/main/scala/com/normation/plugins/helloworld/service/LogAccessInDb.scala
- main-build.conf
- node-external-reports/pom-template.xml
- node-external-reports/src/main/scala/com/normation/plugins/nodeexternalreports/service/ReadExternalReports.scala
- pom-template.xml
- user-management/pom-template.xml
- version-compat.adoc
https://issues.rudder.io/issues/16562
> Fixes #16562: Port plugins to scala 2.13

- user-management/src/main/elm/sources/View.elm
https://issues.rudder.io/issues/16566
> Fixes #16566: Reload users configuration file from the UI

- cis/build.conf
- cis/configuration/techniques/Disable_Service.json
- cis/configuration/techniques/Disable_kernel_module_loading.json
- cis/configuration/techniques/Enable_Service.json
- cis/configuration/techniques/Ensure_a_package_is_installed.json
- cis/configuration/techniques/Ensure_a_package_is_not_installed.json
- cis/configuration/techniques/Ensure_gpgcheck_is_globally_activated.json
- cis/configuration/techniques/Ensure_key_value_in_file.json
- cis/configuration/techniques/Ensure_lines_present_in_file.json
- cis/configuration/techniques/Ensure_mounting_partition_is_correct.json
- cis/configuration/techniques/Ensure_sysctl_key_value_IPV4.json
- cis/configuration/techniques/Ensure_sysctl_key_value_IPV6.json
- cis/configuration/techniques/Execute_command.json
- cis/configuration/techniques/Set_permissions.json
- cis/packaging/postinst
- cis/packaging/rudder-synchronize
https://issues.rudder.io/issues/16103
> Fixes #16103: Add a CIS category and put everything in it

- user-management/src/main/elm/sources/DataTypes.elm
- user-management/src/main/elm/sources/Init.elm
- user-management/src/main/elm/sources/UserManagement.elm
- user-management/src/main/elm/sources/View.elm
https://issues.rudder.io/issues/16611
> Fixes #16611: Change model in user management and text from buttons

- main-build.conf
https://issues.rudder.io/issues/16656
> Fixes #16656: need to update plugin-common-private to be compatible Scala 2.13

- plugins-common-private/pom-template.xml
https://issues.rudder.io/issues/16660
> Fixes #16660: Update licence lib to 2.0

- user-management/src/main/elm/sources/ApiCalls.elm
- user-management/src/main/elm/sources/DataTypes.elm
- user-management/src/main/elm/sources/Init.elm
- user-management/src/main/elm/sources/UserManagement.elm
- user-management/src/main/elm/sources/View.elm
- user-management/src/main/resources/template/UserManagement.html
- user-management/src/main/resources/toserve/usermanagement/user-management.css
- user-management/src/main/scala/com/normation/plugins/usermanagement/UserManagementService.scala
https://issues.rudder.io/issues/16605
> Fixes #16605: Beautify and improve UX/UI

- branding/src/main/resources/template/brandingManagement.html
- branding/src/main/resources/toserve/branding/media.css
- branding/src/main/scala/com/normation/plugins/branding/snippet/CommonBranding.scala
- branding/src/main/scala/com/normation/plugins/branding/snippet/LoginBranding.scala
https://issues.rudder.io/issues/12949
> Fixes #12949: Transparency leads to broken display

- openscap-report/Makefile
https://issues.rudder.io/issues/16776
> Fixes #16776: Update rudder_synchronyze checksum

- scale-out-relay/README.adoc
https://issues.rudder.io/issues/16747
> Fixes #16747: Add documentation on version/reporting mode compatibility for the relays

- ansible-policies/README.adoc
https://issues.rudder.io/issues/16809
> Fixes #16809: Remove installation hack steps from the documentation

- centreon/packaging/metadata
https://issues.rudder.io/issues/16590
> Fixes #16590: Cannot install Centreon plugin 

- openscap-report/configuration/techniques/plugin_openscap_report.json
https://issues.rudder.io/issues/16610
> Fixes #16610: Update openSCAP plugin to support multiple OS

- user-management/src/main/scala/com/normation/plugins/usermanagement/DataTypes.scala
- user-management/src/main/scala/com/normation/plugins/usermanagement/UserManagementService.scala
https://issues.rudder.io/issues/16720
> Fixes #16720: Add BCrypt support for password encoder message box

- cis/Makefile
- cis/tools/cis-tag
https://issues.rudder.io/issues/16920
> Fixes #16920: Add Ubuntu18 benchmark support

- openscap-report/packaging/metadata
https://issues.rudder.io/issues/16952
> Fixes #16952: error at installation of openscap plugin

- datasources/pom-template.xml
- datasources/src/main/scala/com/normation/plugins/datasources/DataSourcesPluginDef.scala
- datasources/src/main/scala/com/normation/plugins/datasources/Repository.scala
- datasources/src/main/scala/com/normation/plugins/datasources/Scheduler.scala
- datasources/src/main/scala/com/normation/plugins/datasources/UpdateHttpDataset.scala
- datasources/src/test/scala/com/normation/plugins/datasources/UpdateHttpDatasetTest.scala
- pom-template.xml
https://issues.rudder.io/issues/16959
> Fixes #16959: Revert datasource port to zio rc18 in 6.0 branch

- vault/share/plugins/vault/30_generic_methods/variable_from_vault.cf
https://issues.rudder.io/issues/16973
> fixes #16973 : Always repaired state while executing agent

- ansible-policies/README.adoc
- api-authorizations/README.adoc
- branding/README.adoc
- create-node-api/README.adoc
https://issues.rudder.io/issues/16985
> Fixes #16985: Ansible plugin doc has incorrect title

- vault/share/plugins/vault/30_generic_methods/variable_from_vault.cf
https://issues.rudder.io/issues/17011
> fixes #17011: Generic method path parameter description change

- cis/Makefile.plugin
- cis/packaging/prerm
- cis/packaging/remove_configuration
- cis/src/tools/trackConfig.py
https://issues.rudder.io/issues/16948
> Fixes #16948: Cleanup the uninstall process

- openscap-report/configuration/techniques/plugin_openscap_report.json
https://issues.rudder.io/issues/16953
> Fixes #16953: error when using openscap technique

- qa-test
https://issues.rudder.io/issues/17038
> Fixes #17038: typo in qa-test

- consul/build.conf
- consul/share/plugins/consul/20_cfe_basics/consul_lib.cf
- consul/share/plugins/consul/30_generic_methods/variable_from_consul.cf
https://issues.rudder.io/issues/17064
> fixes #17064: Consul plugin's code modification

- vault/share/plugins/vault/20_cfe_basics/vault_lib.cf
- vault/share/plugins/vault/30_generic_methods/variable_from_vault.cf
- vault/share/plugins/vault/sample_vault.json
https://issues.rudder.io/issues/17083
> Fix 17083 make the generic method usable with self-signed tls

- consul/share/plugins/consul/20_cfe_basics/consul_lib.cf
- consul/share/plugins/consul/30_generic_methods/variable_from_consul.cf
https://issues.rudder.io/issues/17042
> fixes #17042: Plugins should not use a hardcoded path for curl

- consul/share/plugins/consul/20_cfe_basics/consul_lib.cf
- vault/README.adoc
https://issues.rudder.io/issues/17096
> fixes #17096 Improve Vault Doc

- vault/share/plugins/vault/30_generic_methods/variable_from_vault.cf
https://issues.rudder.io/issues/17103
> fixes #17103: Variable from vault file must contains two [data] levels

- user-management/src/main/scala/com/normation/plugins/usermanagement/UserManagementService.scala
https://issues.rudder.io/issues/17086
> Fixes #17086: Missing scheme error when adding an user 

- user-management/src/main/resources/toserve/usermanagement/user-management.css
https://issues.rudder.io/issues/17077
> Fixes #17077: User creation area is cut when branding plugin is enabled

- scale-out-relay/Makefile
- scale-out-relay/packaging/postinst
- scale-out-relay/src/main/resources/server-node-to-relay
https://issues.rudder.io/issues/17177
> Fixes #17177: Distribute node-to-relay script with the plugin 

- scale-out-relay/src/main/scala/bootstrap/rudder/plugin/ScaleOutRelayConf.scala
- scale-out-relay/src/main/scala/com/normation/plugins/scaleoutrelay/ScaleOutRelayPluginDef.scala
- scale-out-relay/src/main/scala/com/normation/plugins/scaleoutrelay/ScaleOutRelayService.scala
- scale-out-relay/src/main/scala/com/normation/plugins/scaleoutrelay/api/ScaleOutRelayApi.scala
https://issues.rudder.io/issues/16743
> Fixes #16743: Promote a node to relay

- auth-backends/src/main/scala/com/normation/plugins/authbackends/AuthBackendsRepository.scala
https://issues.rudder.io/issues/17259
> Fixes #17259: Bad property name for radius port in API

- change-validation/src/main/scala/com/normation/plugins/changevalidation/WorkflowService.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/snippet/ChangeRequestChangesForm.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/snippet/ChangeValidationSettings.scala
https://issues.rudder.io/issues/17269
> Fixes #17269: Adapt change validation plugin to changes made with properties (goup / global)

- scale-out-relay/src/main/scala/com/normation/plugins/scaleoutrelay/ScaleOutRelayService.scala
https://issues.rudder.io/issues/17279
> Fixes #17279: Adapt Scale out relay plugin to 6.1

- centreon/README.adoc
- cis/README.adoc
- consul/README.adoc
- glpi/README.adoc
- notify/README.adoc
- openscap-report/README.adoc
- vault/README.adoc
- zabbix/README.adoc
https://issues.rudder.io/issues/17276
> Fixes #17276: Clean pugin install docs

- datasources/src/main/scala/com/normation/plugins/datasources/QueryService.scala
- datasources/src/main/scala/com/normation/plugins/datasources/Repository.scala
- datasources/src/main/scala/com/normation/plugins/datasources/Scheduler.scala
- datasources/src/main/scala/com/normation/plugins/datasources/UpdateHttpDataset.scala
- datasources/src/main/scala/com/normation/plugins/datasources/api/DataSourceApiImpl.scala
- datasources/src/test/scala/com/normation/plugins/datasources/UpdateHttpDatasetTest.scala
- helloworld/src/main/scala/bootstrap/rudder/plugin/HelloWorldConf.scala
https://issues.rudder.io/issues/17278
> Fixes #17278: Adapt datasource plugin to 6.1

- create-node-api/src/main/scala/com/normation/plugins/createnodeapi/CreateNodeApi.scala
- create-node-api/src/main/scala/com/normation/plugins/createnodeapi/DataTypes.scala
https://issues.rudder.io/issues/17277
> Fixes #17277: Adapt create node api to 6.1

- user-management/README.adoc
https://issues.rudder.io/issues/17343
> Fixes #17343: Update documentation about custom roles

- change-validation/src/main/scala/com/normation/plugins/changevalidation/snippet/ChangeRequestChangesForm.scala
- datasources/pom-template.xml
- datasources/src/main/scala/com/normation/plugins/datasources/DataTypes.scala
- datasources/src/main/scala/com/normation/plugins/datasources/UpdateHttpDataset.scala
- datasources/src/test/scala/com/normation/plugins/datasources/UpdateHttpDatasetTest.scala
https://issues.rudder.io/issues/17448
> Fixes #17448: Fix non compiling plugins after changes on Rudder

- openscap-policies/README.adoc
https://issues.rudder.io/issues/17452
> Fixes #17452: document openscap plugin

- cis/src/debian9/directives/b078d18e-7a99-4bd5-8386-43eaf4f3669f.json
- cis/src/redhat7/directives/d892c617-31b3-4d58-8715-914d2c2fb4b2.json
- cis/src/ubuntu18/directives/f28f4308-a37c-4b73-b5a8-09edfbac312d.json
https://issues.rudder.io/issues/17302
> Fixes #17302: The plugin check for module freexvfs instead of freevxfs

- openscap-policies/Makefile
- openscap-policies/packaging/postinst
https://issues.rudder.io/issues/17346
> Fixes #17346: update openscap to use rudder_synchronize from rudder itself

- openscap-policies/src/main/scala/com/normation/plugins/openscappolicies/extension/OpenScapNodeDetailsExtension.scala
https://issues.rudder.io/issues/17540
> Fixes #17540: openscap plugin replace technical logs by "test"

- scale-out-relay/src/main/resources/server-node-to-relay
https://issues.rudder.io/issues/17548
> Fixes #17548: Broken line breaks in postinst output

- branding/src/main/scala/com/normation/plugins/branding/snippet/CommonBranding.scala
https://issues.rudder.io/issues/17436
> Fixes #17436: Empty footer in sidebar 

- change-validation/src/main/scala/com/normation/plugins/changevalidation/snippet/ChangeRequestChangesForm.scala
- create-node-api/src/main/scala/com/normation/plugins/createnodeapi/DataTypes.scala
- datasources/src/main/scala/com/normation/plugins/datasources/DataTypes.scala
- datasources/src/main/scala/com/normation/plugins/datasources/Serialization.scala
- datasources/src/main/scala/com/normation/plugins/datasources/UpdateHttpDataset.scala
- datasources/src/main/scala/com/normation/plugins/datasources/api/DataSourceApiImpl.scala
- datasources/src/test/scala/com/normation/plugins/datasources/JsonPathTest.scala
- datasources/src/test/scala/com/normation/plugins/datasources/UpdateHttpDatasetTest.scala
- main-build.conf
https://issues.rudder.io/issues/17587
> Fixes #17587: Adapt plugin to 6.1 rc releases, especially properties Hocon format

- datasources/src/main/resources/template/dataSourceManagement.html
- datasources/src/main/scala/com/normation/plugins/datasources/UpdateHttpDataset.scala
- datasources/src/test/scala/com/normation/plugins/datasources/JsonPathTest.scala
- datasources/src/test/scala/com/normation/plugins/datasources/UpdateHttpDatasetTest.scala
https://issues.rudder.io/issues/17640
> Fixes #17640: Datasource retrieve string in place of json

- vault/README.adoc
https://issues.rudder.io/issues/17714
> Fixes #17714: Typo in vault documentation

- branding/src/main/scala/com/normation/plugins/branding/BrandingConf.scala
- branding/src/main/scala/com/normation/plugins/branding/BrandingConfService.scala
- branding/src/main/scala/com/normation/plugins/branding/api/BrandingApi.scala
- branding/src/main/scala/com/normation/plugins/branding/snippet/CommonBranding.scala
https://issues.rudder.io/issues/17833
> Fixes #17833: NPE on start

- api-authorizations/src/main/elm/build-app.sh
- auth-backends/src/main/elm/build-app.sh
- branding/src/main/elm/build-app.sh
- change-validation/src/main/elm/build-app.sh
- user-management/src/main/elm/build-app.sh
https://issues.rudder.io/issues/17886
> Fixes #17886: Optimize elm plugins

- datasources/src/main/scala/com/normation/plugins/datasources/QueryService.scala
https://issues.rudder.io/issues/17826
> Fixes #17826: Ignored node should be ignored for datasource

- change-validation/src/main/resources/template/ChangeValidationManagement.html
- change-validation/src/main/scala/bootstrap/rudder/plugin/ChangeValidationConf.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/ValidationNeeded.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/snippet/ChangeRequestChangesForm.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/snippet/ChangeRequestDetails.scala
https://issues.rudder.io/issues/17819
> Fixes #17819: Trying to add a group property with change request plugin enabled lead to a blanck property (plugin side)

- branding/README.adoc
https://issues.rudder.io/issues/18034
> Fixes #18034: Broken image in branding plugin doc

- datasources/README.adoc
- datasources/src/main/scala/com/normation/plugins/datasources/UpdateHttpDataset.scala
- datasources/src/test/scala/com/normation/plugins/datasources/JsonPathTest.scala
- datasources/src/test/scala/com/normation/plugins/datasources/UpdateHttpDatasetTest.scala
https://issues.rudder.io/issues/17828
> Fixes #17828: Inject short hostname as a node property to be able to use it in url/json path

- change-validation/Makefile
- change-validation/packaging/postinst
- change-validation/pom-template.xml
- change-validation/src/main/resources/cancelled-mail.template
- change-validation/src/main/resources/change-validation.conf
- change-validation/src/main/resources/deployed-mail.template
- change-validation/src/main/resources/deployment-mail.template
- change-validation/src/main/resources/validation-mail.template
- change-validation/src/main/scala/bootstrap/rudder/plugin/ChangeValidationConf.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/DataTypes.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/NotificationService.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/WorkflowService.scala
https://issues.rudder.io/issues/17205
> Fixes #17205: Notifiy change validation request by email

- change-validation/README.adoc
https://issues.rudder.io/issues/18099
> Fixes #18099: Document notification email feature

- auth-backends/pom-template.xml
- auth-backends/src/main/scala/com/normation/plugins/authbackends/RadiusAuthentication.scala
https://issues.rudder.io/issues/18206
> Fixes #18206: Radius client incorrectly send password after first time

- auth-backends/src/main/scala/bootstrap/rudder/plugin/AuthBackendsConf.scala
- auth-backends/src/main/scala/com/normation/plugins/authbackends/RadiusAuthentication.scala
https://issues.rudder.io/issues/18230
> Fixes #18230: Stacktrace when radius connection timeout

- consul/share/plugins/consul/30_generic_methods/variable_from_consul.cf
https://issues.rudder.io/issues/18240
> Fixes #18240: Broken URL scheme for consul server

- glpi/bin/glpi-plugin
https://issues.rudder.io/issues/18234
> Fixes #18234: 2 curl lines

- datasources/src/test/scala/com/normation/plugins/datasources/UpdateHttpDatasetTest.scala
https://issues.rudder.io/issues/18288
> Fixes #18288: Add tests regarding arrays

- datasources/src/main/scala/com/normation/plugins/datasources/UpdateHttpDataset.scala
https://issues.rudder.io/issues/18287
> Fixes #18287: Only first element of root array is collected

- datasources/src/test/scala/com/normation/plugins/datasources/UpdateHttpDatasetTest.scala
https://issues.rudder.io/issues/18310
> Fixes #18310: Broken datasources test

- auth-backends/README.adoc
https://issues.rudder.io/issues/18402
> Fixes #18402: Missing doc about restart jetty after change in config

- create-node-api/README.adoc
https://issues.rudder.io/issues/18470
> Fixes #18470: Fix link to create-node API doc

- change-validation/src/main/scala/com/normation/plugins/changevalidation/ValidatedUserJdbcRepository.scala
https://issues.rudder.io/issues/18518
> Fixes #18518: Cannot remove a validated user

- change-validation/src/main/scala/com/normation/plugins/changevalidation/ValidatedUserJdbcRepository.scala
https://issues.rudder.io/issues/18519
> Fixes #18519: User Plugin can not be build with previous version of Rudder API

- change-validation/src/main/scala/com/normation/plugins/changevalidation/snippet/ChangeRequestChangesForm.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/snippet/ChangeRequestManagement.scala
- helloworld/src/main/scala/com/normation/plugins/helloworld/extension/CreateRuleExtension.scala
https://issues.rudder.io/issues/18550
> Fixes #18550: DateFormaterService moved in plugins

- auth-backends/src/main/scala/com/normation/plugins/authbackends/AuthBackendsPluginDef.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/ChangeValidationPluginDef.scala
- create-node-api/src/main/scala/com/normation/plugins/createnodeapi/CreateNodeApiPluginDef.scala
- openscap/src/main/scala/com/normation/plugins/openscappolicies/OpenscapPoliciesPluginDef.scala
- user-management/src/main/scala/com/normation/plugins/usermanagement/UserManagementPluginDef.scala
https://issues.rudder.io/issues/18599
> Fixes #18599: Make plugins display names more consistent

- branding/src/main/scala/com/normation/plugins/branding/api/BrandingApi.scala
- change-validation/src/main/scala/bootstrap/rudder/plugin/ChangeValidationConf.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/ChangeRequestJdbcRepository.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/ChangeRequestRepository.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/ChangeValidationPluginDef.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/WorkflowService.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/comet/WorkflowInformation.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/snippet/ChangeRequestChangesForm.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/snippet/ChangeRequestDetails.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/snippet/ChangeRequestManagement.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/snippet/ChangeValidationSettings.scala
- create-node-api/src/main/scala/com/normation/plugins/createnodeapi/CreateNodeApi.scala
- create-node-api/src/main/scala/com/normation/plugins/createnodeapi/DataTypes.scala
- datasources/src/main/scala/bootstrap/rudder/plugin/DataSourcesConf.scala
- datasources/src/main/scala/com/normation/plugins/datasources/DataTypes.scala
- datasources/src/main/scala/com/normation/plugins/datasources/QueryService.scala
- datasources/src/main/scala/com/normation/plugins/datasources/Repository.scala
- datasources/src/main/scala/com/normation/plugins/datasources/Scheduler.scala
- datasources/src/main/scala/com/normation/plugins/datasources/UpdateHttpDataset.scala
- datasources/src/test/scala/com/normation/plugins/datasources/UpdateHttpDatasetTest.scala
- openscap/src/main/scala/com/normation/plugins/openscappolicies/api/OpenScapApi.scala
- openscap/src/main/scala/com/normation/plugins/openscappolicies/services/GetActiveTechniqueIds.scala
- user-management/src/main/scala/com/normation/plugins/usermanagement/UserManagementService.scala
https://issues.rudder.io/issues/18630
> Fixes #18630: Fix plugins build according to 6.2 changes

- datasources/src/main/scala/com/normation/plugins/datasources/Scheduler.scala
- datasources/src/main/scala/com/normation/plugins/datasources/UpdateHttpDataset.scala
- datasources/src/test/scala/com/normation/plugins/datasources/JsonPathTest.scala
- datasources/src/test/scala/com/normation/plugins/datasources/UpdateHttpDatasetTest.scala
https://issues.rudder.io/issues/18643
> Fixes #18643: Datasources test in error

- datasources/src/test/scala/com/normation/plugins/datasources/UpdateHttpDatasetTest.scala
https://issues.rudder.io/issues/18697
> Fixes #18697: datasource tests *still* in error

- change-validation/src/main/resources/change-validation.conf
https://issues.rudder.io/issues/18875
> Fixes #18875: Error when parsing change-validation.conf file

- api-authorizations/src/main/elm/build-dev.sh
- api-authorizations/src/main/elm/sources/api-authorizations.elm
https://issues.rudder.io/issues/18958
> Fixes #18958: Custom ACL menu is not displayed

- scale-out-relay/src/main/resources/server-node-to-relay
https://issues.rudder.io/issues/18968
> Fixes #18968: Command rudder server node-to-relay may fail with curl error

- Makefile
- cis/Makefile
- cis/Makefile.plugin
- makefiles/common-plugin.mk
- makefiles/make-plugins-common.mk
https://issues.rudder.io/issues/19030
> Fixes #19030: Make cis plugin build

- change-validation/src/main/resources/change-validation.conf
https://issues.rudder.io/issues/19148
> Fixes #19148: Parsing error when the port is undefined in change-validation.conf

- api-authorizations/pom-template.xml
- auth-backends/pom-template.xml
- branding/pom-template.xml
- change-validation/pom-template.xml
- create-node-api/pom-template.xml
- datasources/pom-template.xml
- helloworld/pom-template.xml
- node-external-reports/pom-template.xml
- openscap/pom-template.xml
- plugins-common-private/pom-template.xml
- pom-template.xml
- scale-out-relay/pom-template.xml
- user-management/pom-template.xml
https://issues.rudder.io/issues/19165
> Fixes #19165: 

- src/main/g8/pom-template.xml
https://issues.rudder.io/issues/19168
> Fixes #19168: 

- Jenkinsfile-security
- dependency-check-suppression.xml
https://issues.rudder.io/issues/19230
> Fixes #19230: Add dependency check for plugins

- Makefile
https://issues.rudder.io/issues/19239
> Fixes #19239: Broken generate-all-pom-nightly in master

- Makefile
https://issues.rudder.io/issues/19240
> Fixes #19240: Wrong depedency on generate-all-pom-nightly

- Jenkinsfile-security
https://issues.rudder.io/issues/19253
> Fixes #19253: Set vulnerability level to a higher value

- Jenkinsfile-security
https://issues.rudder.io/issues/19256
> Fixes #19256: build plgin commons before checking dependencies

- dependency-check-suppression.xml
https://issues.rudder.io/issues/19275
> Fixes #19275:  Ignore security alert for unused js embeded in scala lib (plugin)

- Jenkinsfile-security
https://issues.rudder.io/issues/19279
> Fixes #19279: For plugins, we need to skip CVE check on provided dependencies

- change-validation/README.adoc
- change-validation/src/main/resources/template/ChangeValidationManagement.html
- change-validation/src/main/scala/com/normation/plugins/changevalidation/NotificationService.scala
https://issues.rudder.io/issues/19147
> Fixes #19147: Email notification should be disabled when no host server is configured

- main-build.conf
- pom-template.xml
https://issues.rudder.io/issues/18979
> Fixes #18979: Add licenses tag in plugins pom

- openscap/pom-template.xml
- openscap/src/main/resources/antisamy.xml
- openscap/src/main/resources/antisamy.xsd
https://issues.rudder.io/issues/19252
> Fixes #19252: 

- notify/share/python/notifyd.py
https://issues.rudder.io/issues/19384
> Fixes #19384: Notification plugin fails on python3

- auth-backends/README.adoc
https://issues.rudder.io/issues/19401
> Fixes #19401: Add an ldapsearch example in config file for LDAP auth

- vault/README.adoc
https://issues.rudder.io/issues/19418
> Fixes #19418: Typo on Plugin Documentation

- .gitignore
- Jenkinsfile
- centreon/share/python/ipaddress.py
- notify/share/python/glpi.py
- notify/share/python/notify.py
- qa-test
- zabbix/bin/zabbix-plugin.py
https://issues.rudder.io/issues/19439
> Fixes #19439: Add python and shell linters on plugins

- scale-out-relay/src/main/scala/com/normation/plugins/scaleoutrelay/DataTypes.scala
- scale-out-relay/src/main/scala/com/normation/plugins/scaleoutrelay/ScaleOutRelayPluginDef.scala
- scale-out-relay/src/main/scala/com/normation/plugins/scaleoutrelay/ScaleOutRelayService.scala
- scale-out-relay/src/main/scala/com/normation/plugins/scaleoutrelay/api/ScaleOutRelayApi.scala
https://issues.rudder.io/issues/19577
> Fixes #19577: Adapt scale-out-relay to rudder 7 system techniques

- main-build.conf
- scale-out-relay/build.conf
- scale-out-relay/src/main/scala/com/normation/plugins/scaleoutrelay/ScaleOutRelayService.scala
https://issues.rudder.io/issues/19637
> Fixes #19637: Make plugin build with 7.0 branch

- scale-out-relay/src/main/scala/com/normation/plugins/scaleoutrelay/ScaleOutRelayService.scala
- scale-out-relay/src/main/scala/com/normation/plugins/scaleoutrelay/api/ScaleOutRelayApi.scala
https://issues.rudder.io/issues/19641
See in combination with: https://issues.rudder.io/issues/19642
> Fixes #19641: Add demote API and end adaptation to rudder 7.0

- create-node-api/build.conf
- create-node-api/src/main/scala/com/normation/plugins/createnodeapi/CreateNodeApi.scala
- create-node-api/src/main/scala/com/normation/plugins/createnodeapi/DataTypes.scala
https://issues.rudder.io/issues/19644
> Fixes #19644: Make plugin create node API build with Rudder 7.0

- auth-backends/src/main/scala/com/normation/plugins/authbackends/api/AuthBackendsApi.scala
- branding/src/main/scala/com/normation/rudder/rest/BrandingApiSchema.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/api/ChangeRequestApi.scala
- datasources/src/main/scala/com/normation/plugins/datasources/api/DataSourceApi.scala
- user-management/src/main/scala/com/normation/plugins/usermanagement/api/UserManagementApi.scala
https://issues.rudder.io/issues/19693
> Fixes #19693: Missing dataContainer in endpoint definition

- branding/src/main/scala/com/normation/plugins/branding/BrandingConfService.scala
https://issues.rudder.io/issues/19698
> Fixes #19698: First start with branding plugin fails

- openscap/src/main/scala/com/normation/plugins/openscappolicies/api/OpenScapApi.scala
- openscap/src/main/scala/com/normation/plugins/openscappolicies/services/OpenScapReportReader.scala
https://issues.rudder.io/issues/19702
> Fixes #19702: openscap doesn't build for 7.0

- change-validation/src/main/scala/bootstrap/rudder/plugin/ChangeValidationConf.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/ChangeRequestJdbcRepository.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/ChangeRequestRepository.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/ValidationNeeded.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/api/SupervisedTargetsApi.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/api/ValidatedUserApi.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/snippet/ChangeRequestChangesForm.scala
- change-validation/src/test/scala/com/normation/plugins/changevalidation/TestEmailService.scala
https://issues.rudder.io/issues/19701
> Fixes #19701: Change-validation not building anymore in 7.0

- node-external-reports/src/main/scala/com/normation/plugins/nodeexternalreports/service/ReadExternalReports.scala
https://issues.rudder.io/issues/19705
> Fixes #19705: make plugin works in 7.0

- datasources/src/main/scala/com/normation/plugins/datasources/DataTypes.scala
- datasources/src/main/scala/com/normation/plugins/datasources/QueryService.scala
- datasources/src/main/scala/com/normation/plugins/datasources/Repository.scala
- datasources/src/main/scala/com/normation/plugins/datasources/Serialization.scala
- datasources/src/main/scala/com/normation/plugins/datasources/UpdateHttpDataset.scala
- datasources/src/main/scala/com/normation/plugins/datasources/api/DataSourceApiImpl.scala
- datasources/src/test/scala/com/normation/plugins/datasources/JsonPathTest.scala
- datasources/src/test/scala/com/normation/plugins/datasources/UpdateHttpDatasetTest.scala
- datasources/src/test/scala/com/normation/plugins/datasources/api/RestDataSourceTest.scala
https://issues.rudder.io/issues/19700
> Fixes #19700: Datasource not building anymore in 7.0

- scale-out-relay/src/main/resources/server-node-to-relay
https://issues.rudder.io/issues/19777
> Fixes #19777: error when promoting node to relay

- scale-out-relay/src/main/scala/com/normation/plugins/scaleoutrelay/ScaleOutRelayService.scala
https://issues.rudder.io/issues/19785
> Fixes #19785: Allowed networks are not init for the Relay when doing node-to-relay

- scale-out-relay/src/main/resources/server-node-to-relay
https://issues.rudder.io/issues/19814
> Fixes #19814: Node to relay misses token for reload techniques

- scale-out-relay/src/main/resources/server-node-to-relay
https://issues.rudder.io/issues/19824
> Fixes #19824: Wrong URL to reload policies

- datasources/build.conf
- datasources/src/main/scala/com/normation/plugins/datasources/QueryService.scala
- datasources/src/main/scala/com/normation/plugins/datasources/Repository.scala
- datasources/src/main/scala/com/normation/plugins/datasources/Scheduler.scala
- datasources/src/main/scala/com/normation/plugins/datasources/Serialization.scala
- datasources/src/main/scala/com/normation/plugins/datasources/api/DataSourceApiImpl.scala
- datasources/src/test/resources/configuration-repository/techniques/ncf_techniques/Create_file/1.0/metadata.xml
- datasources/src/test/scala/com/normation/plugins/datasources/UpdateHttpDatasetTest.scala
https://issues.rudder.io/issues/19859
> Fixes #19859: Fix typos in datasources plugins

- node-external-reports/src/main/scala/com/normation/plugins/nodeexternalreports/extension/CreateNodeDetailsExtension.scala
https://issues.rudder.io/issues/17733
> Fixes #17733: Security/Monitoring report from external node reports appears on "System status" tab

- datasources/src/test/scala/com/normation/plugins/datasources/UpdateHttpDatasetTest.scala
https://issues.rudder.io/issues/19917
> Fixes #19917: Missing implementation of method in test 

- Makefile
- main-build.conf
- makefiles/common-scala-plugin.mk
- makefiles/common.mk
- makefiles/global-vars.mk
- makefiles/make-plugins-common.mk
https://issues.rudder.io/issues/19905
> Fixes #19905: Evolve plugin build to support a separate branching scheme in 7.0.0

- scale-out-relay/src/main/scala/com/normation/plugins/scaleoutrelay/ScaleOutRelayService.scala
https://issues.rudder.io/issues/19928
> Fixes #19928: Remove warning about unit expression

- change-validation/src/main/scala/com/normation/plugins/changevalidation/ValidatedUserJdbcRepository.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/snippet/ChangeRequestChangesForm.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/snippet/ChangeRequestDetails.scala
https://issues.rudder.io/issues/19909
> Fixes #19909: Bad use of toString in place of serialize in change-validation

- openscap/pom-template.xml
https://issues.rudder.io/issues/19958
> Fixes #19958: stack trace when openscap plugin loads

- change-validation/src/main/scala/com/normation/plugins/changevalidation/api/ChangeRequestApi.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/api/SupervisedTargetsApi.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/api/ValidatedUserApi.scala
- create-node-api/src/main/scala/com/normation/plugins/createnodeapi/CreateNodeApi.scala
- datasources/src/main/scala/com/normation/plugins/datasources/api/DataSourceApiImpl.scala
https://issues.rudder.io/issues/20040
> Fixes #20040: error at start of change validation plugin, datasource & create-node-api in 7.0

- api-authorizations/src/main/scala/com/normation/plugins/apiauthorizations/UserTokenApiDefinition.scala
https://issues.rudder.io/issues/20046
> Fixes #29946: Make api authorization compile

- main-build.conf
- plugins-common-private/pom-template.xml
https://issues.rudder.io/issues/20059
> Fixes #20059: Update rudder-plugins private lib to understand new license format

- create-node-api/README.adoc
- create-node-api/src/main/resources/template/CreateNodeApiManagement.html
https://issues.rudder.io/issues/20055
> Fixes #20055: URL in example is invalid

- scale-out-relay/src/main/resources/server-node-to-relay
https://issues.rudder.io/issues/20135
> Fixes #20135: Missing -X POST in request to reload techniques in node-to-relay

- openscap/configuration/techniques/plugin_openscap_report.json
- openscap/packaging/postinst
https://issues.rudder.io/issues/20238
> Fixes #20238: cannot install openscap plugin in rudder 7.0

- openscap/configuration/techniques/plugin_openscap_report.json
https://issues.rudder.io/issues/20406
> Fixes #20406: parent ticket didn't solve the issue

- plugins-common/pom-template.xml
https://issues.rudder.io/issues/20514
> Fixes #20514: Copy main-build.conf into plugin jar

- centreon/README.adoc
- centreon/bin/centreon-plugin
- centreon/packaging/postinst
- centreon/share/python/centreonapi/centreon.py
- centreon/share/python/centreonapi/webservice/__init__.py
https://issues.rudder.io/issues/20527
> Fixes #20527: Allow to have non verified connection to centreon server, and improve documentation

- openscap/src/main/scala/com/normation/plugins/openscappolicies/extension/OpenScapNodeDetailsExtension.scala
https://issues.rudder.io/issues/19703
> Fixes #19703: openscap display is broken in 7.0

- openscap/pom-template.xml
https://issues.rudder.io/issues/20447
> Fixes #20447: 

- ansible-policies/configuration/techniques/ansible_policies.json
- ansible-policies/packaging/postinst
- openscap/packaging/postinst
https://issues.rudder.io/issues/20575
> Fixes #20575: Port technique to 7.0 techniques API

- auth-backends/README.adoc
https://issues.rudder.io/issues/20613
> Fixes #20613: Document ldaps needs certificate added in jvm keystore

- cis/Makefile.plugin
- cis/packaging/postinst
https://issues.rudder.io/issues/20650
> Fixes #20650: GM should be reloaded before importing techniques

- scale-out-relay/Makefile
- scale-out-relay/packaging/postinst
- scale-out-relay/src/main/resources/server-relay-to-node
https://issues.rudder.io/issues/20665
> Fixes #20665: Demote relay rudder server command

- auth-backends/README.adoc
https://issues.rudder.io/issues/20699
> Fixes #20699: Duplicate "import" in certificate command for jvm keystore

- plugins-common/pom-template.xml
https://issues.rudder.io/issues/20730
> Fixes #20730: Missing some rudder provided dependencies for plugins in 7.0

- vault/share/plugins/vault/30_generic_methods/variable_from_vault.cf
https://issues.rudder.io/issues/20760
> Fixes #20760: Plugin dedicated method does not follow the new 7.0 ressource guideline

- datasources/src/test/scala/com/normation/plugins/datasources/UpdateHttpDatasetTest.scala
https://issues.rudder.io/issues/20813
> Fixes #20813: tests broken with because of new method in NodeInfoService

- change-validation/src/main/scala/com/normation/plugins/changevalidation/ChangeValidationPluginDef.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/api/ChangeRequestApi.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/comet/WorkflowInformation.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/snippet/ChangeRequestDetails.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/snippet/ChangeRequestEditForm.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/snippet/ChangeRequestManagement.scala
https://issues.rudder.io/issues/20735
> Fixes #20735: Counterpart of 20734: update import for RudderUserDetails

- api-authorizations/src/main/elm/sources/ApiAuthorizations.elm
- api-authorizations/src/main/resources/toserve/apiauthorizations/media.css
- api-authorizations/src/main/scala/com/normation/plugins/apiauthorizations/ApiAccountsExtension.scala
https://issues.rudder.io/issues/20817
> Fixes #20817: Make the API authorization plugin work with the new API accounts page

- datasources/src/main/scala/com/normation/plugins/datasources/DataSourcesPluginDef.scala
https://issues.rudder.io/issues/20927
> Fixes #20927: Move the plugin entry to the Node management menu

- change-validation/src/main/scala/com/normation/plugins/changevalidation/ChangeValidationPluginDef.scala
https://issues.rudder.io/issues/20935
> Fixes #20935: Move the Change validation plugin entry to the Administration menu

- user-management/src/main/scala/com/normation/plugins/usermanagement/UserManagementPluginDef.scala
https://issues.rudder.io/issues/20934
> Fixes #20934: Move the User management plugin entry to the Administration menu

- branding/src/main/scala/com/normation/plugins/branding/BrandingPluginDef.scala
https://issues.rudder.io/issues/20932
> Fixes #20932: Move the Branding plugin entry to the Utilities menu

- node-external-reports/src/main/scala/com/normation/plugins/nodeexternalreports/NodeExternalReportPluginDef.scala
https://issues.rudder.io/issues/20930
> Fixes #20930: Move the Node external reports plugin entry to the Node management menu

- notify/packaging/metadata
- notify/packaging/postinst
- notify/share/python/log_tail.py
- notify/share/python/notify.py
- notify/share/python/notifyd.py
https://issues.rudder.io/issues/20967
> Fixes #20967: Notifyd doesn't work with python3

- auth-backends/src/main/scala/bootstrap/rudder/plugin/AuthBackendsConf.scala
https://issues.rudder.io/issues/20997
The 3 following cases are now working correctly:
- when oicd/oauth is not configured, then login snippet is not registered and spring security are not created, 
- when oicd/oauth is configured in property file by properties are missing, we have the error message on login page, 
- when everything is correctly configured, no error message (and oidc auth works). 
In all cases, fallback authentication was working. 
From a tech point of view, it's a bit ugly, because we don't have our hand on what is the exact init graph that spring uses, and we don't want to have to change things in rudder core, and we have plugins which complicated things. So we just read properties file also in the plugin just to know if the user want oidc/oauth, and if not, we don't …
> Fixes #20997: Incorrect error of missing oauth config when the backend is disabled 

- branding/src/main/scala/com/normation/plugins/branding/BrandingConfService.scala
https://issues.rudder.io/issues/20962
> Fixes #20962: Change the default background colour of the bar to make it more visible

- api-authorizations/src/main/elm/sources/ApiAuthorizations.elm
- api-authorizations/src/main/resources/toserve/apiauthorizations/media.css
https://issues.rudder.io/issues/20859
Replacing previous PR: https://github.com/Normation/rudder-plugins/pull/450
> Fixes #20859: Prevent acl categories to fold when we click on the All or None buttons

- datasources/src/main/resources/template/dataSourceManagement.html
- datasources/src/main/resources/toserve/datasources/rudder-datasources.css
- datasources/src/main/resources/toserve/datasources/rudder-datasources.js
https://issues.rudder.io/issues/20992
> Fixes #20992: Improve the integration of the plugin in the 7.0 interface

- openscap/packaging/postinst
https://issues.rudder.io/issues/21006
> Fixes #21006: Plugin can not be installed in 7.0.2

- Jenkinsfile
- ansible-policies/packaging/postinst
- ansible-policies/packaging/prerm
- api-authorizations/packaging/postinst
- auth-backends/packaging/postinst
- branding/packaging/postinst
- change-validation/packaging/postinst
- cis/packaging/postinst
- cis/packaging/prerm
- create-node-api/packaging/postinst
- datasources/packaging/postinst
- glpi/packaging/postinst
- helloworld/packaging/postinst
- node-external-reports/packaging/postinst
- notify/packaging/postinst
- openscap/packaging/postinst
- openscap/packaging/prerm
- qa-test
- scale-out-relay/packaging/postinst
- user-management/packaging/postinst
- zabbix/packaging/postinst
https://issues.rudder.io/issues/21008
> Fixes #21008: Plugins package scripts should always exit on error

- auth-backends/src/main/scala/com/normation/plugins/authbackends/snippet/Oauth2LoginBanner.scala
https://issues.rudder.io/issues/21017
> Fixes #21017: Login form is not update in 7.0

- auth-backends/pom-template.xml
- auth-backends/src/main/scala/bootstrap/rudder/plugin/AuthBackendsConf.scala
https://issues.rudder.io/issues/21024
> Fixes #21024: Oauth login error are not logged nor displayed on rudder login screen

- auth-backends/pom-template.xml
- auth-backends/src/main/scala/bootstrap/rudder/plugin/AuthBackendsConf.scala
https://issues.rudder.io/issues/21021
> Fixes #21021: Bad spring dependency for oauth2 token lib

- change-validation/src/main/elm/sources/View.elm
- change-validation/src/main/resources/template/ChangeValidationManagement.html
- change-validation/src/main/resources/template/changeRequest.html
- change-validation/src/main/resources/template/changeRequests.html
- change-validation/src/main/resources/toserve/changevalidation/ComponentChangeRequest.html
- change-validation/src/main/resources/toserve/changevalidation/change-validation.css
- change-validation/src/main/resources/toserve/changevalidation/change-validation.js
- change-validation/src/main/scala/com/normation/plugins/changevalidation/snippet/ChangeRequestChangesForm.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/snippet/ChangeRequestDetails.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/snippet/ChangeRequestManagement.scala
https://issues.rudder.io/issues/21029
> Fixes #21029: Improve integration of the Change Validation plugin in the 7.0 interface

- auth-backends/pom-template.xml
- auth-backends/src/main/scala/bootstrap/rudder/plugin/AuthBackendsConf.scala
https://issues.rudder.io/issues/21076
> Fixes #21076: Backport 21021 because same NPE happens in 6.2

- helloworld/src/main/scala/bootstrap/rudder/plugin/HelloWorldConf.scala
https://issues.rudder.io/issues/21114
> Fixes #21114: Hello world plugin does not compile anymore

- Jenkinsfile-security
- ci/dep-check.Dockerfile
https://issues.rudder.io/issues/21198
> Fixes #21198: Dockerize dependency-check

- ci/dep-check.Dockerfile
https://issues.rudder.io/issues/21198
> Fixes #21208: Missing make dependancy

- Jenkinsfile-security
https://issues.rudder.io/issues/21209
> Fixes #21209: Dependency check fails

- Jenkinsfile
- Makefile
- ci/plugins.Dockerfile
- makefiles/global-vars.mk
https://issues.rudder.io/issues/21193
> Fixes #21193: Add PR tests for webapp plugins

- api-authorizations/src/main/elm/build.sh
- api-authorizations/src/main/scala/com/normation/plugins/apiauthorizations/UserInformationExtension.scala
- auth-backends/src/main/elm/build.sh
- branding/src/main/elm/build.sh
- change-validation/src/main/elm/build.sh
- user-management/src/main/elm/build.sh
https://issues.rudder.io/issues/21217
> Fixes #21217: Broken build of maven plugins with elm apps after minification

- auth-backends/src/main/scala/bootstrap/rudder/plugin/AuthBackendsConf.scala
- auth-backends/src/main/scala/com/normation/plugins/authbackends/Oauth2Authentication.scala
https://issues.rudder.io/issues/21228
> Fixes #21228: Bad warning about missing config for oauth when oauth backend is not used

- auth-backends/README.adoc
- user-management/README.adoc
https://issues.rudder.io/issues/21250
> Fixes #21250: Add case-sentitivity parameter in user file example

- api-authorizations/src/main/elm/elm.json
- auth-backends/src/main/elm/elm.json
- branding/src/main/elm/elm.json
- change-validation/src/main/elm/elm.json
- user-management/src/main/elm/elm.json
https://issues.rudder.io/issues/21447
> Fixes #21447: 

- datasources/src/test/scala/com/normation/plugins/datasources/UpdateHttpDatasetTest.scala
https://issues.rudder.io/issues/21514
> Fixes #21514: Correct tests in datasources

- scale-out-relay/packaging/postinst
https://issues.rudder.io/issues/21428
> Fixes #21428: output of install of scale out relay is clearly not great

- plugins-common/pom-template.xml
https://issues.rudder.io/issues/21493
> Fixes #21493:  Update bouncycastle for 7.2 - plugins

- Jenkinsfile
https://issues.rudder.io/issues/21540
> Fixes #21540: Force mvn update for building plugins

- Jenkinsfile
https://issues.rudder.io/issues/21543
> Fixes #21543: Pass --update to all maven commands

- plugins-common-private/pom-template.xml
https://issues.rudder.io/issues/21660
> Fixes #21660: Update license-lib version used by plugins to sign them

- Jenkinsfile
https://issues.rudder.io/issues/21819
> Fixes #21819: Disable plugin publication through pipeline for now

- Jenkinsfile
https://issues.rudder.io/issues/21823
> Fixes #21823: Activate tests on plugins

- Jenkinsfile-security
https://issues.rudder.io/issues/21827
> Fixes #21827: Fix plugin dependency check

- Jenkinsfile-security
https://issues.rudder.io/issues/21831
> Fixes #21831: Fix plugin dependency check - lower CVSS limit

- openscap/pom-template.xml
https://issues.rudder.io/issues/21832
> Fixes #21832: 

- openscap/pom-template.xml
https://issues.rudder.io/issues/21838
> Fixes #21838: 

- dependency-check-suppression.xml
https://issues.rudder.io/issues/21841
> Fixes #21841: 

- auth-backends/README.adoc
- auth-backends/src/main/scala/com/normation/plugins/authbackends/Oauth2Authentication.scala
https://issues.rudder.io/issues/21896
> Fixes #21896: Remaingin OAUTH secret in log in trace level

- dependency-check-suppression.xml
https://issues.rudder.io/issues/21907
> Fixes #21907: Ignore reported batik-css CVE

- dependency-check-suppression.xml
https://issues.rudder.io/issues/21908
> Fixes #21908:  Ignore reported batik-util CVE

- auth-backends/pom-template.xml
https://issues.rudder.io/issues/21927
> Fixes #21927: Jackson-databind used in oauth has CVE

- datasources/src/main/resources/template/dataSourceManagement.html
- datasources/src/main/resources/toserve/datasources/rudder-datasources.js
https://issues.rudder.io/issues/21504
> Fixes #21504: Display an error when user try to save without rights

- datasources/src/main/scala/com/normation/plugins/datasources/Serialization.scala
- datasources/src/test/scala/com/normation/plugins/datasources/api/RestDataSourceTest.scala
https://issues.rudder.io/issues/21926
> Fixes #21926: Error when trying to set default value without quotes for 404 error

- auth-backends/README.adoc
https://issues.rudder.io/issues/21987
> Fixes #21987: Document oauth2 common error case

- auth-backends/pom-template.xml
https://issues.rudder.io/issues/21992
> Fixes #21992: New CVE in Jackson-Databind 2.13.4

- plugins-common/pom-template.xml
https://issues.rudder.io/issues/22004
> Fixes #22004: Spotless must not be exec in plugin parent

- plugins-common/pom-template.xml
https://issues.rudder.io/issues/22008
> Fixes #22008: Spotless must not be exec in plugins-common but on children

- glpi/bin/glpi-plugin
https://issues.rudder.io/issues/22057
> Fixes #22057: Unbound variable INV for glpi-plugin send-one command

- dependency-check-suppression.xml
https://issues.rudder.io/issues/22065
> Fixes #22065: Ignore CVE-2022-31690

- dependency-check-suppression.xml
https://issues.rudder.io/issues/22067
> Fixes #22067:  Ignore CVE-2022-31690 - 7.2

- plugins-common/pom-template.xml
https://issues.rudder.io/issues/22090
> Fixes #22090: Datasource broken b/c version of dependencyManagement provided XML lib is not enforced in children projects

- api-authorizations/src/main/elm/elm.json
- auth-backends/src/main/elm/elm.json
- branding/src/main/elm/elm.json
- change-validation/src/main/elm/elm.json
- user-management/src/main/elm/elm.json
https://issues.rudder.io/issues/22052
> Fixes #22052:  Update elm dependencies - plugins

- Jenkinsfile-security
https://issues.rudder.io/issues/22219
> Fixes #22219: Add security check on plugin npm dependencies

- api-authorizations/src/main/.nsprc
- auth-backends/src/main/.nsprc
- branding/src/main/.nsprc
- change-validation/src/main/.nsprc
- plugins-common/.nsprc
- plugins-common/gulpfile.js
- plugins-common/package-lock.json
- plugins-common/package.json
- user-management/src/main/.nsprc
https://issues.rudder.io/issues/22220
> Fixes #22220:  Add security check on plugin npm dependencies - exception

- Jenkinsfile-security
https://issues.rudder.io/issues/22221
> Fixes #22221: Skip npm dependency check on plugins without elm

- plugins-common/gulpfile.js
https://issues.rudder.io/issues/22262
> Fixes #22262: Broken elm build in plugins

- plugins-common/.nsprc
https://issues.rudder.io/issues/22304
> Fixes #22304: Ignore  CVE-2020-28469 in plugins

- plugins-common/.nsprc
https://issues.rudder.io/issues/22321
> Fixes #22321: Ignore DoS in npm plugin dependencies

- plugins-common/.nsprc
https://issues.rudder.io/issues/22323
> Fixes #22323: Ignore DoS in npm plugin dependencies

- change-validation/src/main/scala/bootstrap/rudder/plugin/ChangeValidationConf.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/ValidationNeeded.scala
https://issues.rudder.io/issues/22188
> Fixes #22188: Changes made by validated users still need to be validated

- change-validation/src/main/scala/com/normation/plugins/changevalidation/ValidatedUserJdbcRepository.scala
https://issues.rudder.io/issues/22361
> Fixes #22361: Adapt code to changes from #22206 (custom roles)

- change-validation/src/main/resources/toserve/changevalidation/ComponentChangeRequest.html
- change-validation/src/main/scala/com/normation/plugins/changevalidation/snippet/ChangeRequestDetails.scala
https://issues.rudder.io/issues/22364
> Fixes #22364: Adapt warning message to warn about merge with divergence

- ansible-policies/packaging/postinst
- ansible-policies/packaging/prerm
- api-authorizations/packaging/postinst
- auth-backends/packaging/postinst
- branding/packaging/postinst
- change-validation/packaging/postinst
- cis/packaging/postinst
- cis/packaging/prerm
- create-node-api/packaging/postinst
- datasources/packaging/postinst
- glpi/packaging/postinst
- helloworld/packaging/postinst
- node-external-reports/packaging/postinst
- notify/packaging/postinst
- openscap/packaging/postinst
- openscap/packaging/prerm
- qa-test
- scale-out-relay/packaging/postinst
- user-management/packaging/postinst
- zabbix/packaging/postinst
https://issues.rudder.io/issues/22441
> Fixes #22441: secrets are leaking at the install of the plugin

- user-management/src/main/scala/com/normation/plugins/usermanagement/api/UserManagementApi.scala
- user-management/src/test/scala/com/normation/plugins/usermanagement/RoleComputationTest.scala
https://issues.rudder.io/issues/22458
> Fixes #22458: Adapt user-management plugin to parseRight (#22457)

- scale-out-relay/README.adoc
https://issues.rudder.io/issues/22488
> Fixes #22488: Remove outdated docs

- auth-backends/pom-template.xml
https://issues.rudder.io/issues/22533
> Fixes #22533: Upgrade nimbus-jose-jwt to last patch release

- branding/src/main/scala/com/normation/plugins/branding/snippet/CommonBranding.scala
https://issues.rudder.io/issues/22566
> Fixes #22566: Enabling branding plugin top bar causes minor glitches in the interface

- datasources/src/main/scala/com/normation/plugins/datasources/Repository.scala
- datasources/src/main/scala/com/normation/plugins/datasources/Scheduler.scala
- datasources/src/test/scala/com/normation/plugins/datasources/UpdateHttpDatasetTest.scala
https://issues.rudder.io/issues/12752
The problem was an non evaluated `RudderIO` on save :/
I've added a test to check for that now.
> Fixes #12752: Datasources plugin scheduler problems after updating/deleting a datasource

- ansible-policies/README.adoc
https://issues.rudder.io/issues/22395
> Fixes #22395: Link to ansible plugin in ansible policies in docs 7.2 leads to doc 5.0

- auth-backends/README.adoc
- auth-backends/src/main/resources/applicationContext-security-auth-ldap.xml
https://issues.rudder.io/issues/22158
> Fixes #22158: LDAP auth backend should deref link to allows finding user in remote directory

- user-management/src/main/elm/sources/View.elm
- user-management/src/main/resources/toserve/usermanagement/user-management.css
https://issues.rudder.io/issues/22697
> Fixes #22697: save button is "SaveSave"

- datasources/src/test/scala/com/normation/plugins/datasources/UpdateHttpDatasetTest.scala
https://issues.rudder.io/issues/22770
> Fixes #22770: Reflect changes of 7.3 backport to datasource plugin

- datasources/src/main/scala/com/normation/plugins/datasources/Scheduler.scala
- datasources/src/test/scala/com/normation/plugins/datasources/UpdateHttpDatasetTest.scala
https://issues.rudder.io/issues/22771
> Fixes #22771: Still some chances to datasource for 7.3 backport 

- change-validation/src/main/scala/bootstrap/rudder/plugin/ChangeValidationConf.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/ValidationNeeded.scala
https://issues.rudder.io/issues/22422
supervised and unsupervised targets were inverted
> Fixes #22422: port of ticket 22188 in 7.2

- change-validation/src/main/scala/com/normation/plugins/changevalidation/snippet/ChangeRequestChangesForm.scala
https://issues.rudder.io/issues/22803
> Fixes #22803: Replace Query trait in plugins

- auth-backends/src/main/elm/elm.json
- auth-backends/src/main/elm/sources/AuthBackends.elm
- branding/src/main/elm/elm.json
- branding/src/main/elm/sources/ApiCall.elm
- branding/src/main/elm/sources/View.elm
- ci/plugins.Dockerfile
- user-management/src/main/elm/elm.json
- user-management/src/main/elm/sources/ApiCalls.elm
- user-management/src/main/elm/sources/Init.elm
https://issues.rudder.io/issues/22883
> Fixes #22883: Update elm dependencies

- openscap/packaging/postinst
- openscap/packaging/prerm
https://issues.rudder.io/issues/22688
> Fixes #22688: Error at upgrade from 7.2 to 7.3

- auth-backends/pom-template.xml
- change-validation/pom-template.xml
- plugins-common/pom-template.xml
https://issues.rudder.io/issues/22806
> Fixes #22806: Update plugin dependencies for 8.0

- ci/dep-check.Dockerfile
- ci/plugins.Dockerfile
- ci/pylint.Dockerfile
- ci/shellcheck.Dockerfile
- ci/typos.Dockerfile
https://issues.rudder.io/issues/22917
> Fixes #22917: add label to rudder-plugin docker images

- glpi/README.adoc
- glpi/bin/glpi-plugin
- glpi/packaging/postinst
https://issues.rudder.io/issues/22893
> Fixes #22893: Allow to patch fqdn when sending inventories to glpi

- auth-backends/src/main/scala/bootstrap/rudder/plugin/AuthBackendsConf.scala
https://issues.rudder.io/issues/23022
> Fixes #23022: Better debug logs for OIDC provided roles

- datasources/src/main/scala/bootstrap/rudder/plugin/DataSourcesConf.scala
https://issues.rudder.io/issues/23061
Use the new "new node hook" datasctrucre brought in by https://github.com/Normation/rudder/pull/4869
API exposed with https://github.com/Normation/rudder/pull/4892
> Fixes #23061: Compilation error following change in newNodeManager

- glpi/packaging/postinst
https://issues.rudder.io/issues/22781
> Fixes #22781: The cron never runs

- datasources/src/main/scala/com/normation/plugins/datasources/Scheduler.scala
https://issues.rudder.io/issues/23141
> Fixes #23141: Schedule not displayed correctly in logs

- api-authorizations/src/main/resources/toserve/apiauthorizations/media.css
- auth-backends/src/main/resources/toserve/authbackends/auth-backends.css
- branding/src/main/resources/toserve/branding/media.css
- change-validation/src/main/resources/toserve/changevalidation/change-validation.css
- openscap/src/main/resources/template/OpenScapPoliciesManagement.html
- user-management/src/main/resources/toserve/usermanagement/user-management.css
https://issues.rudder.io/issues/23270
> Fixes #23270: Use consistent fonts in Rudder interface - plugins

- branding/LICENSE
- branding/LICENSE_EXCEPTION
https://issues.rudder.io/issues/23272
> Fixes #23272: Missing license information

- main-build.conf
https://issues.rudder.io/issues/23282
> Fixes #23282: Wrong version in 8.0

- auth-backends/README.adoc
https://issues.rudder.io/issues/23321
> Fixes #23321: Add example log trace for LDAP connection errors

- user-management/src/main/scala/com/normation/plugins/usermanagement/UserManagementService.scala
https://issues.rudder.io/issues/23315
Propagate changes from https://github.com/Normation/rudder/pull/4990
> Fixes #23315: Replicate change in Rights from rudder-core

- auth-backends/pom-template.xml
https://issues.rudder.io/issues/23371
> Fixes #23371: Update scala dependencies 

- Jenkinsfile
- Jenkinsfile-security
- openscap/pom-template.xml
https://issues.rudder.io/issues/23423
> Fixes #23423: 

- user-management/src/main/scala/com/normation/plugins/usermanagement/UserManagementPluginDef.scala
https://issues.rudder.io/issues/23432
> Fixes #23432: User management menu is shown with read rights but need write ones

- openscap/src/main/scala/com/normation/plugins/openscappolicies/OpenscapPoliciesPluginDef.scala
https://issues.rudder.io/issues/23696
> Fixes #23696: Remove 8.0 openscap unused imports

- auth-backends/pom-template.xml
- auth-backends/src/main/scala/com/normation/plugins/authbackends/Oauth2Authentication.scala
- change-validation/pom-template.xml
- openscap/pom-template.xml
https://issues.rudder.io/issues/23762
> Fixes #23762: Update rudder-plugins dependencies

- auth-backends/src/main/scala/com/normation/plugins/authbackends/Oauth2Authentication.scala
https://issues.rudder.io/issues/23768
> Fixes #23768: Remove Password authentication for OAuth2

- datasources/src/main/scala/bootstrap/rudder/plugin/DataSourcesConf.scala
- datasources/src/test/scala/com/normation/plugins/datasources/UpdateHttpDatasetTest.scala
https://issues.rudder.io/issues/23752
> Fixes #23752: Implication of CoreNodeFactRepository to plugins

- plugins-common/package-lock.json
- plugins-common/package.json
https://issues.rudder.io/issues/23829
> Fixes #23829: Update rudder-plugins front-end dependencies

- branding/src/test/resources/branding_api/api_branding.yml
- branding/src/test/scala/com/normation/plugins/branding/api/BrandingApiTest.scala
https://issues.rudder.io/issues/23858
Just typo and a little simplification
> Fixes #23858: Error in test (typo)

- auth-backends/src/main/scala/bootstrap/rudder/plugin/AuthBackendsConf.scala
- datasources/src/test/scala/com/normation/plugins/datasources/UpdateHttpDatasetTest.scala
- scale-out-relay/src/test/scala/com/normation/plugins/scaleoutrelay/MockServices.scala
- scale-out-relay/src/test/scala/com/normation/plugins/scaleoutrelay/api/ScaleOutRelayApiTest.scala
https://issues.rudder.io/issues/23857
Just adapt a few places to match changes in https://github.com/Normation/rudder/pull/5229
> Fixes #23857: Impact of API change for tenants on plugins

- datasources/src/main/elm/sources/View.elm
- datasources/src/main/resources/toserve/datasources/rudder-datasources.css
https://issues.rudder.io/issues/23900
> Fixes #23900: Rename the "Add data source" button to "Create" in 8.0

- datasources/src/main/resources/template/dataSourceManagement.html
https://issues.rudder.io/issues/23875
> Fixes #23875: Rename the "Add data source" button to "Create"

- change-validation/src/main/scala/com/normation/plugins/changevalidation/DataTypes.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/api/ChangeRequestApi.scala
- datasources/src/main/scala/com/normation/plugins/datasources/Serialization.scala
https://issues.rudder.io/issues/23984
> Fixes #23984: Change sequence/traverse in plugins too

- auth-backends/src/main/scala/bootstrap/rudder/plugin/AuthBackendsConf.scala
https://issues.rudder.io/issues/23986
> Fixes #23986: Remove warning about missing ()

- change-validation/src/main/scala/com/normation/plugins/changevalidation/ChangeValidationPluginDef.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/WorkflowService.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/api/ChangeRequestApi.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/comet/WorkflowInformation.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/snippet/ChangeRequestDetails.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/snippet/ChangeRequestEditForm.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/snippet/ChangeRequestManagement.scala
- change-validation/src/test/scala/com/normation/plugins/changevalidation/ValidatedUserJdbcRepositoryTest.scala
https://issues.rudder.io/issues/23991
Just a couple imports
> Fixes #23991: Missing some CurrentUser changes

- api-authorizations/src/test/scala/com/normation/plugins/apiauthorizations/api/UserApiTest.scala
- user-management/src/main/scala/bootstrap/rudder/plugin/UserManagementConf.scala
- user-management/src/main/scala/com/normation/plugins/usermanagement/api/UserManagementApi.scala
https://issues.rudder.io/issues/23994
Same errors, changing imports and adding more params
> Fixes #23994: Some more missing change for user 

- openscap/pom-template.xml
https://issues.rudder.io/issues/24003
> Fixes #24003: Update antisamy for security issue (CVE-2023-43643)

- api-authorizations/src/main/scala-templates/limited/com/normation/plugins/apiauthorizations/EnablePluginImpl.scala
- auth-backends/src/main/scala-templates/limited/com/normation/plugins/authbackends/EnablePluginImpl.scala
- branding/src/main/scala-templates/limited/com/normation/plugins/branding/EnablePluginImpl.scala
- change-validation/src/main/scala-templates/limited/com/normation/plugins/changevalidation/EnablePluginImpl.scala
- datasources/src/main/scala-templates/limited/com/normation/plugins/datasources/EnablePluginImpl.scala
- node-external-reports/src/main/scala-templates/limited/com/normation/plugins/nodeexternalreports/EnablePluginImpl.scala
- scale-out-relay/src/main/scala-templates/limited/com/normation/plugins/scaleoutrelay/EnablePluginImpl.scala
- src/main/g8/src/main/scala-templates/limited/com/normation/plugins/$plugin_pkg$/EnablePluginImpl.scala
- user-management/src/main/scala-templates/limited/com/normation/plugins/usermanagement/EnablePluginImpl.scala
https://issues.rudder.io/issues/24029
> Fixes #24029: license plugin checks are not building since node facts changes

- openscap/Makefile
https://issues.rudder.io/issues/24037
> Fixes #24037: Invalid makefile because prerm was removed

- makefiles/global-vars.mk
- openscap/Makefile
https://issues.rudder.io/issues/24044
> Fixes #24044: Use correct rudderc version to build openscap technique

- Jenkinsfile-release
https://issues.rudder.io/issues/24046
> Fixes #24046: Add new Jenkinsfile-release

- change-validation/src/main/scala/com/normation/plugins/changevalidation/WorkflowService.scala
https://issues.rudder.io/issues/24111
> Fixes #24111: Pending deployment action are completely messed up

- datasources/src/main/elm/sources/APICalls.elm
- datasources/src/main/elm/sources/DataSourceForm.elm
- datasources/src/main/elm/sources/JsonDecoder.elm
- datasources/src/main/elm/sources/Messages.elm
- datasources/src/main/elm/sources/Port.elm
- datasources/src/main/elm/sources/Update.elm
- datasources/src/main/elm/sources/View.elm
- datasources/src/main/resources/template/dataSourceManagement.html
https://issues.rudder.io/issues/24154
> Fixes #24154: The UI is barely functional

- datasources/src/main/elm/sources/View.elm
https://issues.rudder.io/issues/24161
> Fixes #24161: Missing write check on delete button

- datasources/src/main/package-lock.json
- datasources/src/main/package.json
https://issues.rudder.io/issues/24163
> Fixes #24163: gulp-sass missing for datasources

- datasources/src/main/package-lock.json
- datasources/src/main/package.json
- datasources/src/main/style/rudder-datasources.css
https://issues.rudder.io/issues/24167
Missing also sass and gulp-sourcemap, plus there was an error in the sass css (missing font size)
> Fixes #24167: Actually other gulp plugins are missing

- auth-backends/src/main/scala/bootstrap/rudder/plugin/AuthBackendsConf.scala
https://issues.rudder.io/issues/24189
We copied only the `roles` to override the user details from `Rudder` : https://github.com/Normation/rudder/blob/backports/7.3.12/24146/webapp/sources/rudder/rudder-web/src/main/scala/bootstrap/liftweb/AppConfigAuth.scala#L386.
But we also need to replace the `ApiAuthorization.None` by authorizations computed from the set of roles
> Fixes #24189: No API right with aliased roles

- user-management/src/main/scala/com/normation/plugins/usermanagement/DataTypes.scala
https://issues.rudder.io/issues/24192
> Fixes #24192: Fix documentation typo for usermanagement JsonUser

- api-authorizations/src/main/elm/sources/ApiAuthorizations.elm
- api-authorizations/src/main/style/media.css
https://issues.rudder.io/issues/24214
Result :
> Fixes #24214: Fix UI issues caused by bootstrap update in api-authorization plugin

- auth-backends/src/main/scala/bootstrap/rudder/plugin/AuthBackendsConf.scala
https://issues.rudder.io/issues/24202
This is a port of https://github.com/Normation/rudder-plugins/pull/655 to 7.3 branch
> Fixes #24202: No API right with OIDC provided roles

- datasources/src/main/elm/sources/DataSourceForm.elm
- datasources/src/main/elm/sources/Update.elm
- datasources/src/main/elm/sources/View.elm
- datasources/src/main/resources/template/dataSourceManagement.html
- datasources/src/main/scala/com/normation/plugins/datasources/QueryService.scala
- datasources/src/main/style/rudder-datasources.css
https://issues.rudder.io/issues/24221
Result :
> Fixes #24221: Fix UI issues caused by bootstrap update in datasources plugin

- change-validation/src/main/resources/template/ChangeValidationManagement.html
https://issues.rudder.io/issues/24249
> Fixes #24249: Fix typo in HTML of the setting to validate all changes

- auth-backends/src/main/scala/bootstrap/rudder/plugin/AuthBackendsConf.scala
https://issues.rudder.io/issues/24247
> Fixes #24247: Authentication protocol names should be normalized to lowercase

- glpi/etc/hooks.d/node-post-deletion/20-clean-inventories
https://issues.rudder.io/issues/22731
> Fixes #22731: Rudder-plugin-glpi sends inventory of node that no longer exists

- change-validation/README.adoc
https://issues.rudder.io/issues/24293
> Fixes #24293: change validation plugin documentation refers to Rudder 5.0

- main-build.conf
- makefiles/global-vars.mk
https://issues.rudder.io/issues/24364
> Fixes #24364: Remove RPKG variable that creates plugin with wrong version

- datasources/Makefile
- node-external-reports/Makefile
- scale-out-relay/Makefile
- user-management/Makefile
https://issues.rudder.io/issues/24368
> Fixes #24368: Remove duplicated files from some plugins

- user-management/Makefile
https://issues.rudder.io/issues/24410
> Fixes #24410: Correct user-management build

- user-management/Makefile
https://issues.rudder.io/issues/24438
> Fixes #24438: Fix user-management build failure when requiring schema.sql file

- auth-backends/pom-template.xml
https://issues.rudder.io/issues/24469
Tested an OIDC log-in, works without noticeable change.
> Fixes #24469: Update JWT lib for CVE-2023-52428

- openscap/src/main/scala/com/normation/plugins/openscappolicies/extension/OpenScapNodeDetailsExtension.scala
https://issues.rudder.io/issues/24357
> Fixes #24357: OpenSCAP tabs is not aligned in page node

- user-management/src/main/elm/sources/View.elm
https://issues.rudder.io/issues/24461
> Fixes #24461: Missleading placeholder for empty field value

- ansible-policies/packaging/metadata
- node-external-reports/packaging/metadata
https://issues.rudder.io/issues/24525
> Fixes #24525: Add description field to plugin metadata

- change-validation/Makefile
https://issues.rudder.io/issues/24545
> Fixes #24545: Remove duplicated files

- auth-backends/src/main/scala/com/normation/plugins/authbackends/DataTypes.scala
- auth-backends/src/main/scala/com/normation/plugins/authbackends/api/AuthBackendsApi.scala
- branding/src/main/scala/com/normation/rudder/rest/BrandingApiSchema.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/api/ChangeRequestApi.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/api/SupervisedTargetsApi.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/api/ValidatedUserApi.scala
- datasources/src/main/scala/com/normation/plugins/datasources/DataTypes.scala
- datasources/src/main/scala/com/normation/plugins/datasources/api/DataSourceApi.scala
- openscap/src/main/scala/com/normation/plugins/openscappolicies/api/OpenScapApi.scala
- plugins-common/pom-template.xml
- scale-out-relay/src/main/scala/com/normation/plugins/scaleoutrelay/api/ScaleOutRelayApi.scala
- user-management/src/main/scala/com/normation/plugins/usermanagement/api/UserManagementApi.scala
https://issues.rudder.io/issues/24555
> Fixes #24555:  Use enumeratum in place of sealarate for scala3 migration - public plugins

- scale-out-relay/src/main/scala/bootstrap/rudder/plugin/ScaleOutRelayConf.scala
- scale-out-relay/src/main/scala/com/normation/plugins/scaleoutrelay/ScaleOutRelayService.scala
- scale-out-relay/src/main/scala/com/normation/plugins/scaleoutrelay/api/ScaleOutRelayApi.scala
- scale-out-relay/src/test/scala/com/normation/plugins/scaleoutrelay/MockServices.scala
- scale-out-relay/src/test/scala/com/normation/plugins/scaleoutrelay/api/ScaleOutRelayApiTest.scala
https://issues.rudder.io/issues/24417
> Fixes #24417: Promote a node to relay command failed with parsing message error

- change-validation/src/test/resources/changevalidation_api/api_supervisedtargets.yml
- change-validation/src/test/scala/bootstrap/rudder/plugin/MigrateSupervisedGroupsTests.scala
- change-validation/src/test/scala/com/normation/plugins/changevalidation/MockServices.scala
- change-validation/src/test/scala/com/normation/plugins/changevalidation/api/SupervisedTargetsApiTest.scala
- datasources/src/test/scala/com/normation/plugins/datasources/UpdateHttpDatasetTest.scala
https://issues.rudder.io/issues/24623
Nothing really interesting, just removing removed methods from trait and moving a group in a subcategory
> Fixes #24623: Several compilation error following change in rudder-core

- user-management/src/main/scala/com/normation/plugins/usermanagement/DataTypes.scala
- user-management/src/main/scala/com/normation/plugins/usermanagement/UserManagementService.scala
https://issues.rudder.io/issues/24690
> Fixes #24690: Editing user roles overrides tenants in rudder-users.xml file 

- Jenkinsfile
https://issues.rudder.io/issues/24747
> Fixes #24747: Openscap nightlies are still in need of a license

- user-management/src/test/scala/com/normation/plugins/usermanagement/api/UserManagementApiTest.scala
https://issues.rudder.io/issues/24791
> Fixes #24791: Change in rudder user details break plugin compilation

- change-validation/src/main/scala/com/normation/plugins/changevalidation/ChangeRequestJson.scala
https://issues.rudder.io/issues/24790
> Fixes #24790: Already defined json encoders break plugin build

- user-management/src/test/scala/com/normation/plugins/usermanagement/MockServices.scala
https://issues.rudder.io/issues/24848
> Fixes #24848: Impact on user management: missing get with new param

- openscap/packaging/postinst
https://issues.rudder.io/issues/24781
> Fixes #24781: OpenSCAP technique doesn't show up in GUI after OpenSCAP plugin installation

- zabbix/bin/zabbix-plugin.py
https://issues.rudder.io/issues/24873
> Fixes #24873: Python lint error in the zabbix plugin

- api-authorizations/src/main/elm/elm.json
- api-authorizations/src/main/elm/review
- auth-backends/src/main/elm/elm.json
- auth-backends/src/main/elm/review
- branding/src/main/elm/elm.json
- branding/src/main/elm/review
- change-validation/src/main/elm/elm.json
- change-validation/src/main/elm/review
- ci/plugins.Dockerfile
- datasources/src/main/elm/elm.json
- datasources/src/main/elm/review
- plugins-common/package-lock.json
- plugins-common/package.json
- plugins-common/pom-template.xml
- plugins-common/review/elm.json
- plugins-common/review/src/ReviewConfig.elm
- user-management/src/main/elm/review
https://issues.rudder.io/issues/24880
> Fixes #24880: Add basic elm-review config - plugins

- openscap/src/main/scala/com/normation/plugins/openscappolicies/api/OpenScapApi.scala
https://issues.rudder.io/issues/24868
> Fixes #24868: User with node read should be able to see open scap report

- zabbix/packaging/postinst
https://issues.rudder.io/issues/19206
Replacing previous PR: https://github.com/Normation/rudder-plugins/pull/367
> Fixes #19206: Missing cron task for application of monitoring templates

- api-authorizations/src/main/scala/com/normation/plugins/apiauthorizations/ApiAccountsExtension.scala
https://issues.rudder.io/issues/24979
The `Accounts` Elm app in Rudder creates a new modal component `modal-account` every time we edit an account, and the modal get deleted from the DOM every time a new account is rendered on the page.
Within the modal DOM element, there is a `<div id="apiauthorization-content"/>` which is a the target of the mounting of the `ApiAuthorizations` Elm app that displays the list of ACLs. 
The problem is that the `ApiAuthorizations` Elm app is no longer mounted, because the modal system has changed and mounting is attempted before the target is available.  
To fix it in the plugin we need to :
* await the modal creation, to guarantee the presence of `<div id="apiauthorization-content"/>`
* do this every time we display an account : we need an Elm app for each …
> Fixes #24979: API accounts cannot be changed when api-authorizations plugin is enabled

- plugins-common/.nsprc
https://issues.rudder.io/issues/24998
> Fixes #24998: Ignore braces DoS in plugins in 7.3

- plugins-common/build.sh
https://issues.rudder.io/issues/25006
Related to https://github.com/Normation/rudder-plugins-private/pull/620
> Fixes #25006: Plugins don't build since gulpfile update

- datasources/src/main/scala/com/normation/plugins/datasources/UpdateHttpDataset.scala
https://issues.rudder.io/issues/25022
> Fixes #25022: Similar black in datasource for 7.3

- ci/plugins.Dockerfile
https://issues.rudder.io/issues/25027
> Fixes #25027: Missing make command in the build process

- ci/plugins.Dockerfile
https://issues.rudder.io/issues/25029
> Fixes #25029: xz-utils not found when building plugins

- ci/plugins.Dockerfile
https://issues.rudder.io/issues/25030
> Fixes #25030: Missing ar command in builds

- plugins-common/review/elm.json
https://issues.rudder.io/issues/25031
> Fixes #25031: Update jfmengels/elm-review lib in datasources

- api-authorizations/src/main/scala/com/normation/plugins/apiauthorizations/ApiAccountsExtension.scala
- auth-backends/src/main/scala/com/normation/plugins/authbackends/snippet/Oauth2LoginBanner.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/snippet/ChangeRequestChangesForm.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/snippet/ChangeRequestDetails.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/snippet/ChangeRequestManagement.scala
https://issues.rudder.io/issues/25065
There is nothing to be escaped at all, really...
> Fixes #25065: 

- scale-out-relay/src/main/scala/com/normation/plugins/scaleoutrelay/DataTypes.scala
https://issues.rudder.io/issues/25134
Changes needed to keep the plugin compiling from [this change from a review request](https://github.com/Normation/rudder/pull/5763/commits/3fcd7e8bf0f58a9b2c5a71a99847bd17a8869408)
> Fixes #25134: Fix scale-out-relay build since change of API in webapp

- change-validation/src/test/scala/com/normation/plugins/changevalidation/api/ChangeRequestApiTest.scala
https://issues.rudder.io/issues/25160
> Fixes #25160: Missing values for VariableSpec in test

- openscap/src/main/scala/com/normation/plugins/openscappolicies/extension/OpenScapNodeDetailsExtension.scala
https://issues.rudder.io/issues/25075
> Fixes #25075: OpenSCAP plugin output displays on *all* node tabs

- auth-backends/README.adoc
https://issues.rudder.io/issues/25221
:sob:
> Fixes #25221: Typo for parameter enableProvisioning in documentation

- auth-backends/README.adoc
https://issues.rudder.io/issues/25280
> Fixes #25280: Clarify that we do not support authorizations in OIDC authentification role in documentation

- user-management/src/main/scala/com/normation/plugins/usermanagement/api/UserManagementApi.scala
- user-management/src/test/scala/com/normation/plugins/usermanagement/MockServices.scala
https://issues.rudder.io/issues/25313
This is both needed to make the plugin compile, and for changes in https://github.com/Normation/rudder/pull/5816
> Fixes #25313: Reload users file when user is disabled or activated in plugin

- user-management/src/test/scala/com/normation/plugins/usermanagement/MockServices.scala
https://issues.rudder.io/issues/25343
> Fixes #25343: Setting existing users with case sensitivity in user management tests

- api-authorizations/pom-template.xml
- auth-backends/pom-template.xml
- auth-backends/src/main/scala/bootstrap/rudder/plugin/AuthBackendsConf.scala
- branding/pom-template.xml
- change-validation/pom-template.xml
- datasources/pom-template.xml
- openscap/pom-template.xml
- plugins-common/pom-template.xml
- scale-out-relay/pom-template.xml
https://issues.rudder.io/issues/25378
Needs https://github.com/Normation/rudder/pull/5843
> Fixes #25378: Update to jetty 11 spring 6  on plugins

- plugins-common/pom-template.xml
https://issues.rudder.io/issues/25392
> Fixes #25392: Typo in pom-template

- change-validation/src/test/resources/changevalidation_api/api_supervisedtargets.yml
https://issues.rudder.io/issues/25397
These categories were added in https://github.com/Normation/rudder/pull/5834 when testing deletion of system groups
> Fixes #25397: Added test groups make change-validation tests fail

- Jenkinsfile
- centreon/etc/hooks.d/node-post-acceptance/centreon-post-acceptance.sh
- centreon/etc/hooks.d/node-pre-deletion/centreon-pre-deletion.sh
- datasources/src/main/scala/com/normation/plugins/datasources/Scheduler.scala
- glpi/etc/hooks.d/node-post-acceptance/glpi-inventory.sh
- plugins-common-private/src/main/scala/com/normation/plugins/ParsePluginLicense.scala
- zabbix/etc/hooks.d/node-post-acceptance/zabbix-post-acceptance.sh
- zabbix/etc/hooks.d/node-pre-deletion/zabbix-pre-deletion.sh
https://issues.rudder.io/issues/25424
> Fixes #25424: Update typo-cli version

- api-authorizations/src/test/resources/authorizations_api/api_users.yml
- change-validation/src/test/resources/changevalidation_api/api_changerequest.yml
https://issues.rudder.io/issues/25425
> Fixes #25425: Repair test in plugins due to change in test data from parent

- Jenkinsfile
- centreon/etc/hooks.d/node-post-acceptance/centreon-post-acceptance.sh
- centreon/etc/hooks.d/node-pre-deletion/centreon-pre-deletion.sh
- datasources/src/main/scala/com/normation/plugins/datasources/Scheduler.scala
- glpi/etc/hooks.d/node-post-acceptance/glpi-inventory.sh
- plugins-common-private/src/main/scala/com/normation/plugins/ParsePluginLicense.scala
- zabbix/etc/hooks.d/node-post-acceptance/zabbix-post-acceptance.sh
- zabbix/etc/hooks.d/node-pre-deletion/zabbix-pre-deletion.sh
https://issues.rudder.io/issues/25460
> Fixes #25460: Bump typos-cli to 1.24.5

- user-management/src/test/scala/com/normation/plugins/usermanagement/MockServices.scala
https://issues.rudder.io/issues/25472
> Fixes #25472: Impact of session invalidation in user-management test on userrepository

- user-management/src/test/scala/com/normation/plugins/usermanagement/MockServices.scala
https://issues.rudder.io/issues/25482
> Fixes #25482: User cleanup configuration impact on user-management

- user-management/src/main/elm/sources/UserManagement.elm
- user-management/src/main/scala/com/normation/plugins/usermanagement/UserManagementService.scala
https://issues.rudder.io/issues/25447
> Fixes #25447: Admin user should have notification that their session is kept until timeout

- auth-backends/src/main/scala/bootstrap/rudder/plugin/AuthBackendsConf.scala
- user-management/src/main/scala/com/normation/plugins/usermanagement/UserManagementService.scala
https://issues.rudder.io/issues/25484
> Fixes #25484: Normalize authentication logs in plugins

- datasources/src/test/scala/com/normation/plugins/datasources/UpdateHttpDatasetTest.scala
https://issues.rudder.io/issues/25497
> Fixes #25497: Datasources tests are failling due to race condition

- plugins-common/.nsprc
https://issues.rudder.io/issues/25558
> Fixes #25558: Ignore DoS in semver npm dependency

- change-validation/src/main/resources/template/ChangeValidationManagement.html
https://issues.rudder.io/issues/25660
> Fixes #25660: Remove use of the clipboardjs library

- api-authorizations/src/main/style/media.css
https://issues.rudder.io/issues/25666
> Fixes #25666: Delete token and create token button are not usable

- auth-backends/src/main/scala/bootstrap/rudder/plugin/AuthBackendsConf.scala
- user-management/src/test/scala/com/normation/plugins/usermanagement/MockServices.scala
https://issues.rudder.io/issues/25685
This fixes the problem of "batch deletion" of current OIDC users using the changes from https://github.com/Normation/rudder/pull/5951
> Fixes #25685: OIDC users need to add individual users in plugins

- openscap/packaging/postinst
- scale-out-relay/src/main/resources/server-node-to-relay
- scale-out-relay/src/main/resources/server-relay-to-node
https://issues.rudder.io/issues/25805
> Fixes #25805: Use the system token header file in plugin scripts

- scale-out-relay/src/main/resources/server-node-to-relay
- scale-out-relay/src/main/resources/server-relay-to-node
https://issues.rudder.io/issues/25831
> Fixes #25831: Broken Token in commands

- auth-backends/src/main/scala-templates/limited/com/normation/plugins/authbackends/EnablePluginImpl.scala
https://issues.rudder.io/issues/25874
> Fixes #25874: Remove NodeInfoService impact on auth-backends

- openscap/README.adoc
- openscap/packaging/metadata
https://issues.rudder.io/issues/25891
> Fixes #25891: Remove the api-client dependency from OpenSCAP plugin

- change-validation/src/main/scala/com/normation/plugins/changevalidation/api/ChangeRequestApi.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/snippet/ChangeRequestChangesForm.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/snippet/ChangeRequestDetails.scala
- change-validation/src/test/scala/com/normation/plugins/changevalidation/MockServices.scala
- change-validation/src/test/scala/com/normation/plugins/changevalidation/api/ChangeRequestApiTest.scala
https://issues.rudder.io/issues/25961
Make change-validation compile since https://github.com/Normation/rudder/pull/6046 (also refactoring from https://github.com/Normation/rudder/pull/6027)
> Fixes #25961: Impact of removing rest extractor lift-json methods on plugins

- scale-out-relay/src/main/resources/server-node-to-relay
https://issues.rudder.io/issues/25968
> Fixes #25968: Add a tip message after promote a node to relay to trigger agent run

- plugins-common/package-lock.json
- plugins-common/package.json
https://issues.rudder.io/issues/26048
> Fixes #26048: Update front-end dependencies

- change-validation/src/main/scala/com/normation/plugins/changevalidation/snippet/ChangeRequestManagement.scala
https://issues.rudder.io/issues/26094
> Fixes #26094: Impact of JsDataLine in change validation

- auth-backends/src/main/scala/bootstrap/rudder/plugin/AuthBackendsConf.scala
- auth-backends/src/main/scala/com/normation/plugins/authbackends/AuthBackendsPluginDef.scala
- branding/src/main/resources/template/brandingManagement.html
- branding/src/main/scala/bootstrap/rudder/plugin/BrandingPluginConf.scala
- branding/src/main/scala/com/normation/plugins/branding/BrandingConf.scala
- branding/src/main/scala/com/normation/plugins/branding/BrandingPluginDef.scala
- branding/src/main/scala/com/normation/plugins/branding/snippet/BrandingResources.scala
- branding/src/main/scala/com/normation/plugins/branding/snippet/CommonBranding.scala
- branding/src/main/scala/com/normation/plugins/branding/snippet/LoginBranding.scala
- change-validation/README.adoc
- change-validation/src/main/resources/template/ChangeValidationManagement.html
- change-validation/src/main/scala/bootstrap/rudder/plugin/ChangeValidationConf.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/ChangeValidationPluginDef.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/comet/WorkflowInformation.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/extension/ChangeValidationTab.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/snippet/ChangeRequestDetails.scala
- change-validation/src/test/resources/emails/change-validation-email.conf
- change-validation/src/test/scala/com/normation/plugins/changevalidation/TestEmailService.scala
- datasources/src/main/scala/com/normation/plugins/datasources/DataSourcesPluginDef.scala
- node-external-reports/src/main/scala/com/normation/plugins/nodeexternalreports/extension/CreateNodeDetailsExtension.scala
https://issues.rudder.io/issues/26095
See https://github.com/Normation/rudder/pull/6107 for explanation and details.
> Fixes #26095: Change main menu (public plugins)

- datasources/src/main/elm/sources/DataSourceForm.elm
- datasources/src/main/elm/sources/JsonDecoder.elm
- datasources/src/main/elm/sources/Model.elm
- datasources/src/main/elm/sources/Update.elm
- datasources/src/main/scala/bootstrap/rudder/plugin/DataSourcesConf.scala
- datasources/src/main/scala/com/normation/plugins/datasources/QueryService.scala
- datasources/src/main/scala/com/normation/plugins/datasources/Repository.scala
- datasources/src/main/scala/com/normation/plugins/datasources/Serialization.scala
- datasources/src/main/scala/com/normation/plugins/datasources/api/DataSourceApiImpl.scala
- datasources/src/test/resources/datasources_api/api_datasources.yml
- datasources/src/test/scala/com/normation/plugins/datasources/api/RestDataSourceTest.scala
https://issues.rudder.io/issues/26172
A LOT of problems: 
- error were not displayed in the main form for empty name and id
- empty URL was not checked for an error
- the ID was not normalized on save like it was displayed in the placehold
- backend says that the duration for schedule is in seconds, but front end uses minutes
- an error was silently absorbed on repository save failure
- repository is not enforcing the same rule than front end on ID allowed chars
Plus cleaning unused things.
> Fixes #26172: in datasources, ids are not normalized, thus creating problems at deletion

- auth-backends/README.adoc
https://issues.rudder.io/issues/26313
> Fixes #26313: Change path to webapp logfile in plugins documentation

- api-authorizations/src/main/elm/sources/UserApiToken.elm
https://issues.rudder.io/issues/26271
> Fixes #26271: API authorization menu could not open due to CSRF

- api-authorizations/src/main/scala/com/normation/plugins/apiauthorizations/UserTokenApiDefinition.scala
- auth-backends/src/test/scala/com/normation/plugins/authbackends/TestReadOidcConfig.scala
https://issues.rudder.io/issues/26316
Fix the default value in tests, and chimney mapping for https://github.com/Normation/rudder-plugins/pull/789
> Fixes #26316: Fix clear text token chimney implicits and default pivot attribute

- change-validation/src/main/elm/elm.json
https://issues.rudder.io/issues/26339
`elm-json uninstall elm-community/list-extra`
> Fixes #26339: Remove unused Elm dependencies in change-validation

- plugins-common-private/src/main/scala/com/normation/plugins/ParsePluginLicense.scala
https://issues.rudder.io/issues/26356
Of course, the license mapping needs to be changed in `plugins-common-private` too :sweat: #796
> Fixes #26356: Impact of plugins datastructures splitting in plugins-private

- api-authorizations/packaging/metadata
- auth-backends/packaging/metadata
- change-validation/packaging/metadata
- datasources/packaging/metadata
- scale-out-relay/packaging/metadata
https://issues.rudder.io/issues/26361
> Fixes #26361:  Add a new requires_license field in the metadata in rudder-plugins

- change-validation/src/main/resources/template/ChangeValidationManagement.html
https://issues.rudder.io/issues/26376
> Fixes #26376: data-lift="with-cached-resource"> typo in header 

- change-validation/src/main/scala/com/normation/plugins/changevalidation/ChangeRequestJson.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/DataTypes.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/snippet/ChangeRequestDetails.scala
- change-validation/src/test/scala/com/normation/plugins/changevalidation/ChangeRequestJdbcRepositoryTest.scala
- change-validation/src/test/scala/com/normation/plugins/changevalidation/TestEmailService.scala
- datasources/src/test/scala/com/normation/plugins/datasources/UpdateHttpDatasetTest.scala
- plugins-common/pom-template.xml
- scale-out-relay/src/main/scala/com/normation/plugins/scaleoutrelay/ScaleOutRelayService.scala
https://issues.rudder.io/issues/26460
Impact of https://github.com/Normation/rudder/pull/6223
> Fixes #26460: Impact of Scala 3 - 26459 - public plugins

- branding/packaging/metadata
- node-external-reports/packaging/metadata
https://issues.rudder.io/issues/26477
> Fixes #26477: Add missing licenses

- change-validation/src/main/resources/template/ChangeValidationManagement.html
- change-validation/src/main/scala/com/normation/plugins/changevalidation/snippet/ChangeValidationSettings.scala
https://issues.rudder.io/issues/26583
**Before:**
**After:**
> Fixes #26583: Navbar menu is broken

- change-validation/src/main/resources/change-validation.conf
- change-validation/src/main/resources/toserve/changevalidation/change-validation.js
https://issues.rudder.io/issues/26647
We missed the js file. Also corrected some URL in comments.
> Fixes #26647: Change validation links are all broken

- openscap/packaging/postinst
https://issues.rudder.io/issues/26670
> Fixes #26670: Openscap plugin postinst fails when the plugin is upgraded or re-installed

- Jenkinsfile-release
https://issues.rudder.io/issues/26676
> Fixes #26676: If an error occured while the plugin is being published to the repository, the build still succeeds

- change-validation/src/main/scala/com/normation/plugins/changevalidation/ValidationNeeded.scala
- change-validation/src/test/scala/com/normation/plugins/changevalidation/ValidationNeededTest.scala
https://issues.rudder.io/issues/26686
> Fixes #26686: The ValidationNeeded class doesn't have a test class

- change-validation/src/main/scala/bootstrap/rudder/plugin/ChangeValidationConf.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/ChangeRequestJdbcRepository.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/ChangeRequestRepository.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/ValidationNeeded.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/WorkflowJdbcRepository.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/WorkflowService.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/api/ChangeRequestApi.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/comet/WorkflowInformation.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/snippet/ChangeRequestChangesForm.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/snippet/ChangeRequestDetails.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/snippet/ChangeRequestManagement.scala
- change-validation/src/test/resources/changevalidation_api/api_changerequest.yml
- change-validation/src/test/scala/com/normation/plugins/changevalidation/ChangeRequestJdbcRepositoryTest.scala
- change-validation/src/test/scala/com/normation/plugins/changevalidation/MockServices.scala
- change-validation/src/test/scala/com/normation/plugins/changevalidation/ValidationNeededTest.scala
- change-validation/src/test/scala/com/normation/plugins/changevalidation/WorkflowJdbcRepositoryTest.scala
- change-validation/src/test/scala/com/normation/plugins/changevalidation/api/ChangeRequestApiTest.scala
https://issues.rudder.io/issues/26698
> Fixes #26698: Refactoring of ValidationNeeded class : replace type Box with IOResult

- change-validation/src/main/scala/bootstrap/rudder/plugin/ChangeValidationConf.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/ChangeRequestJson.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/WorkflowJdbcRepository.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/api/WorkflowInternalApi.scala
- change-validation/src/test/resources/changevalidation_api/api_workflowinternal.yml
- change-validation/src/test/scala/com/normation/plugins/changevalidation/MockServices.scala
- change-validation/src/test/scala/com/normation/plugins/changevalidation/WorkflowJdbcRepositoryTest.scala
- change-validation/src/test/scala/com/normation/plugins/changevalidation/api/WorkflowInternalApiTest.scala
https://issues.rudder.io/issues/26760
> Fixes #26760: Add a new internal endpoint in order to replace WorkflowInformation

- change-validation/src/main/scala/com/normation/plugins/changevalidation/ChangeRequestJdbcRepository.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/WorkflowJdbcRepository.scala
https://issues.rudder.io/issues/26770
> Fixes #26770: WoChangeRequestJdbcRepository#updateChangeRequest executes several transactions

- change-validation/src/main/resources/template/ChangeValidationManagement.html
- change-validation/src/main/style/change-validation.css
https://issues.rudder.io/issues/26794
This PR is correlated with the following: https://github.com/Normation/rudder/pull/6338
> Fixes #26794: We cannot scroll to the bottom change validation tab

- change-validation/src/main/scala/com/normation/plugins/changevalidation/snippet/ChangeRequestChangesForm.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/snippet/ChangeRequestDetails.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/snippet/ChangeRequestEditForm.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/snippet/ChangeValidationSettings.scala
https://issues.rudder.io/issues/26775
> Fixes #26775: Refactoring : use ZIO instead of Box in change-validation snippets

- change-validation/src/test/scala/com/normation/plugins/changevalidation/ChangeRequestJdbcRepositoryTest.scala
https://issues.rudder.io/issues/26802
> Fixes #26802: Change request JDBC repo tests has the wrong error type in tests

- auth-backends/README.adoc
https://issues.rudder.io/issues/26713
> Fixes #26713: Documentation for OIDC opaque/JWT bearer tokens 

- auth-backends/README.adoc
https://issues.rudder.io/issues/26933
> Fixes #26933: Clarify how to setup multiple OIDC providers

- change-validation/src/main/scala/com/normation/plugins/changevalidation/ChangeRequestJdbcRepository.scala
https://issues.rudder.io/issues/26953
The pending change requests that are related to a given resource (i.e. node group, rule, or directive) are shown on the resource's dedicated page. However, if one or more of the change requests has had an unserialization error, this will not be shown on the page. This PR aims to show an error in the page's UI in case this happens.
The error display UI is inconsistent across resource types for now, but this error should be very rare : it should be impossible to create an incorrect change request XML by using the public API.
Error display for a nodegroup : 
Error display for a rule : 
Error display for a directive : 
A change request whose unserialization has failed will not appear in the full change request table. 
Attempting to modify a changerequest …
> Fixes #26953: ChangeRequestJdbcRepository ignores error when change request unserialization fails

- plugins-common-private/src/main/scala/com/normation/plugins/LicensedPluginCheck.scala
https://issues.rudder.io/issues/27089
> Fixes #27089: Chimney error in plugins-common-private

- auth-backends/README.adoc
https://issues.rudder.io/issues/27101
> Fixes #27101: OAuth2 documentation is missing tenants for users

- .gitignore
https://issues.rudder.io/issues/27158
> Fixes #27158:  Add .scala.semanticdb in gitignore (plugins)

- api-authorizations/src/main/elm/elm.json
- auth-backends/src/main/elm/elm.json
- branding/src/main/elm/elm.json
- change-validation/src/main/elm/elm.json
- datasources/src/main/elm/elm.json
- plugins-common/gulpfile.mjs
- plugins-common/package-lock.json
- plugins-common/package.json
- plugins-common/review/elm.json
https://issues.rudder.io/issues/27150
Same dependencies resolution as in https://github.com/Normation/rudder/pull/6460 for gulp and sass.
Other than that there is nothing in particular...
> Fixes #27150: Update front-end dependencies in plugins

- change-validation/src/test/scala/com/normation/plugins/changevalidation/ValidatedUserJdbcRepositoryTest.scala
https://issues.rudder.io/issues/27190
> Fixes #27190: Impact of argon2id parameters on change-validation tests

- change-validation/src/main/scala/com/normation/plugins/changevalidation/WorkflowService.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/snippet/ChangeRequestChangesForm.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/snippet/ChangeRequestManagement.scala
- datasources/src/main/scala/com/normation/plugins/datasources/QueryService.scala
- datasources/src/main/scala/com/normation/plugins/datasources/api/DataSourceApiImpl.scala
- scale-out-relay/src/main/scala/com/normation/plugins/scaleoutrelay/api/ScaleOutRelayApi.scala
https://issues.rudder.io/issues/27238
Counter part of https://github.com/Normation/rudder/pull/6452 on plugins
> Fixes #27238: Impact of DateTime to Instant switch on plugins

- change-validation/src/main/elm/elm-git.json
https://issues.rudder.io/issues/27260
> Fixes #27260: Elm git library needs cloning using HTTPS

- plugins-common/pom-template.xml
https://issues.rudder.io/issues/27271
> Fixes #27271: Report change in dependencies to plugins

- change-validation/src/main/elm/elm.json
- change-validation/src/main/elm/sources/ChangeRequestChangesForm.elm
- change-validation/src/main/elm/sources/ChangeRequestDetails.elm
- change-validation/src/main/elm/sources/ChangeRequestEditForm.elm
- change-validation/src/main/elm/sources/ErrorMessages.elm
- change-validation/src/main/elm/sources/RudderDataTypes.elm
- change-validation/src/main/elm/sources/RudderLinkUtil.elm
- change-validation/src/main/resources/template/changeRequest.html
- change-validation/src/main/scala/com/normation/plugins/changevalidation/ChangeRequestChangesJson.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/WorkflowService.scala
- change-validation/src/main/scala/com/normation/plugins/changevalidation/api/WorkflowInternalApi.scala
https://issues.rudder.io/issues/26907
> Fixes #26907: Migrate the ChangeRequestDetails snippet from Scala/lift to Elm

- auth-backends/README.adoc
https://issues.rudder.io/issues/27320
> Fixes #27320: How to configure a proxy for SSO feaure

- change-validation/src/main/scala/com/normation/plugins/changevalidation/comet/WorkflowInformation.scala
https://issues.rudder.io/issues/27581
> Fixes #27581: Change request counts are loading even if the plugin is disabled
